LOAD DATA
CHARACTERSET RU8PC866
INTO TABLE ARM_BUFFER_PSV
APPEND
TRAILING NULLCOLS 
(
ID SEQUENCE(1,1),
TEXT position(1:250) CHAR NULLIF TEXT=BLANKS,
FLAG position(4:4) CHAR "DECODE(:FLAG,null,'I',DECODE(:FLAG,'-','I','D'))" 
)  
