-- Новые tablespaces

DROP TABLESPACE AUDIT_KERNEL INCLUDING CONTENTS;

CREATE TABLESPACE AUDIT_KERNEL DATAFILE 
  'D:\ORACLE\KERNEL\ORADATA\AUDIT01.DBF' SIZE 1000M AUTOEXTEND ON NEXT 100M MAXSIZE UNLIMITED
NOLOGGING
ONLINE
PERMANENT
EXTENT MANAGEMENT LOCAL UNIFORM SIZE 128K;


DROP TABLESPACE IDX INCLUDING CONTENTS;

CREATE TABLESPACE IDX DATAFILE 
  'D:\ORACLE\KERNEL\ORADATA\INDX01.DBF' SIZE 20000M AUTOEXTEND ON NEXT 100M MAXSIZE UNLIMITED
NOLOGGING
ONLINE
PERMANENT
EXTENT MANAGEMENT LOCAL UNIFORM SIZE 256K;


DROP TABLESPACE REPL INCLUDING CONTENTS;

CREATE TABLESPACE REPL DATAFILE 
  'D:\ORACLE\KERNEL\ORADATA\REPL01.DBF' SIZE 5000M AUTOEXTEND ON NEXT 100M MAXSIZE UNLIMITED
NOLOGGING
ONLINE
PERMANENT
EXTENT MANAGEMENT LOCAL UNIFORM SIZE 128K;


ALTER DATABASE DATAFILE 'D:\ORACLE\KERNEL\ORADATA\SYSTEM01.DBF' AUTOEXTEND ON  NEXT 100M MAXSIZE UNLIMITED;

ALTER DATABASE DATAFILE 'D:\ORACLE\KERNEL\ORADATA\SYSAUX01.DBF' AUTOEXTEND ON  NEXT 100M MAXSIZE UNLIMITED;

ALTER DATABASE TEMPFILE 'D:\ORACLE\KERNEL\ORADATA\TEMP01.DBF' RESIZE 600M;

ALTER DATABASE TEMPFILE 'D:\ORACLE\KERNEL\ORADATA\TEMP01.DBF' AUTOEXTEND ON  NEXT 100M MAXSIZE UNLIMITED;

ALTER DATABASE DATAFILE 'D:\ORACLE\KERNEL\ORADATA\UNDOTBS01.DBF' RESIZE 1000M;

ALTER DATABASE DATAFILE 'D:\ORACLE\KERNEL\ORADATA\UNDOTBS01.DBF' AUTOEXTEND ON  NEXT 100M MAXSIZE UNLIMITED;

ALTER DATABASE DATAFILE 'D:\ORACLE\KERNEL\ORADATA\USERS01.DBF' RESIZE 30000M;

ALTER DATABASE DATAFILE 'D:\ORACLE\KERNEL\ORADATA\USERS01.DBF' AUTOEXTEND ON  NEXT 100M MAXSIZE UNLIMITED;
