CREATE PROFILE ADMIN LIMIT
  SESSIONS_PER_USER UNLIMITED
  CPU_PER_SESSION UNLIMITED
  CPU_PER_CALL UNLIMITED
  CONNECT_TIME UNLIMITED
  IDLE_TIME UNLIMITED
  LOGICAL_READS_PER_SESSION UNLIMITED
  LOGICAL_READS_PER_CALL UNLIMITED
  COMPOSITE_LIMIT UNLIMITED
  PRIVATE_SGA UNLIMITED
  FAILED_LOGIN_ATTEMPTS UNLIMITED
  PASSWORD_LIFE_TIME UNLIMITED
  PASSWORD_REUSE_TIME UNLIMITED
  PASSWORD_REUSE_MAX UNLIMITED
  PASSWORD_LOCK_TIME UNLIMITED
  PASSWORD_GRACE_TIME UNLIMITED
  PASSWORD_VERIFY_FUNCTION NULL;


CREATE PROFILE FOX_PROFILE LIMIT
  SESSIONS_PER_USER UNLIMITED
  CPU_PER_SESSION UNLIMITED
  CPU_PER_CALL UNLIMITED
  CONNECT_TIME UNLIMITED
  IDLE_TIME UNLIMITED
  LOGICAL_READS_PER_SESSION UNLIMITED
  LOGICAL_READS_PER_CALL UNLIMITED
  COMPOSITE_LIMIT UNLIMITED
  PRIVATE_SGA UNLIMITED
  FAILED_LOGIN_ATTEMPTS 10
  PASSWORD_LIFE_TIME UNLIMITED
  PASSWORD_REUSE_TIME UNLIMITED
  PASSWORD_REUSE_MAX UNLIMITED
  PASSWORD_LOCK_TIME UNLIMITED
  PASSWORD_GRACE_TIME UNLIMITED
  PASSWORD_VERIFY_FUNCTION NULL;


CREATE PROFILE TEST LIMIT
  SESSIONS_PER_USER 1
  CPU_PER_SESSION UNLIMITED
  CPU_PER_CALL UNLIMITED
  CONNECT_TIME UNLIMITED
  IDLE_TIME 5
  LOGICAL_READS_PER_SESSION UNLIMITED
  LOGICAL_READS_PER_CALL UNLIMITED
  COMPOSITE_LIMIT UNLIMITED
  PRIVATE_SGA UNLIMITED
  FAILED_LOGIN_ATTEMPTS UNLIMITED
  PASSWORD_LIFE_TIME UNLIMITED
  PASSWORD_REUSE_TIME UNLIMITED
  PASSWORD_REUSE_MAX UNLIMITED
  PASSWORD_LOCK_TIME UNLIMITED
  PASSWORD_GRACE_TIME UNLIMITED
  PASSWORD_VERIFY_FUNCTION NULL;


CREATE PROFILE USERS LIMIT
  SESSIONS_PER_USER 5
  CPU_PER_SESSION UNLIMITED
  CPU_PER_CALL UNLIMITED
  CONNECT_TIME UNLIMITED
  IDLE_TIME 1000
  LOGICAL_READS_PER_SESSION UNLIMITED
  LOGICAL_READS_PER_CALL UNLIMITED
  COMPOSITE_LIMIT UNLIMITED
  PRIVATE_SGA UNLIMITED
  FAILED_LOGIN_ATTEMPTS UNLIMITED
  PASSWORD_LIFE_TIME UNLIMITED
  PASSWORD_REUSE_TIME UNLIMITED
  PASSWORD_REUSE_MAX UNLIMITED
  PASSWORD_LOCK_TIME UNLIMITED
  PASSWORD_GRACE_TIME UNLIMITED
  PASSWORD_VERIFY_FUNCTION NULL;



CREATE USER ADMAZS
  IDENTIFIED BY VALUES '304AABD7DE6B0C1F'
  DEFAULT TABLESPACE USERS
  TEMPORARY TABLESPACE TEMP
  PROFILE USERS
  ACCOUNT UNLOCK;
  -- 5 Roles for ADMAZS 
  GRANT AQ_ADMINISTRATOR_ROLE TO ADMAZS;
  GRANT CONNECT TO ADMAZS;
  GRANT KERNEL_MANAGER TO ADMAZS;
  GRANT REPORT TO ADMAZS;
  GRANT WORKSPACE TO ADMAZS;
  ALTER USER ADMAZS DEFAULT ROLE AQ_ADMINISTRATOR_ROLE, CONNECT, KERNEL_MANAGER;
  -- 1 System Privilege for ADMAZS 
  GRANT ADMINISTER DATABASE TRIGGER TO ADMAZS;


CREATE USER ARCH
  IDENTIFIED BY VALUES 'F0B2D212ACB9B839'
  DEFAULT TABLESPACE USERS
  TEMPORARY TABLESPACE TEMP
  PROFILE ADMIN
  ACCOUNT UNLOCK;
  -- 2 Roles for ARCH 
  GRANT CONNECT TO ARCH;
  GRANT EXP_FULL_DATABASE TO ARCH;
  ALTER USER ARCH DEFAULT ROLE ALL;


CREATE USER ARIN
  IDENTIFIED BY VALUES '8E66BC7C2B1BAA28'
  DEFAULT TABLESPACE USERS
  TEMPORARY TABLESPACE TEMP
  PROFILE USERS
  ACCOUNT UNLOCK;
  -- 3 Roles for ARIN 
  GRANT CONNECT TO ARIN;
  GRANT REPORT TO ARIN;
  GRANT WORKSPACE TO ARIN;
  ALTER USER ARIN DEFAULT ROLE CONNECT;


CREATE USER AUDIT_USER
  IDENTIFIED BY VALUES 'AABBF8AD3D864F95'
  DEFAULT TABLESPACE AUDIT_KERNEL
  TEMPORARY TABLESPACE TEMP
  PROFILE ADMIN
  ACCOUNT LOCK;
  -- 2 Roles for AUDIT_USER 
  GRANT CONNECT TO AUDIT_USER;
  GRANT QUEST_SL_USER TO AUDIT_USER;
  ALTER USER AUDIT_USER DEFAULT ROLE CONNECT;
  -- 1 Tablespace Quota for AUDIT_USER 
  ALTER USER AUDIT_USER QUOTA UNLIMITED ON AUDIT_KERNEL;


CREATE USER AUDIT_USER_R3
  IDENTIFIED BY VALUES 'EB6670ABAB419298'
  DEFAULT TABLESPACE AUDIT_KERNEL
  TEMPORARY TABLESPACE TEMP
  PROFILE ADMIN
  ACCOUNT LOCK;
  -- 3 Roles for AUDIT_USER_R3 
  GRANT CONNECT TO AUDIT_USER_R3;
  GRANT REPORT TO AUDIT_USER_R3;
  GRANT WORKSPACE TO AUDIT_USER_R3;
  ALTER USER AUDIT_USER_R3 DEFAULT ROLE CONNECT;
  -- 1 Tablespace Quota for AUDIT_USER_R3 
  ALTER USER AUDIT_USER_R3 QUOTA UNLIMITED ON AUDIT_KERNEL;


CREATE USER AZK1AR
  IDENTIFIED BY VALUES 'E841DFEA66E9AA1B'
  DEFAULT TABLESPACE USERS
  TEMPORARY TABLESPACE TEMP
  PROFILE USERS
  ACCOUNT UNLOCK;
  -- 3 Roles for AZK1AR 
  GRANT CONNECT TO AZK1AR;
  GRANT REPORT TO AZK1AR;
  GRANT WORKSPACE TO AZK1AR;
  ALTER USER AZK1AR DEFAULT ROLE CONNECT;


CREATE USER AZS
  IDENTIFIED BY VALUES 'AFF0AC5B57ED6F1C'
  DEFAULT TABLESPACE USERS
  TEMPORARY TABLESPACE TEMP
  PROFILE USERS
  ACCOUNT UNLOCK;
  -- 3 Roles for AZS 
  GRANT CONNECT TO AZS;
  GRANT REPORT TO AZS;
  GRANT WORKSPACE TO AZS;
  ALTER USER AZS DEFAULT ROLE CONNECT;


CREATE USER AZS1
  IDENTIFIED BY VALUES '875F21443B1BBD7A'
  DEFAULT TABLESPACE USERS
  TEMPORARY TABLESPACE TEMP
  PROFILE USERS
  ACCOUNT UNLOCK;
  -- 3 Roles for AZS1 
  GRANT CONNECT TO AZS1;
  GRANT REPORT TO AZS1;
  GRANT WORKSPACE TO AZS1;
  ALTER USER AZS1 DEFAULT ROLE CONNECT;


CREATE USER AZS10
  IDENTIFIED BY VALUES 'A191BC78BE81D661'
  DEFAULT TABLESPACE USERS
  TEMPORARY TABLESPACE TEMP
  PROFILE USERS
  ACCOUNT UNLOCK;
  -- 3 Roles for AZS10 
  GRANT CONNECT TO AZS10;
  GRANT REPORT TO AZS10;
  GRANT WORKSPACE TO AZS10;
  ALTER USER AZS10 DEFAULT ROLE CONNECT;


CREATE USER AZS10AR
  IDENTIFIED BY VALUES '371594AB8B73681B'
  DEFAULT TABLESPACE USERS
  TEMPORARY TABLESPACE TEMP
  PROFILE USERS
  ACCOUNT UNLOCK;
  -- 3 Roles for AZS10AR 
  GRANT CONNECT TO AZS10AR;
  GRANT REPORT TO AZS10AR;
  GRANT WORKSPACE TO AZS10AR;
  ALTER USER AZS10AR DEFAULT ROLE CONNECT;


CREATE USER AZS11
  IDENTIFIED BY VALUES '25DD1F93C3BFC5D3'
  DEFAULT TABLESPACE USERS
  TEMPORARY TABLESPACE TEMP
  PROFILE USERS
  ACCOUNT UNLOCK;
  -- 3 Roles for AZS11 
  GRANT CONNECT TO AZS11;
  GRANT REPORT TO AZS11;
  GRANT WORKSPACE TO AZS11;
  ALTER USER AZS11 DEFAULT ROLE CONNECT;


CREATE USER AZS11AR
  IDENTIFIED BY VALUES '1B22BF44FF17F58A'
  DEFAULT TABLESPACE USERS
  TEMPORARY TABLESPACE TEMP
  PROFILE USERS
  ACCOUNT UNLOCK;
  -- 3 Roles for AZS11AR 
  GRANT CONNECT TO AZS11AR;
  GRANT REPORT TO AZS11AR;
  GRANT WORKSPACE TO AZS11AR;
  ALTER USER AZS11AR DEFAULT ROLE CONNECT;


CREATE USER AZS12AR
  IDENTIFIED BY VALUES '8664D04DD5B63D5A'
  DEFAULT TABLESPACE USERS
  TEMPORARY TABLESPACE TEMP
  PROFILE USERS
  ACCOUNT UNLOCK;
  -- 3 Roles for AZS12AR 
  GRANT CONNECT TO AZS12AR;
  GRANT REPORT TO AZS12AR;
  GRANT WORKSPACE TO AZS12AR;
  ALTER USER AZS12AR DEFAULT ROLE CONNECT;


CREATE USER AZS13
  IDENTIFIED BY VALUES '2C1D3E00A75798EA'
  DEFAULT TABLESPACE USERS
  TEMPORARY TABLESPACE TEMP
  PROFILE USERS
  ACCOUNT UNLOCK;
  -- 3 Roles for AZS13 
  GRANT CONNECT TO AZS13;
  GRANT REPORT TO AZS13;
  GRANT WORKSPACE TO AZS13;
  ALTER USER AZS13 DEFAULT ROLE CONNECT;


CREATE USER AZS13AR
  IDENTIFIED BY VALUES '53F4584AC1733F82'
  DEFAULT TABLESPACE USERS
  TEMPORARY TABLESPACE TEMP
  PROFILE USERS
  ACCOUNT UNLOCK;
  -- 3 Roles for AZS13AR 
  GRANT CONNECT TO AZS13AR;
  GRANT REPORT TO AZS13AR;
  GRANT WORKSPACE TO AZS13AR;
  ALTER USER AZS13AR DEFAULT ROLE CONNECT;


CREATE USER AZS15AR
  IDENTIFIED BY VALUES '32843B3D1D1E3E7F'
  DEFAULT TABLESPACE USERS
  TEMPORARY TABLESPACE TEMP
  PROFILE USERS
  ACCOUNT UNLOCK;
  -- 3 Roles for AZS15AR 
  GRANT CONNECT TO AZS15AR;
  GRANT REPORT TO AZS15AR;
  GRANT WORKSPACE TO AZS15AR;
  ALTER USER AZS15AR DEFAULT ROLE CONNECT;


CREATE USER AZS16
  IDENTIFIED BY VALUES '8F975F3369D57DE1'
  DEFAULT TABLESPACE USERS
  TEMPORARY TABLESPACE TEMP
  PROFILE USERS
  ACCOUNT UNLOCK;
  -- 3 Roles for AZS16 
  GRANT CONNECT TO AZS16;
  GRANT REPORT TO AZS16;
  GRANT WORKSPACE TO AZS16;
  ALTER USER AZS16 DEFAULT ROLE CONNECT;


CREATE USER AZS16AR
  IDENTIFIED BY VALUES '3BAFB62B37DF255B'
  DEFAULT TABLESPACE USERS
  TEMPORARY TABLESPACE TEMP
  PROFILE USERS
  ACCOUNT UNLOCK;
  -- 3 Roles for AZS16AR 
  GRANT CONNECT TO AZS16AR;
  GRANT REPORT TO AZS16AR;
  GRANT WORKSPACE TO AZS16AR;
  ALTER USER AZS16AR DEFAULT ROLE CONNECT;


CREATE USER AZS17
  IDENTIFIED BY VALUES '5433729343581639'
  DEFAULT TABLESPACE USERS
  TEMPORARY TABLESPACE TEMP
  PROFILE USERS
  ACCOUNT UNLOCK;
  -- 3 Roles for AZS17 
  GRANT CONNECT TO AZS17;
  GRANT REPORT TO AZS17;
  GRANT WORKSPACE TO AZS17;
  ALTER USER AZS17 DEFAULT ROLE CONNECT;


CREATE USER AZS17AR
  IDENTIFIED BY VALUES '959FAA656F4CF96A'
  DEFAULT TABLESPACE USERS
  TEMPORARY TABLESPACE TEMP
  PROFILE USERS
  ACCOUNT UNLOCK;
  -- 3 Roles for AZS17AR 
  GRANT CONNECT TO AZS17AR;
  GRANT REPORT TO AZS17AR;
  GRANT WORKSPACE TO AZS17AR;
  ALTER USER AZS17AR DEFAULT ROLE CONNECT;


CREATE USER AZS18
  IDENTIFIED BY VALUES '76548EEC8EB8E672'
  DEFAULT TABLESPACE USERS
  TEMPORARY TABLESPACE TEMP
  PROFILE USERS
  ACCOUNT UNLOCK;
  -- 3 Roles for AZS18 
  GRANT CONNECT TO AZS18;
  GRANT REPORT TO AZS18;
  GRANT WORKSPACE TO AZS18;
  ALTER USER AZS18 DEFAULT ROLE CONNECT;


CREATE USER AZS18AR
  IDENTIFIED BY VALUES 'DDA53B4C21C1218B'
  DEFAULT TABLESPACE USERS
  TEMPORARY TABLESPACE TEMP
  PROFILE USERS
  ACCOUNT UNLOCK;
  -- 3 Roles for AZS18AR 
  GRANT CONNECT TO AZS18AR;
  GRANT REPORT TO AZS18AR;
  GRANT WORKSPACE TO AZS18AR;
  ALTER USER AZS18AR DEFAULT ROLE CONNECT;


CREATE USER AZS19
  IDENTIFIED BY VALUES '36FD44404E17FCB2'
  DEFAULT TABLESPACE USERS
  TEMPORARY TABLESPACE TEMP
  PROFILE USERS
  ACCOUNT UNLOCK;
  -- 3 Roles for AZS19 
  GRANT CONNECT TO AZS19;
  GRANT REPORT TO AZS19;
  GRANT WORKSPACE TO AZS19;
  ALTER USER AZS19 DEFAULT ROLE CONNECT;


CREATE USER AZS19AR
  IDENTIFIED BY VALUES '892E9631395F6169'
  DEFAULT TABLESPACE USERS
  TEMPORARY TABLESPACE TEMP
  PROFILE USERS
  ACCOUNT UNLOCK;
  -- 3 Roles for AZS19AR 
  GRANT CONNECT TO AZS19AR;
  GRANT REPORT TO AZS19AR;
  GRANT WORKSPACE TO AZS19AR;
  ALTER USER AZS19AR DEFAULT ROLE CONNECT;


CREATE USER AZS1NM
  IDENTIFIED BY VALUES '347B2BF0DFD7B72C'
  DEFAULT TABLESPACE USERS
  TEMPORARY TABLESPACE TEMP
  PROFILE USERS
  ACCOUNT UNLOCK;
  -- 3 Roles for AZS1NM 
  GRANT CONNECT TO AZS1NM;
  GRANT REPORT TO AZS1NM;
  GRANT WORKSPACE TO AZS1NM;
  ALTER USER AZS1NM DEFAULT ROLE CONNECT;


CREATE USER AZS2
  IDENTIFIED BY VALUES 'BFB874374BBA47ED'
  DEFAULT TABLESPACE USERS
  TEMPORARY TABLESPACE TEMP
  PROFILE USERS
  ACCOUNT UNLOCK;
  -- 3 Roles for AZS2 
  GRANT CONNECT TO AZS2;
  GRANT REPORT TO AZS2;
  GRANT WORKSPACE TO AZS2;
  ALTER USER AZS2 DEFAULT ROLE CONNECT;


CREATE USER AZS20
  IDENTIFIED BY VALUES '4B5BDD2F3DC2757F'
  DEFAULT TABLESPACE USERS
  TEMPORARY TABLESPACE TEMP
  PROFILE USERS
  ACCOUNT UNLOCK;
  -- 3 Roles for AZS20 
  GRANT CONNECT TO AZS20;
  GRANT REPORT TO AZS20;
  GRANT WORKSPACE TO AZS20;
  ALTER USER AZS20 DEFAULT ROLE CONNECT;


CREATE USER AZS20AR
  IDENTIFIED BY VALUES '4B398381662A736A'
  DEFAULT TABLESPACE USERS
  TEMPORARY TABLESPACE TEMP
  PROFILE USERS
  ACCOUNT UNLOCK;
  -- 3 Roles for AZS20AR 
  GRANT CONNECT TO AZS20AR;
  GRANT REPORT TO AZS20AR;
  GRANT WORKSPACE TO AZS20AR;
  ALTER USER AZS20AR DEFAULT ROLE CONNECT;


CREATE USER AZS21
  IDENTIFIED BY VALUES '5A56CFE32A2E0CC1'
  DEFAULT TABLESPACE USERS
  TEMPORARY TABLESPACE TEMP
  PROFILE USERS
  ACCOUNT UNLOCK;
  -- 3 Roles for AZS21 
  GRANT CONNECT TO AZS21;
  GRANT REPORT TO AZS21;
  GRANT WORKSPACE TO AZS21;
  ALTER USER AZS21 DEFAULT ROLE CONNECT;


CREATE USER AZS22
  IDENTIFIED BY VALUES '46C876416CD172CE'
  DEFAULT TABLESPACE USERS
  TEMPORARY TABLESPACE TEMP
  PROFILE USERS
  ACCOUNT UNLOCK;
  -- 3 Roles for AZS22 
  GRANT CONNECT TO AZS22;
  GRANT REPORT TO AZS22;
  GRANT WORKSPACE TO AZS22;
  ALTER USER AZS22 DEFAULT ROLE CONNECT;


CREATE USER AZS22AR
  IDENTIFIED BY VALUES '65D0245F83BF11E7'
  DEFAULT TABLESPACE USERS
  TEMPORARY TABLESPACE TEMP
  PROFILE USERS
  ACCOUNT UNLOCK;
  -- 3 Roles for AZS22AR 
  GRANT CONNECT TO AZS22AR;
  GRANT REPORT TO AZS22AR;
  GRANT WORKSPACE TO AZS22AR;
  ALTER USER AZS22AR DEFAULT ROLE CONNECT;


CREATE USER AZS23
  IDENTIFIED BY VALUES 'E58F5DD6FA0DADCC'
  DEFAULT TABLESPACE USERS
  TEMPORARY TABLESPACE TEMP
  PROFILE USERS
  ACCOUNT UNLOCK;
  -- 3 Roles for AZS23 
  GRANT CONNECT TO AZS23;
  GRANT REPORT TO AZS23;
  GRANT WORKSPACE TO AZS23;
  ALTER USER AZS23 DEFAULT ROLE CONNECT;


CREATE USER AZS24
  IDENTIFIED BY VALUES 'CB6DF46EC10891A8'
  DEFAULT TABLESPACE USERS
  TEMPORARY TABLESPACE TEMP
  PROFILE USERS
  ACCOUNT UNLOCK;
  -- 3 Roles for AZS24 
  GRANT CONNECT TO AZS24;
  GRANT REPORT TO AZS24;
  GRANT WORKSPACE TO AZS24;
  ALTER USER AZS24 DEFAULT ROLE CONNECT;


CREATE USER AZS25
  IDENTIFIED BY VALUES '4D731D1519894E82'
  DEFAULT TABLESPACE USERS
  TEMPORARY TABLESPACE TEMP
  PROFILE USERS
  ACCOUNT UNLOCK;
  -- 3 Roles for AZS25 
  GRANT CONNECT TO AZS25;
  GRANT REPORT TO AZS25;
  GRANT WORKSPACE TO AZS25;
  ALTER USER AZS25 DEFAULT ROLE CONNECT;


CREATE USER AZS25AR
  IDENTIFIED BY VALUES 'ABDD3E663646BFB5'
  DEFAULT TABLESPACE USERS
  TEMPORARY TABLESPACE TEMP
  PROFILE USERS
  ACCOUNT UNLOCK;
  -- 3 Roles for AZS25AR 
  GRANT CONNECT TO AZS25AR;
  GRANT REPORT TO AZS25AR;
  GRANT WORKSPACE TO AZS25AR;
  ALTER USER AZS25AR DEFAULT ROLE CONNECT;


CREATE USER AZS26
  IDENTIFIED BY VALUES 'C6CC904E5E13AEA7'
  DEFAULT TABLESPACE USERS
  TEMPORARY TABLESPACE TEMP
  PROFILE USERS
  ACCOUNT UNLOCK;
  -- 3 Roles for AZS26 
  GRANT CONNECT TO AZS26;
  GRANT REPORT TO AZS26;
  GRANT WORKSPACE TO AZS26;
  ALTER USER AZS26 DEFAULT ROLE CONNECT;


CREATE USER AZS27
  IDENTIFIED BY VALUES 'C94351639DF428D7'
  DEFAULT TABLESPACE USERS
  TEMPORARY TABLESPACE TEMP
  PROFILE USERS
  ACCOUNT UNLOCK;
  -- 3 Roles for AZS27 
  GRANT CONNECT TO AZS27;
  GRANT REPORT TO AZS27;
  GRANT WORKSPACE TO AZS27;
  ALTER USER AZS27 DEFAULT ROLE CONNECT;


CREATE USER AZS28
  IDENTIFIED BY VALUES 'A90E6456AC876C22'
  DEFAULT TABLESPACE USERS
  TEMPORARY TABLESPACE TEMP
  PROFILE USERS
  ACCOUNT UNLOCK;
  -- 3 Roles for AZS28 
  GRANT CONNECT TO AZS28;
  GRANT REPORT TO AZS28;
  GRANT WORKSPACE TO AZS28;
  ALTER USER AZS28 DEFAULT ROLE CONNECT;


CREATE USER AZS29
  IDENTIFIED BY VALUES '4A23346732494822'
  DEFAULT TABLESPACE USERS
  TEMPORARY TABLESPACE TEMP
  PROFILE USERS
  ACCOUNT UNLOCK;
  -- 3 Roles for AZS29 
  GRANT CONNECT TO AZS29;
  GRANT REPORT TO AZS29;
  GRANT WORKSPACE TO AZS29;
  ALTER USER AZS29 DEFAULT ROLE CONNECT;


CREATE USER AZS2AR
  IDENTIFIED BY VALUES '262607813A99F06B'
  DEFAULT TABLESPACE USERS
  TEMPORARY TABLESPACE TEMP
  PROFILE USERS
  ACCOUNT UNLOCK;
  -- 3 Roles for AZS2AR 
  GRANT CONNECT TO AZS2AR;
  GRANT REPORT TO AZS2AR;
  GRANT WORKSPACE TO AZS2AR;
  ALTER USER AZS2AR DEFAULT ROLE CONNECT;


CREATE USER AZS2NM
  IDENTIFIED BY VALUES 'DE5EEB7C8A42AD57'
  DEFAULT TABLESPACE USERS
  TEMPORARY TABLESPACE TEMP
  PROFILE USERS
  ACCOUNT UNLOCK;
  -- 3 Roles for AZS2NM 
  GRANT CONNECT TO AZS2NM;
  GRANT REPORT TO AZS2NM;
  GRANT WORKSPACE TO AZS2NM;
  ALTER USER AZS2NM DEFAULT ROLE CONNECT;


CREATE USER AZS3
  IDENTIFIED BY VALUES 'A437639874181244'
  DEFAULT TABLESPACE USERS
  TEMPORARY TABLESPACE TEMP
  PROFILE USERS
  ACCOUNT UNLOCK;
  -- 3 Roles for AZS3 
  GRANT CONNECT TO AZS3;
  GRANT REPORT TO AZS3;
  GRANT WORKSPACE TO AZS3;
  ALTER USER AZS3 DEFAULT ROLE CONNECT;


CREATE USER AZS30
  IDENTIFIED BY VALUES 'DC3205236C883722'
  DEFAULT TABLESPACE USERS
  TEMPORARY TABLESPACE TEMP
  PROFILE USERS
  ACCOUNT UNLOCK;
  -- 3 Roles for AZS30 
  GRANT CONNECT TO AZS30;
  GRANT REPORT TO AZS30;
  GRANT WORKSPACE TO AZS30;
  ALTER USER AZS30 DEFAULT ROLE CONNECT;


CREATE USER AZS31
  IDENTIFIED BY VALUES '3CA27793FC4319D6'
  DEFAULT TABLESPACE USERS
  TEMPORARY TABLESPACE TEMP
  PROFILE USERS
  ACCOUNT UNLOCK;
  -- 3 Roles for AZS31 
  GRANT CONNECT TO AZS31;
  GRANT REPORT TO AZS31;
  GRANT WORKSPACE TO AZS31;
  ALTER USER AZS31 DEFAULT ROLE CONNECT;


CREATE USER AZS32
  IDENTIFIED BY VALUES '38A85709101B42CC'
  DEFAULT TABLESPACE USERS
  TEMPORARY TABLESPACE TEMP
  PROFILE USERS
  ACCOUNT UNLOCK;
  -- 3 Roles for AZS32 
  GRANT CONNECT TO AZS32;
  GRANT REPORT TO AZS32;
  GRANT WORKSPACE TO AZS32;
  ALTER USER AZS32 DEFAULT ROLE CONNECT;


CREATE USER AZS33
  IDENTIFIED BY VALUES '38FEACA8E4175A42'
  DEFAULT TABLESPACE USERS
  TEMPORARY TABLESPACE TEMP
  PROFILE USERS
  ACCOUNT UNLOCK;
  -- 3 Roles for AZS33 
  GRANT CONNECT TO AZS33;
  GRANT REPORT TO AZS33;
  GRANT WORKSPACE TO AZS33;
  ALTER USER AZS33 DEFAULT ROLE CONNECT;


CREATE USER AZS35
  IDENTIFIED BY VALUES 'B33AE73EF5CE125D'
  DEFAULT TABLESPACE USERS
  TEMPORARY TABLESPACE TEMP
  PROFILE USERS
  ACCOUNT UNLOCK;
  -- 3 Roles for AZS35 
  GRANT CONNECT TO AZS35;
  GRANT REPORT TO AZS35;
  GRANT WORKSPACE TO AZS35;
  ALTER USER AZS35 DEFAULT ROLE CONNECT;


CREATE USER AZS36
  IDENTIFIED BY VALUES '4CD9FF194227BA66'
  DEFAULT TABLESPACE USERS
  TEMPORARY TABLESPACE TEMP
  PROFILE USERS
  ACCOUNT UNLOCK;
  -- 3 Roles for AZS36 
  GRANT CONNECT TO AZS36;
  GRANT REPORT TO AZS36;
  GRANT WORKSPACE TO AZS36;
  ALTER USER AZS36 DEFAULT ROLE CONNECT;


CREATE USER AZS37
  IDENTIFIED BY VALUES 'CFB4259DAF895671'
  DEFAULT TABLESPACE USERS
  TEMPORARY TABLESPACE TEMP
  PROFILE USERS
  ACCOUNT UNLOCK;
  -- 3 Roles for AZS37 
  GRANT CONNECT TO AZS37;
  GRANT REPORT TO AZS37;
  GRANT WORKSPACE TO AZS37;
  ALTER USER AZS37 DEFAULT ROLE CONNECT;


CREATE USER AZS38
  IDENTIFIED BY VALUES '3B04C6845F5635B4'
  DEFAULT TABLESPACE USERS
  TEMPORARY TABLESPACE TEMP
  PROFILE USERS
  ACCOUNT UNLOCK;
  -- 3 Roles for AZS38 
  GRANT CONNECT TO AZS38;
  GRANT REPORT TO AZS38;
  GRANT WORKSPACE TO AZS38;
  ALTER USER AZS38 DEFAULT ROLE CONNECT;


CREATE USER AZS39
  IDENTIFIED BY VALUES '53FB7F4AE2C54D0A'
  DEFAULT TABLESPACE USERS
  TEMPORARY TABLESPACE TEMP
  PROFILE USERS
  ACCOUNT UNLOCK;
  -- 3 Roles for AZS39 
  GRANT CONNECT TO AZS39;
  GRANT REPORT TO AZS39;
  GRANT WORKSPACE TO AZS39;
  ALTER USER AZS39 DEFAULT ROLE CONNECT;


CREATE USER AZS4
  IDENTIFIED BY VALUES 'F11C108D5A612D24'
  DEFAULT TABLESPACE USERS
  TEMPORARY TABLESPACE TEMP
  PROFILE USERS
  ACCOUNT UNLOCK;
  -- 3 Roles for AZS4 
  GRANT CONNECT TO AZS4;
  GRANT REPORT TO AZS4;
  GRANT WORKSPACE TO AZS4;
  ALTER USER AZS4 DEFAULT ROLE CONNECT;


CREATE USER AZS40
  IDENTIFIED BY VALUES '47D2C57EE206CE1E'
  DEFAULT TABLESPACE USERS
  TEMPORARY TABLESPACE TEMP
  PROFILE USERS
  ACCOUNT UNLOCK;
  -- 3 Roles for AZS40 
  GRANT CONNECT TO AZS40;
  GRANT REPORT TO AZS40;
  GRANT WORKSPACE TO AZS40;
  ALTER USER AZS40 DEFAULT ROLE CONNECT;


CREATE USER AZS41
  IDENTIFIED BY VALUES '5E911114633554D7'
  DEFAULT TABLESPACE USERS
  TEMPORARY TABLESPACE TEMP
  PROFILE USERS
  ACCOUNT UNLOCK;
  -- 3 Roles for AZS41 
  GRANT CONNECT TO AZS41;
  GRANT REPORT TO AZS41;
  GRANT WORKSPACE TO AZS41;
  ALTER USER AZS41 DEFAULT ROLE CONNECT;


CREATE USER AZS42
  IDENTIFIED BY VALUES 'AF3CA10EEE83DC85'
  DEFAULT TABLESPACE USERS
  TEMPORARY TABLESPACE TEMP
  PROFILE USERS
  ACCOUNT UNLOCK;
  -- 3 Roles for AZS42 
  GRANT CONNECT TO AZS42;
  GRANT REPORT TO AZS42;
  GRANT WORKSPACE TO AZS42;
  ALTER USER AZS42 DEFAULT ROLE CONNECT;


CREATE USER AZS43
  IDENTIFIED BY VALUES '4EE3621E76ECD339'
  DEFAULT TABLESPACE USERS
  TEMPORARY TABLESPACE TEMP
  PROFILE USERS
  ACCOUNT UNLOCK;
  -- 3 Roles for AZS43 
  GRANT CONNECT TO AZS43;
  GRANT REPORT TO AZS43;
  GRANT WORKSPACE TO AZS43;
  ALTER USER AZS43 DEFAULT ROLE CONNECT;


CREATE USER AZS45
  IDENTIFIED BY VALUES 'DD9302ECC12C25C7'
  DEFAULT TABLESPACE USERS
  TEMPORARY TABLESPACE TEMP
  PROFILE USERS
  ACCOUNT UNLOCK;
  -- 3 Roles for AZS45 
  GRANT CONNECT TO AZS45;
  GRANT REPORT TO AZS45;
  GRANT WORKSPACE TO AZS45;
  ALTER USER AZS45 DEFAULT ROLE CONNECT;


CREATE USER AZS46
  IDENTIFIED BY VALUES 'CDCFF5024C93C32A'
  DEFAULT TABLESPACE USERS
  TEMPORARY TABLESPACE TEMP
  PROFILE USERS
  ACCOUNT UNLOCK;
  -- 3 Roles for AZS46 
  GRANT CONNECT TO AZS46;
  GRANT REPORT TO AZS46;
  GRANT WORKSPACE TO AZS46;
  ALTER USER AZS46 DEFAULT ROLE CONNECT;


CREATE USER AZS47
  IDENTIFIED BY VALUES 'F774064CA0286A34'
  DEFAULT TABLESPACE USERS
  TEMPORARY TABLESPACE TEMP
  PROFILE USERS
  ACCOUNT UNLOCK;
  -- 3 Roles for AZS47 
  GRANT CONNECT TO AZS47;
  GRANT REPORT TO AZS47;
  GRANT WORKSPACE TO AZS47;
  ALTER USER AZS47 DEFAULT ROLE CONNECT;


CREATE USER AZS4AR
  IDENTIFIED BY VALUES '0810C0F973A4A533'
  DEFAULT TABLESPACE USERS
  TEMPORARY TABLESPACE TEMP
  PROFILE USERS
  ACCOUNT UNLOCK;
  -- 3 Roles for AZS4AR 
  GRANT CONNECT TO AZS4AR;
  GRANT REPORT TO AZS4AR;
  GRANT WORKSPACE TO AZS4AR;
  ALTER USER AZS4AR DEFAULT ROLE CONNECT;


CREATE USER AZS5
  IDENTIFIED BY VALUES '71E562E3FFA8C010'
  DEFAULT TABLESPACE USERS
  TEMPORARY TABLESPACE TEMP
  PROFILE USERS
  ACCOUNT UNLOCK;
  -- 3 Roles for AZS5 
  GRANT CONNECT TO AZS5;
  GRANT REPORT TO AZS5;
  GRANT WORKSPACE TO AZS5;
  ALTER USER AZS5 DEFAULT ROLE CONNECT;


CREATE USER AZS50
  IDENTIFIED BY VALUES 'F67C54BEC10DF6CE'
  DEFAULT TABLESPACE USERS
  TEMPORARY TABLESPACE TEMP
  PROFILE USERS
  ACCOUNT UNLOCK;
  -- 3 Roles for AZS50 
  GRANT CONNECT TO AZS50;
  GRANT REPORT TO AZS50;
  GRANT WORKSPACE TO AZS50;
  ALTER USER AZS50 DEFAULT ROLE CONNECT;


CREATE USER AZS52
  IDENTIFIED BY VALUES '68E8F55D1D5E62A4'
  DEFAULT TABLESPACE USERS
  TEMPORARY TABLESPACE TEMP
  PROFILE USERS
  ACCOUNT UNLOCK;
  -- 3 Roles for AZS52 
  GRANT CONNECT TO AZS52;
  GRANT REPORT TO AZS52;
  GRANT WORKSPACE TO AZS52;
  ALTER USER AZS52 DEFAULT ROLE CONNECT;


CREATE USER AZS53
  IDENTIFIED BY VALUES '5F6B5A475D44F8BC'
  DEFAULT TABLESPACE USERS
  TEMPORARY TABLESPACE TEMP
  PROFILE USERS
  ACCOUNT UNLOCK;
  -- 3 Roles for AZS53 
  GRANT CONNECT TO AZS53;
  GRANT REPORT TO AZS53;
  GRANT WORKSPACE TO AZS53;
  ALTER USER AZS53 DEFAULT ROLE CONNECT;


CREATE USER AZS54
  IDENTIFIED BY VALUES '3900E7AF42552E12'
  DEFAULT TABLESPACE USERS
  TEMPORARY TABLESPACE TEMP
  PROFILE USERS
  ACCOUNT UNLOCK;
  -- 3 Roles for AZS54 
  GRANT CONNECT TO AZS54;
  GRANT REPORT TO AZS54;
  GRANT WORKSPACE TO AZS54;
  ALTER USER AZS54 DEFAULT ROLE CONNECT;


CREATE USER AZS55
  IDENTIFIED BY VALUES 'FB901CDAFB8C1AA6'
  DEFAULT TABLESPACE USERS
  TEMPORARY TABLESPACE TEMP
  PROFILE USERS
  ACCOUNT UNLOCK;
  -- 3 Roles for AZS55 
  GRANT CONNECT TO AZS55;
  GRANT REPORT TO AZS55;
  GRANT WORKSPACE TO AZS55;
  ALTER USER AZS55 DEFAULT ROLE CONNECT;


CREATE USER AZS56
  IDENTIFIED BY VALUES '1629894B5EBA31C4'
  DEFAULT TABLESPACE USERS
  TEMPORARY TABLESPACE TEMP
  PROFILE USERS
  ACCOUNT UNLOCK;
  -- 3 Roles for AZS56 
  GRANT CONNECT TO AZS56;
  GRANT REPORT TO AZS56;
  GRANT WORKSPACE TO AZS56;
  ALTER USER AZS56 DEFAULT ROLE CONNECT;


CREATE USER AZS58
  IDENTIFIED BY VALUES '425786DA454D644F'
  DEFAULT TABLESPACE USERS
  TEMPORARY TABLESPACE TEMP
  PROFILE USERS
  ACCOUNT UNLOCK;
  -- 3 Roles for AZS58 
  GRANT CONNECT TO AZS58;
  GRANT REPORT TO AZS58;
  GRANT WORKSPACE TO AZS58;
  ALTER USER AZS58 DEFAULT ROLE CONNECT;


CREATE USER AZS59
  IDENTIFIED BY VALUES 'F8D39C79721535D9'
  DEFAULT TABLESPACE USERS
  TEMPORARY TABLESPACE TEMP
  PROFILE USERS
  ACCOUNT UNLOCK;
  -- 3 Roles for AZS59 
  GRANT CONNECT TO AZS59;
  GRANT REPORT TO AZS59;
  GRANT WORKSPACE TO AZS59;
  ALTER USER AZS59 DEFAULT ROLE CONNECT;


CREATE USER AZS6
  IDENTIFIED BY VALUES 'C39240C8333E2655'
  DEFAULT TABLESPACE USERS
  TEMPORARY TABLESPACE TEMP
  PROFILE USERS
  ACCOUNT UNLOCK;
  -- 3 Roles for AZS6 
  GRANT CONNECT TO AZS6;
  GRANT REPORT TO AZS6;
  GRANT WORKSPACE TO AZS6;
  ALTER USER AZS6 DEFAULT ROLE CONNECT;


CREATE USER AZS60
  IDENTIFIED BY VALUES '67634BC3C7F02A45'
  DEFAULT TABLESPACE USERS
  TEMPORARY TABLESPACE TEMP
  PROFILE USERS
  ACCOUNT UNLOCK;
  -- 3 Roles for AZS60 
  GRANT CONNECT TO AZS60;
  GRANT REPORT TO AZS60;
  GRANT WORKSPACE TO AZS60;
  ALTER USER AZS60 DEFAULT ROLE CONNECT;


CREATE USER AZS61
  IDENTIFIED BY VALUES '1D1FB0AD5C68E901'
  DEFAULT TABLESPACE USERS
  TEMPORARY TABLESPACE TEMP
  PROFILE USERS
  ACCOUNT UNLOCK;
  -- 3 Roles for AZS61 
  GRANT CONNECT TO AZS61;
  GRANT REPORT TO AZS61;
  GRANT WORKSPACE TO AZS61;
  ALTER USER AZS61 DEFAULT ROLE CONNECT;


CREATE USER AZS62
  IDENTIFIED BY VALUES 'E357D5BBCD61DFF4'
  DEFAULT TABLESPACE USERS
  TEMPORARY TABLESPACE TEMP
  PROFILE USERS
  ACCOUNT UNLOCK;
  -- 3 Roles for AZS62 
  GRANT CONNECT TO AZS62;
  GRANT REPORT TO AZS62;
  GRANT WORKSPACE TO AZS62;
  ALTER USER AZS62 DEFAULT ROLE CONNECT;


CREATE USER AZS63
  IDENTIFIED BY VALUES '9EB65AA921420BF6'
  DEFAULT TABLESPACE USERS
  TEMPORARY TABLESPACE TEMP
  PROFILE USERS
  ACCOUNT UNLOCK;
  -- 3 Roles for AZS63 
  GRANT CONNECT TO AZS63;
  GRANT REPORT TO AZS63;
  GRANT WORKSPACE TO AZS63;
  ALTER USER AZS63 DEFAULT ROLE CONNECT;


CREATE USER AZS64
  IDENTIFIED BY VALUES 'FD857C447E8D4E52'
  DEFAULT TABLESPACE USERS
  TEMPORARY TABLESPACE TEMP
  PROFILE USERS
  ACCOUNT UNLOCK;
  -- 3 Roles for AZS64 
  GRANT CONNECT TO AZS64;
  GRANT REPORT TO AZS64;
  GRANT WORKSPACE TO AZS64;
  ALTER USER AZS64 DEFAULT ROLE CONNECT;


CREATE USER AZS65
  IDENTIFIED BY VALUES '9FD4C009FF2899FD'
  DEFAULT TABLESPACE USERS
  TEMPORARY TABLESPACE TEMP
  PROFILE USERS
  ACCOUNT UNLOCK;
  -- 3 Roles for AZS65 
  GRANT CONNECT TO AZS65;
  GRANT REPORT TO AZS65;
  GRANT WORKSPACE TO AZS65;
  ALTER USER AZS65 DEFAULT ROLE CONNECT;


CREATE USER AZS66
  IDENTIFIED BY VALUES '4C4C8AB4404EB501'
  DEFAULT TABLESPACE USERS
  TEMPORARY TABLESPACE TEMP
  PROFILE USERS
  ACCOUNT UNLOCK;
  -- 3 Roles for AZS66 
  GRANT CONNECT TO AZS66;
  GRANT REPORT TO AZS66;
  GRANT WORKSPACE TO AZS66;
  ALTER USER AZS66 DEFAULT ROLE CONNECT;


CREATE USER AZS69
  IDENTIFIED BY VALUES '314DFB37A503E6B0'
  DEFAULT TABLESPACE USERS
  TEMPORARY TABLESPACE TEMP
  PROFILE USERS
  ACCOUNT UNLOCK;
  -- 3 Roles for AZS69 
  GRANT CONNECT TO AZS69;
  GRANT REPORT TO AZS69;
  GRANT WORKSPACE TO AZS69;
  ALTER USER AZS69 DEFAULT ROLE CONNECT;


CREATE USER AZS6AR
  IDENTIFIED BY VALUES '7956624CCCDF0850'
  DEFAULT TABLESPACE USERS
  TEMPORARY TABLESPACE TEMP
  PROFILE USERS
  ACCOUNT UNLOCK;
  -- 3 Roles for AZS6AR 
  GRANT CONNECT TO AZS6AR;
  GRANT REPORT TO AZS6AR;
  GRANT WORKSPACE TO AZS6AR;
  ALTER USER AZS6AR DEFAULT ROLE CONNECT;


CREATE USER AZS7
  IDENTIFIED BY VALUES '27CA89596CBB810F'
  DEFAULT TABLESPACE USERS
  TEMPORARY TABLESPACE TEMP
  PROFILE USERS
  ACCOUNT UNLOCK;
  -- 3 Roles for AZS7 
  GRANT CONNECT TO AZS7;
  GRANT REPORT TO AZS7;
  GRANT WORKSPACE TO AZS7;
  ALTER USER AZS7 DEFAULT ROLE CONNECT;


CREATE USER AZS70
  IDENTIFIED BY VALUES '836DFBE2D0AF3CE1'
  DEFAULT TABLESPACE USERS
  TEMPORARY TABLESPACE TEMP
  PROFILE USERS
  ACCOUNT UNLOCK;
  -- 3 Roles for AZS70 
  GRANT CONNECT TO AZS70;
  GRANT REPORT TO AZS70;
  GRANT WORKSPACE TO AZS70;
  ALTER USER AZS70 DEFAULT ROLE CONNECT;


CREATE USER AZS71
  IDENTIFIED BY VALUES 'A5816E3EDBAA8138'
  DEFAULT TABLESPACE USERS
  TEMPORARY TABLESPACE TEMP
  PROFILE USERS
  ACCOUNT UNLOCK;
  -- 3 Roles for AZS71 
  GRANT CONNECT TO AZS71;
  GRANT REPORT TO AZS71;
  GRANT WORKSPACE TO AZS71;
  ALTER USER AZS71 DEFAULT ROLE CONNECT;


CREATE USER AZS72
  IDENTIFIED BY VALUES '7194D0588BD371EF'
  DEFAULT TABLESPACE USERS
  TEMPORARY TABLESPACE TEMP
  PROFILE USERS
  ACCOUNT UNLOCK;
  -- 3 Roles for AZS72 
  GRANT CONNECT TO AZS72;
  GRANT REPORT TO AZS72;
  GRANT WORKSPACE TO AZS72;
  ALTER USER AZS72 DEFAULT ROLE CONNECT;


CREATE USER AZS73
  IDENTIFIED BY VALUES '47D3D04F32B839D4'
  DEFAULT TABLESPACE USERS
  TEMPORARY TABLESPACE TEMP
  PROFILE USERS
  ACCOUNT UNLOCK;
  -- 3 Roles for AZS73 
  GRANT CONNECT TO AZS73;
  GRANT REPORT TO AZS73;
  GRANT WORKSPACE TO AZS73;
  ALTER USER AZS73 DEFAULT ROLE CONNECT;


CREATE USER AZS74
  IDENTIFIED BY VALUES '1C046E633FE44744'
  DEFAULT TABLESPACE USERS
  TEMPORARY TABLESPACE TEMP
  PROFILE USERS
  ACCOUNT UNLOCK;
  -- 3 Roles for AZS74 
  GRANT CONNECT TO AZS74;
  GRANT REPORT TO AZS74;
  GRANT WORKSPACE TO AZS74;
  ALTER USER AZS74 DEFAULT ROLE CONNECT;


CREATE USER AZS75
  IDENTIFIED BY VALUES '02FC4D42F8D8D5F3'
  DEFAULT TABLESPACE USERS
  TEMPORARY TABLESPACE TEMP
  PROFILE USERS
  ACCOUNT UNLOCK;
  -- 3 Roles for AZS75 
  GRANT CONNECT TO AZS75;
  GRANT REPORT TO AZS75;
  GRANT WORKSPACE TO AZS75;
  ALTER USER AZS75 DEFAULT ROLE CONNECT;


CREATE USER AZS76
  IDENTIFIED BY VALUES 'C7D224BA325DC2AB'
  DEFAULT TABLESPACE USERS
  TEMPORARY TABLESPACE TEMP
  PROFILE USERS
  ACCOUNT UNLOCK;
  -- 3 Roles for AZS76 
  GRANT CONNECT TO AZS76;
  GRANT REPORT TO AZS76;
  GRANT WORKSPACE TO AZS76;
  ALTER USER AZS76 DEFAULT ROLE CONNECT;


CREATE USER AZS77
  IDENTIFIED BY VALUES '15074F16A4B80192'
  DEFAULT TABLESPACE USERS
  TEMPORARY TABLESPACE TEMP
  PROFILE USERS
  ACCOUNT UNLOCK;
  -- 3 Roles for AZS77 
  GRANT CONNECT TO AZS77;
  GRANT REPORT TO AZS77;
  GRANT WORKSPACE TO AZS77;
  ALTER USER AZS77 DEFAULT ROLE CONNECT;


CREATE USER AZS78
  IDENTIFIED BY VALUES 'CD9E553464B2035A'
  DEFAULT TABLESPACE USERS
  TEMPORARY TABLESPACE TEMP
  PROFILE USERS
  ACCOUNT UNLOCK;
  -- 3 Roles for AZS78 
  GRANT CONNECT TO AZS78;
  GRANT REPORT TO AZS78;
  GRANT WORKSPACE TO AZS78;
  ALTER USER AZS78 DEFAULT ROLE CONNECT;


CREATE USER AZS79
  IDENTIFIED BY VALUES '22157589769944C9'
  DEFAULT TABLESPACE USERS
  TEMPORARY TABLESPACE TEMP
  PROFILE USERS
  ACCOUNT UNLOCK;
  -- 3 Roles for AZS79 
  GRANT CONNECT TO AZS79;
  GRANT REPORT TO AZS79;
  GRANT WORKSPACE TO AZS79;
  ALTER USER AZS79 DEFAULT ROLE CONNECT;


CREATE USER AZS7AR
  IDENTIFIED BY VALUES 'BE4EB5D2BA1B3184'
  DEFAULT TABLESPACE USERS
  TEMPORARY TABLESPACE TEMP
  PROFILE USERS
  ACCOUNT UNLOCK;
  -- 3 Roles for AZS7AR 
  GRANT CONNECT TO AZS7AR;
  GRANT REPORT TO AZS7AR;
  GRANT WORKSPACE TO AZS7AR;
  ALTER USER AZS7AR DEFAULT ROLE CONNECT;


CREATE USER AZS8
  IDENTIFIED BY VALUES 'BF42CBE9A9CF049F'
  DEFAULT TABLESPACE USERS
  TEMPORARY TABLESPACE TEMP
  PROFILE USERS
  ACCOUNT UNLOCK;
  -- 3 Roles for AZS8 
  GRANT CONNECT TO AZS8;
  GRANT REPORT TO AZS8;
  GRANT WORKSPACE TO AZS8;
  ALTER USER AZS8 DEFAULT ROLE CONNECT;


CREATE USER AZS8AR
  IDENTIFIED BY VALUES '6E2434C0CB5F985C'
  DEFAULT TABLESPACE USERS
  TEMPORARY TABLESPACE TEMP
  PROFILE USERS
  ACCOUNT UNLOCK;
  -- 3 Roles for AZS8AR 
  GRANT CONNECT TO AZS8AR;
  GRANT REPORT TO AZS8AR;
  GRANT WORKSPACE TO AZS8AR;
  ALTER USER AZS8AR DEFAULT ROLE CONNECT;


CREATE USER AZS9
  IDENTIFIED BY VALUES '4964D5FB0EC958A5'
  DEFAULT TABLESPACE USERS
  TEMPORARY TABLESPACE TEMP
  PROFILE USERS
  ACCOUNT UNLOCK;
  -- 3 Roles for AZS9 
  GRANT CONNECT TO AZS9;
  GRANT REPORT TO AZS9;
  GRANT WORKSPACE TO AZS9;
  ALTER USER AZS9 DEFAULT ROLE CONNECT;


CREATE USER BASKOVA
  IDENTIFIED BY VALUES '34E4A9940B0C462C'
  DEFAULT TABLESPACE USERS
  TEMPORARY TABLESPACE TEMP
  PROFILE USERS
  ACCOUNT UNLOCK;
  -- 3 Roles for BASKOVA 
  GRANT CONNECT TO BASKOVA;
  GRANT REPORT TO BASKOVA;
  GRANT WORKSPACE TO BASKOVA;
  ALTER USER BASKOVA DEFAULT ROLE CONNECT;


CREATE USER BOSOVA
  IDENTIFIED BY VALUES '4E714441F7E32634'
  DEFAULT TABLESPACE USERS
  TEMPORARY TABLESPACE TEMP
  PROFILE USERS
  ACCOUNT UNLOCK;
  -- 3 Roles for BOSOVA 
  GRANT CONNECT TO BOSOVA;
  GRANT REPORT TO BOSOVA;
  GRANT WORKSPACE TO BOSOVA;
  ALTER USER BOSOVA DEFAULT ROLE CONNECT;


CREATE USER DEMIN
  IDENTIFIED BY VALUES '61A04C18EDB9C367'
  DEFAULT TABLESPACE USERS
  TEMPORARY TABLESPACE TEMP
  PROFILE FOX_PROFILE
  ACCOUNT UNLOCK;
  -- 4 Roles for DEMIN 
  GRANT CONNECT TO DEMIN;
  GRANT KERNEL_MANAGER TO DEMIN;
  GRANT REPORT TO DEMIN;
  GRANT WORKSPACE TO DEMIN;
  ALTER USER DEMIN DEFAULT ROLE CONNECT, KERNEL_MANAGER;


CREATE USER DUZJEVA
  IDENTIFIED BY VALUES 'CC92667CF36B9A2C'
  DEFAULT TABLESPACE USERS
  TEMPORARY TABLESPACE TEMP
  PROFILE USERS
  ACCOUNT UNLOCK;
  -- 3 Roles for DUZJEVA 
  GRANT CONNECT TO DUZJEVA;
  GRANT REPORT TO DUZJEVA;
  GRANT WORKSPACE TO DUZJEVA;
  ALTER USER DUZJEVA DEFAULT ROLE CONNECT;


CREATE USER EFIMOV
  IDENTIFIED BY VALUES '8B5E2AF548F1675E'
  DEFAULT TABLESPACE USERS
  TEMPORARY TABLESPACE TEMP
  PROFILE USERS
  ACCOUNT UNLOCK;
  -- 3 Roles for EFIMOV 
  GRANT CONNECT TO EFIMOV;
  GRANT REPORT TO EFIMOV;
  GRANT WORKSPACE TO EFIMOV;
  ALTER USER EFIMOV DEFAULT ROLE CONNECT;


CREATE USER EGOSHINA
  IDENTIFIED BY VALUES '14805FF179972857'
  DEFAULT TABLESPACE USERS
  TEMPORARY TABLESPACE TEMP
  PROFILE USERS
  ACCOUNT UNLOCK;
  -- 3 Roles for EGOSHINA 
  GRANT CONNECT TO EGOSHINA;
  GRANT REPORT TO EGOSHINA;
  GRANT WORKSPACE TO EGOSHINA;
  ALTER USER EGOSHINA DEFAULT ROLE CONNECT;


CREATE USER FEDOSEEVA
  IDENTIFIED BY VALUES '2425287DB8DA42FF'
  DEFAULT TABLESPACE USERS
  TEMPORARY TABLESPACE TEMP
  PROFILE USERS
  ACCOUNT UNLOCK;
  -- 3 Roles for FEDOSEEVA 
  GRANT CONNECT TO FEDOSEEVA;
  GRANT REPORT TO FEDOSEEVA;
  GRANT WORKSPACE TO FEDOSEEVA;
  ALTER USER FEDOSEEVA DEFAULT ROLE CONNECT;


CREATE USER FOX
  IDENTIFIED BY VALUES '3E9416B1A895B3A0'
  DEFAULT TABLESPACE USERS
  TEMPORARY TABLESPACE TEMP
  PROFILE FOX_PROFILE
  ACCOUNT UNLOCK;
  -- 5 Roles for FOX 
  GRANT CONNECT TO FOX;
  GRANT KERNEL_MANAGER TO FOX;
  GRANT QUEST_SL_USER TO FOX;
  GRANT REPORT TO FOX;
  GRANT WORKSPACE TO FOX;
  ALTER USER FOX DEFAULT ROLE CONNECT, KERNEL_MANAGER;


CREATE USER FOXPRO
  IDENTIFIED BY VALUES 'C80654BED696D5E6'
  DEFAULT TABLESPACE USERS
  TEMPORARY TABLESPACE TEMP
  PROFILE FOX_PROFILE
  ACCOUNT UNLOCK;
  -- 4 Roles for FOXPRO 
  GRANT DBA TO FOXPRO;
  GRANT KERNEL_MANAGER TO FOXPRO;
  GRANT QUEST_SL_USER TO FOXPRO;
  GRANT WORKSPACE TO FOXPRO;
  ALTER USER FOXPRO DEFAULT ROLE DBA, KERNEL_MANAGER, WORKSPACE;
  -- 111 System Privileges for FOXPRO 
  GRANT ALTER ANY CLUSTER TO FOXPRO;
  GRANT ALTER ANY DIMENSION TO FOXPRO;
  GRANT ALTER ANY INDEX TO FOXPRO;
  GRANT ALTER ANY INDEXTYPE TO FOXPRO;
  GRANT ALTER ANY LIBRARY TO FOXPRO;
  GRANT ALTER ANY OUTLINE TO FOXPRO;
  GRANT ALTER ANY PROCEDURE TO FOXPRO;
  GRANT ALTER ANY ROLE TO FOXPRO;
  GRANT ALTER ANY SEQUENCE TO FOXPRO;
  GRANT ALTER ANY SNAPSHOT TO FOXPRO;
  GRANT ALTER ANY TABLE TO FOXPRO;
  GRANT ALTER ANY TRIGGER TO FOXPRO;
  GRANT ALTER ANY TYPE TO FOXPRO;
  GRANT ALTER DATABASE TO FOXPRO;
  GRANT ALTER PROFILE TO FOXPRO;
  GRANT ALTER RESOURCE COST TO FOXPRO;
  GRANT ALTER ROLLBACK SEGMENT TO FOXPRO;
  GRANT ALTER SESSION TO FOXPRO;
  GRANT ALTER SYSTEM TO FOXPRO;
  GRANT ALTER TABLESPACE TO FOXPRO;
  GRANT ALTER USER TO FOXPRO;
  GRANT ANALYZE ANY TO FOXPRO;
  GRANT AUDIT ANY TO FOXPRO;
  GRANT AUDIT SYSTEM TO FOXPRO;
  GRANT BACKUP ANY TABLE TO FOXPRO;
  GRANT BECOME USER TO FOXPRO;
  GRANT COMMENT ANY TABLE TO FOXPRO;
  GRANT CREATE ANY CLUSTER TO FOXPRO;
  GRANT CREATE ANY CONTEXT TO FOXPRO;
  GRANT CREATE ANY DIMENSION TO FOXPRO;
  GRANT CREATE ANY DIRECTORY TO FOXPRO;
  GRANT CREATE ANY INDEX TO FOXPRO;
  GRANT CREATE ANY INDEXTYPE TO FOXPRO;
  GRANT CREATE ANY LIBRARY TO FOXPRO;
  GRANT CREATE ANY OPERATOR TO FOXPRO;
  GRANT CREATE ANY OUTLINE TO FOXPRO;
  GRANT CREATE ANY PROCEDURE TO FOXPRO;
  GRANT CREATE ANY SEQUENCE TO FOXPRO;
  GRANT CREATE ANY SNAPSHOT TO FOXPRO;
  GRANT CREATE ANY SYNONYM TO FOXPRO;
  GRANT CREATE ANY TABLE TO FOXPRO;
  GRANT CREATE ANY TRIGGER TO FOXPRO;
  GRANT CREATE ANY TYPE TO FOXPRO;
  GRANT CREATE ANY VIEW TO FOXPRO;
  GRANT CREATE CLUSTER TO FOXPRO;
  GRANT CREATE DATABASE LINK TO FOXPRO;
  GRANT CREATE DIMENSION TO FOXPRO;
  GRANT CREATE INDEXTYPE TO FOXPRO;
  GRANT CREATE LIBRARY TO FOXPRO;
  GRANT CREATE OPERATOR TO FOXPRO;
  GRANT CREATE PROCEDURE TO FOXPRO;
  GRANT CREATE PROFILE TO FOXPRO;
  GRANT CREATE PUBLIC DATABASE LINK TO FOXPRO;
  GRANT CREATE PUBLIC SYNONYM TO FOXPRO;
  GRANT CREATE ROLE TO FOXPRO;
  GRANT CREATE ROLLBACK SEGMENT TO FOXPRO;
  GRANT CREATE SEQUENCE TO FOXPRO;
  GRANT CREATE SESSION TO FOXPRO;
  GRANT CREATE SNAPSHOT TO FOXPRO;
  GRANT CREATE SYNONYM TO FOXPRO;
  GRANT CREATE TABLE TO FOXPRO;
  GRANT CREATE TABLESPACE TO FOXPRO;
  GRANT CREATE TRIGGER TO FOXPRO;
  GRANT CREATE TYPE TO FOXPRO;
  GRANT CREATE USER TO FOXPRO;
  GRANT CREATE VIEW TO FOXPRO;
  GRANT DELETE ANY TABLE TO FOXPRO;
  GRANT DROP ANY CLUSTER TO FOXPRO;
  GRANT DROP ANY CONTEXT TO FOXPRO;
  GRANT DROP ANY DIMENSION TO FOXPRO;
  GRANT DROP ANY DIRECTORY TO FOXPRO;
  GRANT DROP ANY INDEX TO FOXPRO;
  GRANT DROP ANY INDEXTYPE TO FOXPRO;
  GRANT DROP ANY LIBRARY TO FOXPRO;
  GRANT DROP ANY OPERATOR TO FOXPRO;
  GRANT DROP ANY OUTLINE TO FOXPRO;
  GRANT DROP ANY PROCEDURE TO FOXPRO;
  GRANT DROP ANY ROLE TO FOXPRO;
  GRANT DROP ANY SEQUENCE TO FOXPRO;
  GRANT DROP ANY SNAPSHOT TO FOXPRO;
  GRANT DROP ANY SYNONYM TO FOXPRO;
  GRANT DROP ANY TABLE TO FOXPRO;
  GRANT DROP ANY TRIGGER TO FOXPRO;
  GRANT DROP ANY TYPE TO FOXPRO;
  GRANT DROP ANY VIEW TO FOXPRO;
  GRANT DROP PROFILE TO FOXPRO;
  GRANT DROP PUBLIC DATABASE LINK TO FOXPRO;
  GRANT DROP PUBLIC SYNONYM TO FOXPRO;
  GRANT DROP ROLLBACK SEGMENT TO FOXPRO;
  GRANT DROP TABLESPACE TO FOXPRO;
  GRANT DROP USER TO FOXPRO;
  GRANT EXECUTE ANY INDEXTYPE TO FOXPRO;
  GRANT EXECUTE ANY LIBRARY TO FOXPRO;
  GRANT EXECUTE ANY OPERATOR TO FOXPRO;
  GRANT EXECUTE ANY PROCEDURE TO FOXPRO;
  GRANT EXECUTE ANY TYPE TO FOXPRO;
  GRANT EXTENDS ANY TYPE TO FOXPRO;
  GRANT FORCE ANY TRANSACTION TO FOXPRO;
  GRANT FORCE TRANSACTION TO FOXPRO;
  GRANT GLOBAL QUERY REWRITE TO FOXPRO;
  GRANT GRANT ANY PRIVILEGE TO FOXPRO;
  GRANT GRANT ANY ROLE TO FOXPRO;
  GRANT INSERT ANY TABLE TO FOXPRO;
  GRANT LOCK ANY TABLE TO FOXPRO;
  GRANT MANAGE TABLESPACE TO FOXPRO;
  GRANT QUERY REWRITE TO FOXPRO;
  GRANT RESTRICTED SESSION TO FOXPRO;
  GRANT SELECT ANY SEQUENCE TO FOXPRO;
  GRANT SELECT ANY TABLE TO FOXPRO;
  GRANT UNLIMITED TABLESPACE TO FOXPRO;
  GRANT UPDATE ANY TABLE TO FOXPRO;
  -- 1 Object Privilege for FOXPRO 
    GRANT SELECT ON LIDER.DOCUMENT TO FOXPRO;


CREATE USER FROLOVAV
  IDENTIFIED BY VALUES '54DD81F6C756BAB7'
  DEFAULT TABLESPACE USERS
  TEMPORARY TABLESPACE TEMP
  PROFILE FOX_PROFILE
  ACCOUNT UNLOCK;
  -- 4 Roles for FROLOVAV 
  GRANT CONNECT TO FROLOVAV;
  GRANT KERNEL_MANAGER TO FROLOVAV;
  GRANT REPORT TO FROLOVAV;
  GRANT WORKSPACE TO FROLOVAV;
  ALTER USER FROLOVAV DEFAULT ROLE CONNECT, KERNEL_MANAGER;


CREATE USER GENG
  IDENTIFIED BY VALUES '6F0BDCDB1165CDD7'
  DEFAULT TABLESPACE USERS
  TEMPORARY TABLESPACE TEMP
  PROFILE USERS
  ACCOUNT UNLOCK;
  -- 3 Roles for GENG 
  GRANT CONNECT TO GENG;
  GRANT REPORT TO GENG;
  GRANT WORKSPACE TO GENG;
  ALTER USER GENG DEFAULT ROLE CONNECT;


CREATE USER GGIZATULLINA
  IDENTIFIED BY VALUES 'EA2D5C4EFA026D95'
  DEFAULT TABLESPACE USERS
  TEMPORARY TABLESPACE TEMP
  PROFILE USERS
  ACCOUNT UNLOCK;
  -- 3 Roles for GGIZATULLINA 
  GRANT CONNECT TO GGIZATULLINA;
  GRANT REPORT TO GGIZATULLINA;
  GRANT WORKSPACE TO GGIZATULLINA;
  ALTER USER GGIZATULLINA DEFAULT ROLE CONNECT;


CREATE USER GORBUNOVA
  IDENTIFIED BY VALUES '95E1108B97D17B70'
  DEFAULT TABLESPACE USERS
  TEMPORARY TABLESPACE TEMP
  PROFILE USERS
  ACCOUNT UNLOCK;
  -- 3 Roles for GORBUNOVA 
  GRANT CONNECT TO GORBUNOVA;
  GRANT REPORT TO GORBUNOVA;
  GRANT WORKSPACE TO GORBUNOVA;
  ALTER USER GORBUNOVA DEFAULT ROLE CONNECT;


CREATE USER GORINOVA
  IDENTIFIED BY VALUES 'AA76828531801DBB'
  DEFAULT TABLESPACE USERS
  TEMPORARY TABLESPACE TEMP
  PROFILE USERS
  ACCOUNT UNLOCK;
  -- 3 Roles for GORINOVA 
  GRANT CONNECT TO GORINOVA;
  GRANT REPORT TO GORINOVA;
  GRANT WORKSPACE TO GORINOVA;
  ALTER USER GORINOVA DEFAULT ROLE CONNECT;


CREATE USER GROMOVA
  IDENTIFIED BY VALUES '78FCB3A677733C75'
  DEFAULT TABLESPACE USERS
  TEMPORARY TABLESPACE TEMP
  PROFILE USERS
  ACCOUNT UNLOCK;
  -- 3 Roles for GROMOVA 
  GRANT CONNECT TO GROMOVA;
  GRANT REPORT TO GROMOVA;
  GRANT WORKSPACE TO GROMOVA;
  ALTER USER GROMOVA DEFAULT ROLE CONNECT;


CREATE USER HEGLEEVA
  IDENTIFIED BY VALUES 'EA868BAAB5C8154C'
  DEFAULT TABLESPACE USERS
  TEMPORARY TABLESPACE TEMP
  PROFILE USERS
  ACCOUNT UNLOCK;
  -- 3 Roles for HEGLEEVA 
  GRANT CONNECT TO HEGLEEVA;
  GRANT REPORT TO HEGLEEVA;
  GRANT WORKSPACE TO HEGLEEVA;
  ALTER USER HEGLEEVA DEFAULT ROLE CONNECT;


CREATE USER IBASKOVA
  IDENTIFIED BY VALUES 'DA9FC20758E0D190'
  DEFAULT TABLESPACE USERS
  TEMPORARY TABLESPACE TEMP
  PROFILE USERS
  ACCOUNT UNLOCK;
  -- 3 Roles for IBASKOVA 
  GRANT CONNECT TO IBASKOVA;
  GRANT REPORT TO IBASKOVA;
  GRANT WORKSPACE TO IBASKOVA;
  ALTER USER IBASKOVA DEFAULT ROLE CONNECT;


CREATE USER IGNATOV
  IDENTIFIED BY VALUES 'DF3F79C164307755'
  DEFAULT TABLESPACE USERS
  TEMPORARY TABLESPACE TEMP
  PROFILE USERS
  ACCOUNT UNLOCK;
  -- 3 Roles for IGNATOV 
  GRANT CONNECT TO IGNATOV;
  GRANT REPORT TO IGNATOV;
  GRANT WORKSPACE TO IGNATOV;
  ALTER USER IGNATOV DEFAULT ROLE CONNECT;


CREATE USER IGNATOVA
  IDENTIFIED BY VALUES '4742F056E9DE6C2C'
  DEFAULT TABLESPACE USERS
  TEMPORARY TABLESPACE TEMP
  PROFILE USERS
  ACCOUNT UNLOCK;
  -- 3 Roles for IGNATOVA 
  GRANT CONNECT TO IGNATOVA;
  GRANT REPORT TO IGNATOVA;
  GRANT WORKSPACE TO IGNATOVA;
  ALTER USER IGNATOVA DEFAULT ROLE CONNECT;


CREATE USER INST
  IDENTIFIED BY VALUES 'CE875C49433471DC'
  DEFAULT TABLESPACE USERS
  TEMPORARY TABLESPACE TEMP
  PROFILE USERS
  ACCOUNT UNLOCK;
  -- 2 Roles for INST 
  GRANT CONNECT TO INST;
  GRANT RESOURCE TO INST;
  ALTER USER INST DEFAULT ROLE ALL;
  -- 6 System Privileges for INST 
  GRANT ALTER SYSTEM TO INST;
  GRANT CREATE PROCEDURE TO INST;
  GRANT CREATE TABLE TO INST;
  GRANT CREATE VIEW TO INST;
  GRANT SELECT ANY TABLE TO INST;
  GRANT UNLIMITED TABLESPACE TO INST;
  -- 1 Tablespace Quota for INST 
  ALTER USER INST QUOTA UNLIMITED ON USERS;
  -- 212 Object Privileges for INST 
    GRANT SELECT ON SYS.DBA_EXTENTS TO INST;
    GRANT SELECT ON SYS.DBA_FREE_SPACE TO INST;
    GRANT SELECT ON SYS.DBA_INDEXES TO INST;
    GRANT SELECT ON SYS.DBA_IND_COLUMNS TO INST;
    GRANT SELECT ON SYS.DBA_JOBS TO INST;
    GRANT SELECT ON SYS.DBA_TAB_COLUMNS TO INST;
    GRANT EXECUTE ON SYS.DBMS_SYSTEM TO INST;
    GRANT SELECT ON SYS.FET$ TO INST;
    GRANT SELECT ON SYS.FILE$ TO INST;
    GRANT SELECT ON SYS.OBJ$ TO INST;
    GRANT SELECT ON SYS.SEG$ TO INST;
    GRANT SELECT ON SYS.TS$ TO INST;
    GRANT SELECT ON SYS.USER$ TO INST;
    GRANT SELECT ON SYS.V_$ACCESS TO INST;
    GRANT SELECT ON SYS.V_$ACTIVE_INSTANCES TO INST;
    GRANT SELECT ON SYS.V_$AQ1 TO INST;
    GRANT SELECT ON SYS.V_$ARCHIVE TO INST;
    GRANT SELECT ON SYS.V_$ARCHIVED_LOG TO INST;
    GRANT SELECT ON SYS.V_$ARCHIVE_DEST TO INST;
    GRANT SELECT ON SYS.V_$ARCHIVE_PROCESSES TO INST;
    GRANT SELECT ON SYS.V_$BACKUP TO INST;
    GRANT SELECT ON SYS.V_$BACKUP_ASYNC_IO TO INST;
    GRANT SELECT ON SYS.V_$BACKUP_CORRUPTION TO INST;
    GRANT SELECT ON SYS.V_$BACKUP_DATAFILE TO INST;
    GRANT SELECT ON SYS.V_$BACKUP_DEVICE TO INST;
    GRANT SELECT ON SYS.V_$BACKUP_PIECE TO INST;
    GRANT SELECT ON SYS.V_$BACKUP_REDOLOG TO INST;
    GRANT SELECT ON SYS.V_$BACKUP_SET TO INST;
    GRANT SELECT ON SYS.V_$BACKUP_SYNC_IO TO INST;
    GRANT SELECT ON SYS.V_$BGPROCESS TO INST;
    GRANT SELECT ON SYS.V_$BH TO INST;
    GRANT SELECT ON SYS.V_$BSP TO INST;
    GRANT SELECT ON SYS.V_$BUFFER_POOL TO INST;
    GRANT SELECT ON SYS.V_$BUFFER_POOL_STATISTICS TO INST;
    GRANT SELECT ON SYS.V_$CIRCUIT TO INST;
    GRANT SELECT ON SYS.V_$CLASS_PING TO INST;
    GRANT SELECT ON SYS.V_$COMPATIBILITY TO INST;
    GRANT SELECT ON SYS.V_$COMPATSEG TO INST;
    GRANT SELECT ON SYS.V_$CONTEXT TO INST;
    GRANT SELECT ON SYS.V_$CONTROLFILE TO INST;
    GRANT SELECT ON SYS.V_$CONTROLFILE_RECORD_SECTION TO INST;
    GRANT SELECT ON SYS.V_$COPY_CORRUPTION TO INST;
    GRANT SELECT ON SYS.V_$DATABASE TO INST;
    GRANT SELECT ON SYS.V_$DATAFILE TO INST;
    GRANT SELECT ON SYS.V_$DATAFILE_COPY TO INST;
    GRANT SELECT ON SYS.V_$DATAFILE_HEADER TO INST;
    GRANT SELECT ON SYS.V_$DBFILE TO INST;
    GRANT SELECT ON SYS.V_$DBLINK TO INST;
    GRANT SELECT ON SYS.V_$DB_CACHE_ADVICE TO INST;
    GRANT SELECT ON SYS.V_$DB_OBJECT_CACHE TO INST;
    GRANT SELECT ON SYS.V_$DB_PIPES TO INST;
    GRANT SELECT ON SYS.V_$DELETED_OBJECT TO INST;
    GRANT SELECT ON SYS.V_$DISPATCHER TO INST;
    GRANT SELECT ON SYS.V_$DISPATCHER_RATE TO INST;
    GRANT SELECT ON SYS.V_$DLM_ALL_LOCKS TO INST;
    GRANT SELECT ON SYS.V_$DLM_CONVERT_LOCAL TO INST;
    GRANT SELECT ON SYS.V_$DLM_CONVERT_REMOTE TO INST;
    GRANT SELECT ON SYS.V_$DLM_LATCH TO INST;
    GRANT SELECT ON SYS.V_$DLM_LOCKS TO INST;
    GRANT SELECT ON SYS.V_$DLM_MISC TO INST;
    GRANT SELECT ON SYS.V_$DLM_RESS TO INST;
    GRANT SELECT ON SYS.V_$DLM_TRAFFIC_CONTROLLER TO INST;
    GRANT SELECT ON SYS.V_$ENABLEDPRIVS TO INST;
    GRANT SELECT ON SYS.V_$ENQUEUE_LOCK TO INST;
    GRANT SELECT ON SYS.V_$EVENT_NAME TO INST;
    GRANT SELECT ON SYS.V_$EXECUTION TO INST;
    GRANT SELECT ON SYS.V_$FAST_START_SERVERS TO INST;
    GRANT SELECT ON SYS.V_$FAST_START_TRANSACTIONS TO INST;
    GRANT SELECT ON SYS.V_$FILESTAT TO INST;
    GRANT SELECT ON SYS.V_$FILE_PING TO INST;
    GRANT SELECT ON SYS.V_$FIXED_TABLE TO INST;
    GRANT SELECT ON SYS.V_$FIXED_VIEW_DEFINITION TO INST;
    GRANT SELECT ON SYS.V_$GLOBAL_BLOCKED_LOCKS TO INST;
    GRANT SELECT ON SYS.V_$GLOBAL_TRANSACTION TO INST;
    GRANT SELECT ON SYS.V_$HS_AGENT TO INST;
    GRANT SELECT ON SYS.V_$HS_PARAMETER TO INST;
    GRANT SELECT ON SYS.V_$HS_SESSION TO INST;
    GRANT SELECT ON SYS.V_$INDEXED_FIXED_COLUMN TO INST;
    GRANT SELECT ON SYS.V_$INSTANCE TO INST;
    GRANT SELECT ON SYS.V_$INSTANCE_RECOVERY TO INST;
    GRANT SELECT ON SYS.V_$LATCH TO INST;
    GRANT SELECT ON SYS.V_$LATCHHOLDER TO INST;
    GRANT SELECT ON SYS.V_$LATCHNAME TO INST;
    GRANT SELECT ON SYS.V_$LATCH_CHILDREN TO INST;
    GRANT SELECT ON SYS.V_$LATCH_MISSES TO INST;
    GRANT SELECT ON SYS.V_$LATCH_PARENT TO INST;
    GRANT SELECT ON SYS.V_$LIBRARYCACHE TO INST;
    GRANT SELECT ON SYS.V_$LICENSE TO INST;
    GRANT SELECT ON SYS.V_$LOADCSTAT TO INST;
    GRANT SELECT ON SYS.V_$LOADISTAT TO INST;
    GRANT SELECT ON SYS.V_$LOADPSTAT TO INST;
    GRANT SELECT ON SYS.V_$LOADTSTAT TO INST;
    GRANT SELECT ON SYS.V_$LOCK TO INST;
    GRANT SELECT ON SYS.V_$LOCKED_OBJECT TO INST;
    GRANT SELECT ON SYS.V_$LOCKS_WITH_COLLISIONS TO INST;
    GRANT SELECT ON SYS.V_$LOCK_ACTIVITY TO INST;
    GRANT SELECT ON SYS.V_$LOCK_ELEMENT TO INST;
    GRANT SELECT ON SYS.V_$LOG TO INST;
    GRANT SELECT ON SYS.V_$LOGFILE TO INST;
    GRANT SELECT ON SYS.V_$LOGHIST TO INST;
    GRANT SELECT ON SYS.V_$LOGMNR_CONTENTS TO INST;
    GRANT SELECT ON SYS.V_$LOGMNR_DICTIONARY TO INST;
    GRANT SELECT ON SYS.V_$LOGMNR_LOGS TO INST;
    GRANT SELECT ON SYS.V_$LOGMNR_PARAMETERS TO INST;
    GRANT SELECT ON SYS.V_$LOG_HISTORY TO INST;
    GRANT SELECT ON SYS.V_$MAX_ACTIVE_SESS_TARGET_MTH TO INST;
    GRANT SELECT ON SYS.V_$MTS TO INST;
    GRANT SELECT ON SYS.V_$MYSTAT TO INST;
    GRANT SELECT ON SYS.V_$NLS_PARAMETERS TO INST;
    GRANT SELECT ON SYS.V_$NLS_VALID_VALUES TO INST;
    GRANT SELECT ON SYS.V_$OBJECT_DEPENDENCY TO INST;
    GRANT SELECT ON SYS.V_$OBSOLETE_PARAMETER TO INST;
    GRANT SELECT ON SYS.V_$OFFLINE_RANGE TO INST;
    GRANT SELECT ON SYS.V_$OPEN_CURSOR TO INST;
    GRANT SELECT ON SYS.V_$OPTION TO INST;
    GRANT SELECT ON SYS.V_$PARALLEL_DEGREE_LIMIT_MTH TO INST;
    GRANT SELECT ON SYS.V_$PARAMETER TO INST;
    GRANT SELECT ON SYS.V_$PARAMETER2 TO INST;
    GRANT SELECT ON SYS.V_$PQ_SESSTAT TO INST;
    GRANT SELECT ON SYS.V_$PQ_SLAVE TO INST;
    GRANT SELECT ON SYS.V_$PQ_SYSSTAT TO INST;
    GRANT SELECT ON SYS.V_$PQ_TQSTAT TO INST;
    GRANT SELECT ON SYS.V_$PROCESS TO INST;
    GRANT SELECT ON SYS.V_$PROXY_ARCHIVEDLOG TO INST;
    GRANT SELECT ON SYS.V_$PROXY_DATAFILE TO INST;
    GRANT SELECT ON SYS.V_$PWFILE_USERS TO INST;
    GRANT SELECT ON SYS.V_$PX_PROCESS TO INST;
    GRANT SELECT ON SYS.V_$PX_PROCESS_SYSSTAT TO INST;
    GRANT SELECT ON SYS.V_$PX_SESSION TO INST;
    GRANT SELECT ON SYS.V_$PX_SESSTAT TO INST;
    GRANT SELECT ON SYS.V_$QUEUE TO INST;
    GRANT SELECT ON SYS.V_$RECOVERY_FILE_STATUS TO INST;
    GRANT SELECT ON SYS.V_$RECOVERY_LOG TO INST;
    GRANT SELECT ON SYS.V_$RECOVERY_PROGRESS TO INST;
    GRANT SELECT ON SYS.V_$RECOVERY_STATUS TO INST;
    GRANT SELECT ON SYS.V_$RECOVER_FILE TO INST;
    GRANT SELECT ON SYS.V_$REQDIST TO INST;
    GRANT SELECT ON SYS.V_$RESERVED_WORDS TO INST;
    GRANT SELECT ON SYS.V_$RESOURCE TO INST;
    GRANT SELECT ON SYS.V_$RESOURCE_LIMIT TO INST;
    GRANT SELECT ON SYS.V_$ROLLSTAT TO INST;
    GRANT SELECT ON SYS.V_$ROWCACHE TO INST;
    GRANT SELECT ON SYS.V_$ROWCACHE_PARENT TO INST;
    GRANT SELECT ON SYS.V_$ROWCACHE_SUBORDINATE TO INST;
    GRANT SELECT ON SYS.V_$RSRC_CONSUMER_GROUP TO INST;
    GRANT SELECT ON SYS.V_$RSRC_CONSUMER_GROUP_CPU_MTH TO INST;
    GRANT SELECT ON SYS.V_$RSRC_PLAN TO INST;
    GRANT SELECT ON SYS.V_$RSRC_PLAN_CPU_MTH TO INST;
    GRANT SELECT ON SYS.V_$SESSION TO INST;
    GRANT SELECT ON SYS.V_$SESSION_CONNECT_INFO TO INST;
    GRANT SELECT ON SYS.V_$SESSION_CURSOR_CACHE TO INST;
    GRANT SELECT ON SYS.V_$SESSION_EVENT TO INST;
    GRANT SELECT ON SYS.V_$SESSION_LONGOPS TO INST;
    GRANT SELECT ON SYS.V_$SESSION_OBJECT_CACHE TO INST;
    GRANT SELECT ON SYS.V_$SESSION_WAIT TO INST;
    GRANT SELECT ON SYS.V_$SESSTAT TO INST;
    GRANT SELECT ON SYS.V_$SESS_IO TO INST;
    GRANT SELECT ON SYS.V_$SGA TO INST;
    GRANT SELECT ON SYS.V_$SGASTAT TO INST;
    GRANT SELECT ON SYS.V_$SHARED_POOL_RESERVED TO INST;
    GRANT SELECT ON SYS.V_$SHARED_SERVER TO INST;
    GRANT SELECT ON SYS.V_$SORT_SEGMENT TO INST;
    GRANT SELECT ON SYS.V_$SORT_USAGE TO INST;
    GRANT SELECT ON SYS.V_$SQL TO INST;
    GRANT SELECT ON SYS.V_$SQLAREA TO INST;
    GRANT SELECT ON SYS.V_$SQLTEXT TO INST;
    GRANT SELECT ON SYS.V_$SQLTEXT_WITH_NEWLINES TO INST;
    GRANT SELECT ON SYS.V_$SQL_BIND_DATA TO INST;
    GRANT SELECT ON SYS.V_$SQL_BIND_METADATA TO INST;
    GRANT SELECT ON SYS.V_$SQL_CURSOR TO INST;
    GRANT SELECT ON SYS.V_$SQL_SHARED_CURSOR TO INST;
    GRANT SELECT ON SYS.V_$SQL_SHARED_MEMORY TO INST;
    GRANT SELECT ON SYS.V_$STATNAME TO INST;
    GRANT SELECT ON SYS.V_$SUBCACHE TO INST;
    GRANT SELECT ON SYS.V_$SYSSTAT TO INST;
    GRANT SELECT ON SYS.V_$SYSTEM_CURSOR_CACHE TO INST;
    GRANT SELECT ON SYS.V_$SYSTEM_EVENT TO INST;
    GRANT SELECT ON SYS.V_$SYSTEM_PARAMETER TO INST;
    GRANT SELECT ON SYS.V_$SYSTEM_PARAMETER2 TO INST;
    GRANT SELECT ON SYS.V_$TABLESPACE TO INST;
    GRANT SELECT ON SYS.V_$TARGETRBA TO INST;
    GRANT SELECT ON SYS.V_$TEMPFILE TO INST;
    GRANT SELECT ON SYS.V_$TEMPORARY_LOBS TO INST;
    GRANT SELECT ON SYS.V_$TEMPSTAT TO INST;
    GRANT SELECT ON SYS.V_$TEMP_EXTENT_MAP TO INST;
    GRANT SELECT ON SYS.V_$TEMP_EXTENT_POOL TO INST;
    GRANT SELECT ON SYS.V_$TEMP_PING TO INST;
    GRANT SELECT ON SYS.V_$TEMP_SPACE_HEADER TO INST;
    GRANT SELECT ON SYS.V_$THREAD TO INST;
    GRANT SELECT ON SYS.V_$TIMER TO INST;
    GRANT SELECT ON SYS.V_$TRANSACTION TO INST;
    GRANT SELECT ON SYS.V_$TRANSACTION_ENQUEUE TO INST;
    GRANT SELECT ON SYS.V_$TYPE_SIZE TO INST;
    GRANT SELECT ON SYS.V_$VERSION TO INST;
    GRANT SELECT ON SYS.V_$WAITSTAT TO INST;
    GRANT SELECT ON SYS.V_$_LOCK TO INST;
    GRANT SELECT ON SYS.V_$_LOCK1 TO INST;
    GRANT SELECT ON SYS.V_$_SEQUENCES TO INST;
    GRANT SELECT ON SYS.X_$KCBFWAIT TO INST;
    GRANT SELECT ON SYS.X_$KCBWBPD TO INST;
    GRANT SELECT ON SYS.X_$KCBWDS TO INST;
    GRANT SELECT ON SYS.X_$KSLED TO INST;
    GRANT SELECT ON SYS.X_$KSLEI TO INST;
    GRANT SELECT ON SYS.X_$KSLES TO INST;
    GRANT SELECT ON SYS.X_$KSLLD TO INST;
    GRANT SELECT ON SYS.X_$KSLLT TO INST;
    GRANT SELECT ON SYS.X_$KSMLRU TO INST;
    GRANT SELECT ON SYS.X_$KSMSP TO INST;
    GRANT SELECT ON SYS.X_$KSPPCV TO INST;
    GRANT SELECT ON SYS.X_$KSPPI TO INST;
    GRANT SELECT ON SYS.X_$KSQRS TO INST;
    GRANT SELECT ON SYS.X_$KSUSESTA TO INST;


CREATE USER IYUDIN
  IDENTIFIED BY VALUES '3B19E01618F16689'
  DEFAULT TABLESPACE USERS
  TEMPORARY TABLESPACE TEMP
  PROFILE USERS
  ACCOUNT LOCK;
  -- 3 Roles for IYUDIN 
  GRANT CONNECT TO IYUDIN;
  GRANT REPORT TO IYUDIN;
  GRANT WORKSPACE TO IYUDIN;
  ALTER USER IYUDIN DEFAULT ROLE CONNECT;


CREATE USER JEVNERENKO
  IDENTIFIED BY VALUES '58F75F0EFFF22F15'
  DEFAULT TABLESPACE USERS
  TEMPORARY TABLESPACE TEMP
  PROFILE USERS
  ACCOUNT UNLOCK;
  -- 3 Roles for JEVNERENKO 
  GRANT CONNECT TO JEVNERENKO;
  GRANT REPORT TO JEVNERENKO;
  GRANT WORKSPACE TO JEVNERENKO;
  ALTER USER JEVNERENKO DEFAULT ROLE CONNECT;


CREATE USER KEM
  IDENTIFIED BY VALUES '21DAD20B949373FE'
  DEFAULT TABLESPACE USERS
  TEMPORARY TABLESPACE TEMP
  PROFILE USERS
  ACCOUNT UNLOCK;
  -- 3 Roles for KEM 
  GRANT CONNECT TO KEM;
  GRANT REPORT TO KEM;
  GRANT WORKSPACE TO KEM;
  ALTER USER KEM DEFAULT ROLE CONNECT;


CREATE USER KERNEL
  IDENTIFIED BY VALUES '24EC02A4FF013355'
  DEFAULT TABLESPACE USERS
  TEMPORARY TABLESPACE TEMP
  PROFILE ADMIN
  ACCOUNT UNLOCK;
  -- 3 Roles for KERNEL 
  GRANT CONNECT TO KERNEL;
  GRANT REPORT TO KERNEL;
  GRANT WORKSPACE TO KERNEL;
  ALTER USER KERNEL DEFAULT ROLE CONNECT;


CREATE USER KRUG
  IDENTIFIED BY VALUES 'D0C22D5255067F97'
  DEFAULT TABLESPACE USERS
  TEMPORARY TABLESPACE TEMP
  PROFILE USERS
  ACCOUNT UNLOCK;
  -- 3 Roles for KRUG 
  GRANT CONNECT TO KRUG;
  GRANT REPORT TO KRUG;
  GRANT WORKSPACE TO KRUG;
  ALTER USER KRUG DEFAULT ROLE CONNECT;


CREATE USER LAPSHINA
  IDENTIFIED BY VALUES '46625EEC0E20E276'
  DEFAULT TABLESPACE USERS
  TEMPORARY TABLESPACE TEMP
  PROFILE USERS
  ACCOUNT UNLOCK;
  -- 3 Roles for LAPSHINA 
  GRANT CONNECT TO LAPSHINA;
  GRANT REPORT TO LAPSHINA;
  GRANT WORKSPACE TO LAPSHINA;
  ALTER USER LAPSHINA DEFAULT ROLE CONNECT;


CREATE USER LAVROVA
  IDENTIFIED BY VALUES '18091B0D79CA9419'
  DEFAULT TABLESPACE USERS
  TEMPORARY TABLESPACE TEMP
  PROFILE USERS
  ACCOUNT UNLOCK;
  -- 3 Roles for LAVROVA 
  GRANT CONNECT TO LAVROVA;
  GRANT REPORT TO LAVROVA;
  GRANT WORKSPACE TO LAVROVA;
  ALTER USER LAVROVA DEFAULT ROLE CONNECT;


CREATE USER LHANMURZINA
  IDENTIFIED BY VALUES 'AD5B777EFA676CA8'
  DEFAULT TABLESPACE USERS
  TEMPORARY TABLESPACE TEMP
  PROFILE USERS
  ACCOUNT UNLOCK;
  -- 3 Roles for LHANMURZINA 
  GRANT CONNECT TO LHANMURZINA;
  GRANT REPORT TO LHANMURZINA;
  GRANT WORKSPACE TO LHANMURZINA;
  ALTER USER LHANMURZINA DEFAULT ROLE CONNECT;


CREATE USER LIDER
  IDENTIFIED BY VALUES '39DF74B6BB092A5D'
  DEFAULT TABLESPACE USERS
  TEMPORARY TABLESPACE TEMP
  PROFILE ADMIN
  ACCOUNT UNLOCK;
  -- 17 Roles for LIDER 
  GRANT AQ_ADMINISTRATOR_ROLE TO LIDER;
  GRANT AQ_USER_ROLE TO LIDER;
  GRANT CONNECT TO LIDER;
  GRANT DBA TO LIDER;
  GRANT DELETE_CATALOG_ROLE TO LIDER;
  GRANT EXECUTE_CATALOG_ROLE TO LIDER;
  GRANT EXP_FULL_DATABASE TO LIDER;
  GRANT HS_ADMIN_ROLE TO LIDER;
  GRANT IMP_FULL_DATABASE TO LIDER;
  GRANT KERNEL_MANAGER TO LIDER WITH ADMIN OPTION;
  GRANT QUEST_SL_USER TO LIDER WITH ADMIN OPTION;
  GRANT RECOVERY_CATALOG_OWNER TO LIDER;
  GRANT REPORT TO LIDER WITH ADMIN OPTION;
  GRANT RESOURCE TO LIDER;
  GRANT SELECT_CATALOG_ROLE TO LIDER;
  GRANT V_RESOURCE TO LIDER WITH ADMIN OPTION;
  GRANT WORKSPACE TO LIDER WITH ADMIN OPTION;
  ALTER USER LIDER DEFAULT ROLE ALL;
  -- 111 System Privileges for LIDER 
  GRANT ADMINISTER DATABASE TRIGGER TO LIDER;
  GRANT ALTER ANY CLUSTER TO LIDER;
  GRANT ALTER ANY DIMENSION TO LIDER;
  GRANT ALTER ANY INDEX TO LIDER;
  GRANT ALTER ANY INDEXTYPE TO LIDER;
  GRANT ALTER ANY LIBRARY TO LIDER;
  GRANT ALTER ANY OUTLINE TO LIDER;
  GRANT ALTER ANY PROCEDURE TO LIDER;
  GRANT ALTER ANY ROLE TO LIDER;
  GRANT ALTER ANY SEQUENCE TO LIDER;
  GRANT ALTER ANY SNAPSHOT TO LIDER;
  GRANT ALTER ANY TABLE TO LIDER;
  GRANT ALTER ANY TRIGGER TO LIDER;
  GRANT ALTER ANY TYPE TO LIDER;
  GRANT ALTER DATABASE TO LIDER;
  GRANT ALTER PROFILE TO LIDER;
  GRANT ALTER RESOURCE COST TO LIDER;
  GRANT ALTER ROLLBACK SEGMENT TO LIDER;
  GRANT ALTER SESSION TO LIDER;
  GRANT ALTER SYSTEM TO LIDER;
  GRANT ALTER TABLESPACE TO LIDER;
  GRANT ALTER USER TO LIDER;
  GRANT ANALYZE ANY TO LIDER;
  GRANT AUDIT ANY TO LIDER;
  GRANT AUDIT SYSTEM TO LIDER;
  GRANT BACKUP ANY TABLE TO LIDER;
  GRANT BECOME USER TO LIDER;
  GRANT COMMENT ANY TABLE TO LIDER;
  GRANT CREATE ANY CLUSTER TO LIDER;
  GRANT CREATE ANY CONTEXT TO LIDER;
  GRANT CREATE ANY DIMENSION TO LIDER;
  GRANT CREATE ANY DIRECTORY TO LIDER;
  GRANT CREATE ANY INDEX TO LIDER;
  GRANT CREATE ANY INDEXTYPE TO LIDER;
  GRANT CREATE ANY LIBRARY TO LIDER;
  GRANT CREATE ANY OPERATOR TO LIDER;
  GRANT CREATE ANY OUTLINE TO LIDER;
  GRANT CREATE ANY PROCEDURE TO LIDER;
  GRANT CREATE ANY SEQUENCE TO LIDER;
  GRANT CREATE ANY SNAPSHOT TO LIDER;
  GRANT CREATE ANY SYNONYM TO LIDER;
  GRANT CREATE ANY TABLE TO LIDER;
  GRANT CREATE ANY TRIGGER TO LIDER;
  GRANT CREATE ANY TYPE TO LIDER;
  GRANT CREATE ANY VIEW TO LIDER;
  GRANT CREATE CLUSTER TO LIDER;
  GRANT CREATE DATABASE LINK TO LIDER;
  GRANT CREATE DIMENSION TO LIDER;
  GRANT CREATE INDEXTYPE TO LIDER;
  GRANT CREATE LIBRARY TO LIDER;
  GRANT CREATE OPERATOR TO LIDER;
  GRANT CREATE PROCEDURE TO LIDER;
  GRANT CREATE PROFILE TO LIDER;
  GRANT CREATE PUBLIC DATABASE LINK TO LIDER;
  GRANT CREATE PUBLIC SYNONYM TO LIDER;
  GRANT CREATE ROLE TO LIDER;
  GRANT CREATE ROLLBACK SEGMENT TO LIDER;
  GRANT CREATE SEQUENCE TO LIDER;
  GRANT CREATE SESSION TO LIDER;
  GRANT CREATE SNAPSHOT TO LIDER;
  GRANT CREATE SYNONYM TO LIDER;
  GRANT CREATE TABLE TO LIDER;
  GRANT CREATE TABLESPACE TO LIDER;
  GRANT CREATE TRIGGER TO LIDER;
  GRANT CREATE TYPE TO LIDER;
  GRANT CREATE USER TO LIDER;
  GRANT CREATE VIEW TO LIDER;
  GRANT DELETE ANY TABLE TO LIDER;
  GRANT DROP ANY CLUSTER TO LIDER;
  GRANT DROP ANY CONTEXT TO LIDER;
  GRANT DROP ANY DIMENSION TO LIDER;
  GRANT DROP ANY DIRECTORY TO LIDER;
  GRANT DROP ANY INDEX TO LIDER;
  GRANT DROP ANY INDEXTYPE TO LIDER;
  GRANT DROP ANY LIBRARY TO LIDER;
  GRANT DROP ANY OPERATOR TO LIDER;
  GRANT DROP ANY OUTLINE TO LIDER;
  GRANT DROP ANY PROCEDURE TO LIDER;
  GRANT DROP ANY ROLE TO LIDER;
  GRANT DROP ANY SEQUENCE TO LIDER;
  GRANT DROP ANY SNAPSHOT TO LIDER;
  GRANT DROP ANY SYNONYM TO LIDER;
  GRANT DROP ANY TABLE TO LIDER;
  GRANT DROP ANY TRIGGER TO LIDER;
  GRANT DROP ANY TYPE TO LIDER;
  GRANT DROP ANY VIEW TO LIDER;
  GRANT DROP PROFILE TO LIDER;
  GRANT DROP PUBLIC DATABASE LINK TO LIDER;
  GRANT DROP PUBLIC SYNONYM TO LIDER;
  GRANT DROP ROLLBACK SEGMENT TO LIDER;
  GRANT DROP TABLESPACE TO LIDER;
  GRANT DROP USER TO LIDER;
  GRANT EXECUTE ANY INDEXTYPE TO LIDER;
  GRANT EXECUTE ANY LIBRARY TO LIDER;
  GRANT EXECUTE ANY OPERATOR TO LIDER;
  GRANT EXECUTE ANY PROCEDURE TO LIDER;
  GRANT EXECUTE ANY TYPE TO LIDER;
  GRANT FORCE ANY TRANSACTION TO LIDER;
  GRANT FORCE TRANSACTION TO LIDER;
  GRANT GLOBAL QUERY REWRITE TO LIDER;
  GRANT GRANT ANY PRIVILEGE TO LIDER;
  GRANT GRANT ANY ROLE TO LIDER;
  GRANT INSERT ANY TABLE TO LIDER;
  GRANT LOCK ANY TABLE TO LIDER;
  GRANT MANAGE TABLESPACE TO LIDER;
  GRANT QUERY REWRITE TO LIDER;
  GRANT RESTRICTED SESSION TO LIDER;
  GRANT SELECT ANY SEQUENCE TO LIDER;
  GRANT SELECT ANY TABLE TO LIDER;
  GRANT UNLIMITED TABLESPACE TO LIDER;
  GRANT UPDATE ANY TABLE TO LIDER;
  -- 1 Tablespace Quota for LIDER 
  ALTER USER LIDER QUOTA UNLIMITED ON USERS;


CREATE USER LUKASHOV
  IDENTIFIED BY VALUES '900BBFC2F32BD8F2'
  DEFAULT TABLESPACE USERS
  TEMPORARY TABLESPACE TEMP
  PROFILE USERS
  ACCOUNT UNLOCK;
  -- 3 Roles for LUKASHOV 
  GRANT CONNECT TO LUKASHOV;
  GRANT REPORT TO LUKASHOV;
  GRANT WORKSPACE TO LUKASHOV;
  ALTER USER LUKASHOV DEFAULT ROLE CONNECT;


CREATE USER MAG1AR
  IDENTIFIED BY VALUES 'C6E389A9028A51D1'
  DEFAULT TABLESPACE USERS
  TEMPORARY TABLESPACE TEMP
  PROFILE USERS
  ACCOUNT UNLOCK;
  -- 3 Roles for MAG1AR 
  GRANT CONNECT TO MAG1AR;
  GRANT REPORT TO MAG1AR;
  GRANT WORKSPACE TO MAG1AR;
  ALTER USER MAG1AR DEFAULT ROLE CONNECT;


CREATE USER MAG2
  IDENTIFIED BY VALUES 'D5168956818FE07F'
  DEFAULT TABLESPACE USERS
  TEMPORARY TABLESPACE TEMP
  PROFILE USERS
  ACCOUNT UNLOCK;
  -- 3 Roles for MAG2 
  GRANT CONNECT TO MAG2;
  GRANT REPORT TO MAG2;
  GRANT WORKSPACE TO MAG2;
  ALTER USER MAG2 DEFAULT ROLE CONNECT;


CREATE USER MAG72
  IDENTIFIED BY VALUES '0E736C681D4FF565'
  DEFAULT TABLESPACE USERS
  TEMPORARY TABLESPACE TEMP
  PROFILE USERS
  ACCOUNT UNLOCK;
  -- 3 Roles for MAG72 
  GRANT CONNECT TO MAG72;
  GRANT REPORT TO MAG72;
  GRANT WORKSPACE TO MAG72;
  ALTER USER MAG72 DEFAULT ROLE CONNECT;


CREATE USER MAG73
  IDENTIFIED BY VALUES '5D0E71A531FDC0E2'
  DEFAULT TABLESPACE USERS
  TEMPORARY TABLESPACE TEMP
  PROFILE USERS
  ACCOUNT UNLOCK;
  -- 3 Roles for MAG73 
  GRANT CONNECT TO MAG73;
  GRANT REPORT TO MAG73;
  GRANT WORKSPACE TO MAG73;
  ALTER USER MAG73 DEFAULT ROLE CONNECT;


CREATE USER MANAGER1
  IDENTIFIED BY VALUES '22B09D20D9BC3135'
  DEFAULT TABLESPACE USERS
  TEMPORARY TABLESPACE TEMP
  PROFILE USERS
  ACCOUNT UNLOCK;
  -- 3 Roles for MANAGER1 
  GRANT CONNECT TO MANAGER1;
  GRANT REPORT TO MANAGER1;
  GRANT WORKSPACE TO MANAGER1;
  ALTER USER MANAGER1 DEFAULT ROLE CONNECT;


CREATE USER MARHENKO
  IDENTIFIED BY VALUES '85DFA5BFD1F6B2E3'
  DEFAULT TABLESPACE USERS
  TEMPORARY TABLESPACE TEMP
  PROFILE USERS
  ACCOUNT UNLOCK;
  -- 3 Roles for MARHENKO 
  GRANT CONNECT TO MARHENKO;
  GRANT REPORT TO MARHENKO;
  GRANT WORKSPACE TO MARHENKO;
  ALTER USER MARHENKO DEFAULT ROLE CONNECT;


CREATE USER MASTER
  IDENTIFIED BY VALUES '76626E2F3790C349'
  DEFAULT TABLESPACE USERS
  TEMPORARY TABLESPACE TEMP
  PROFILE USERS
  ACCOUNT UNLOCK;
  -- 3 Roles for MASTER 
  GRANT CONNECT TO MASTER;
  GRANT REPORT TO MASTER;
  GRANT WORKSPACE TO MASTER;
  ALTER USER MASTER DEFAULT ROLE CONNECT;


CREATE USER MATUSHEV
  IDENTIFIED BY VALUES '68ADE174B256EFDA'
  DEFAULT TABLESPACE USERS
  TEMPORARY TABLESPACE TEMP
  PROFILE USERS
  ACCOUNT UNLOCK;
  -- 3 Roles for MATUSHEV 
  GRANT CONNECT TO MATUSHEV;
  GRANT REPORT TO MATUSHEV;
  GRANT WORKSPACE TO MATUSHEV;
  ALTER USER MATUSHEV DEFAULT ROLE CONNECT;


CREATE USER MOROZ
  IDENTIFIED BY VALUES '3FA9FD0FA5F4D46C'
  DEFAULT TABLESPACE USERS
  TEMPORARY TABLESPACE TEMP
  PROFILE USERS
  ACCOUNT UNLOCK;
  -- 3 Roles for MOROZ 
  GRANT CONNECT TO MOROZ;
  GRANT REPORT TO MOROZ;
  GRANT WORKSPACE TO MOROZ;
  ALTER USER MOROZ DEFAULT ROLE CONNECT;


CREATE USER MUKHAMETOVA
  IDENTIFIED BY VALUES 'BD8896F9D49BEB6D'
  DEFAULT TABLESPACE USERS
  TEMPORARY TABLESPACE TEMP
  PROFILE USERS
  ACCOUNT UNLOCK;
  -- 3 Roles for MUKHAMETOVA 
  GRANT CONNECT TO MUKHAMETOVA;
  GRANT REPORT TO MUKHAMETOVA;
  GRANT WORKSPACE TO MUKHAMETOVA;
  ALTER USER MUKHAMETOVA DEFAULT ROLE CONNECT;


CREATE USER MVANEEVA
  IDENTIFIED BY VALUES 'F3957FA4D58B3D08'
  DEFAULT TABLESPACE USERS
  TEMPORARY TABLESPACE TEMP
  PROFILE USERS
  ACCOUNT UNLOCK;
  -- 3 Roles for MVANEEVA 
  GRANT CONNECT TO MVANEEVA;
  GRANT REPORT TO MVANEEVA;
  GRANT WORKSPACE TO MVANEEVA;
  ALTER USER MVANEEVA DEFAULT ROLE CONNECT;


CREATE USER NAGOVITCIN
  IDENTIFIED BY VALUES '118AA1C52009537D'
  DEFAULT TABLESPACE USERS
  TEMPORARY TABLESPACE TEMP
  PROFILE USERS
  ACCOUNT UNLOCK;
  -- 3 Roles for NAGOVITCIN 
  GRANT CONNECT TO NAGOVITCIN;
  GRANT REPORT TO NAGOVITCIN;
  GRANT WORKSPACE TO NAGOVITCIN;
  ALTER USER NAGOVITCIN DEFAULT ROLE CONNECT;


CREATE USER NECHAEVA
  IDENTIFIED BY VALUES 'EDB8DE74262DB24F'
  DEFAULT TABLESPACE USERS
  TEMPORARY TABLESPACE TEMP
  PROFILE USERS
  ACCOUNT UNLOCK;
  -- 3 Roles for NECHAEVA 
  GRANT CONNECT TO NECHAEVA;
  GRANT REPORT TO NECHAEVA;
  GRANT WORKSPACE TO NECHAEVA;
  ALTER USER NECHAEVA DEFAULT ROLE CONNECT;


CREATE USER NMANTROVA
  IDENTIFIED BY VALUES '5167DF641325E6FC'
  DEFAULT TABLESPACE USERS
  TEMPORARY TABLESPACE TEMP
  PROFILE USERS
  ACCOUNT UNLOCK;
  -- 3 Roles for NMANTROVA 
  GRANT CONNECT TO NMANTROVA;
  GRANT REPORT TO NMANTROVA;
  GRANT WORKSPACE TO NMANTROVA;
  ALTER USER NMANTROVA DEFAULT ROLE CONNECT;


CREATE USER NOREPL
  IDENTIFIED BY VALUES '7346387A4EA01264'
  DEFAULT TABLESPACE USERS
  TEMPORARY TABLESPACE TEMP
  PROFILE ADMIN
  ACCOUNT UNLOCK;
  -- 4 Roles for NOREPL 
  GRANT CONNECT TO NOREPL;
  GRANT DBA TO NOREPL;
  GRANT REPORT TO NOREPL;
  GRANT WORKSPACE TO NOREPL;
  ALTER USER NOREPL DEFAULT ROLE ALL;
  -- 3 System Privileges for NOREPL 
  GRANT ALTER ANY TABLE TO NOREPL;
  GRANT SELECT ANY TABLE TO NOREPL;
  GRANT UNLIMITED TABLESPACE TO NOREPL;
  -- 3 Tablespace Quotas for NOREPL 
  ALTER USER NOREPL QUOTA UNLIMITED ON AUDIT_KERNEL;
  ALTER USER NOREPL QUOTA UNLIMITED ON IDX;
  ALTER USER NOREPL QUOTA UNLIMITED ON USERS;
  -- 5 Object Privileges for NOREPL 
    GRANT EXECUTE ON LIDER.FACT_VALUE_MO TO NOREPL;
    GRANT EXECUTE ON LIDER.FACT_WEIGHT_MO TO NOREPL;
    GRANT EXECUTE ON LIDER.MAKE_OUT_WBILL_MO_OS_TRAN TO NOREPL;
    GRANT EXECUTE ON LIDER.MAKE_OUT_WBILL_RW_OS_TRAN TO NOREPL;
    GRANT EXECUTE ON LIDER.PRC_CC TO NOREPL;


CREATE USER OPERATOR
  IDENTIFIED BY VALUES '9EC37F63EA349324'
  DEFAULT TABLESPACE USERS
  TEMPORARY TABLESPACE TEMP
  PROFILE USERS
  ACCOUNT UNLOCK;
  -- 3 Roles for OPERATOR 
  GRANT CONNECT TO OPERATOR;
  GRANT REPORT TO OPERATOR;
  GRANT WORKSPACE TO OPERATOR;
  ALTER USER OPERATOR DEFAULT ROLE CONNECT;


CREATE USER OSTASHOVA
  IDENTIFIED BY VALUES '60362AB48729C500'
  DEFAULT TABLESPACE USERS
  TEMPORARY TABLESPACE TEMP
  PROFILE USERS
  ACCOUNT UNLOCK;
  -- 3 Roles for OSTASHOVA 
  GRANT CONNECT TO OSTASHOVA;
  GRANT REPORT TO OSTASHOVA;
  GRANT WORKSPACE TO OSTASHOVA;
  ALTER USER OSTASHOVA DEFAULT ROLE CONNECT;


CREATE USER POGORELAY
  IDENTIFIED BY VALUES 'A61DDDFE02846AD0'
  DEFAULT TABLESPACE USERS
  TEMPORARY TABLESPACE TEMP
  PROFILE USERS
  ACCOUNT UNLOCK;
  -- 3 Roles for POGORELAY 
  GRANT CONNECT TO POGORELAY;
  GRANT REPORT TO POGORELAY;
  GRANT WORKSPACE TO POGORELAY;
  ALTER USER POGORELAY DEFAULT ROLE CONNECT;


CREATE USER POPOVA
  IDENTIFIED BY VALUES 'E248323DED7CAEA2'
  DEFAULT TABLESPACE USERS
  TEMPORARY TABLESPACE TEMP
  PROFILE USERS
  ACCOUNT UNLOCK;
  -- 3 Roles for POPOVA 
  GRANT CONNECT TO POPOVA;
  GRANT REPORT TO POPOVA;
  GRANT WORKSPACE TO POPOVA;
  ALTER USER POPOVA DEFAULT ROLE CONNECT;


CREATE USER R3
  IDENTIFIED BY VALUES '3B7A3B4F1305E762'
  DEFAULT TABLESPACE USERS
  TEMPORARY TABLESPACE TEMP
  PROFILE ADMIN
  ACCOUNT UNLOCK;
  -- 1 Role for R3 
  GRANT WORKSPACE TO R3;
  ALTER USER R3 DEFAULT ROLE ALL;
  -- 111 System Privileges for R3 
  GRANT ADMINISTER DATABASE TRIGGER TO R3;
  GRANT ALTER ANY CLUSTER TO R3;
  GRANT ALTER ANY DIMENSION TO R3;
  GRANT ALTER ANY INDEX TO R3;
  GRANT ALTER ANY INDEXTYPE TO R3;
  GRANT ALTER ANY LIBRARY TO R3;
  GRANT ALTER ANY OUTLINE TO R3;
  GRANT ALTER ANY PROCEDURE TO R3;
  GRANT ALTER ANY ROLE TO R3;
  GRANT ALTER ANY SEQUENCE TO R3;
  GRANT ALTER ANY SNAPSHOT TO R3;
  GRANT ALTER ANY TABLE TO R3;
  GRANT ALTER ANY TRIGGER TO R3;
  GRANT ALTER ANY TYPE TO R3;
  GRANT ALTER DATABASE TO R3;
  GRANT ALTER PROFILE TO R3;
  GRANT ALTER RESOURCE COST TO R3;
  GRANT ALTER ROLLBACK SEGMENT TO R3;
  GRANT ALTER SESSION TO R3;
  GRANT ALTER SYSTEM TO R3;
  GRANT ALTER TABLESPACE TO R3;
  GRANT ALTER USER TO R3;
  GRANT ANALYZE ANY TO R3;
  GRANT AUDIT ANY TO R3;
  GRANT AUDIT SYSTEM TO R3;
  GRANT BACKUP ANY TABLE TO R3;
  GRANT BECOME USER TO R3;
  GRANT COMMENT ANY TABLE TO R3;
  GRANT CREATE ANY CLUSTER TO R3;
  GRANT CREATE ANY CONTEXT TO R3;
  GRANT CREATE ANY DIMENSION TO R3;
  GRANT CREATE ANY DIRECTORY TO R3;
  GRANT CREATE ANY INDEX TO R3;
  GRANT CREATE ANY INDEXTYPE TO R3;
  GRANT CREATE ANY LIBRARY TO R3;
  GRANT CREATE ANY OPERATOR TO R3;
  GRANT CREATE ANY OUTLINE TO R3;
  GRANT CREATE ANY PROCEDURE TO R3;
  GRANT CREATE ANY SEQUENCE TO R3;
  GRANT CREATE ANY SNAPSHOT TO R3;
  GRANT CREATE ANY SYNONYM TO R3;
  GRANT CREATE ANY TABLE TO R3;
  GRANT CREATE ANY TRIGGER TO R3;
  GRANT CREATE ANY TYPE TO R3;
  GRANT CREATE ANY VIEW TO R3;
  GRANT CREATE CLUSTER TO R3;
  GRANT CREATE DATABASE LINK TO R3;
  GRANT CREATE DIMENSION TO R3;
  GRANT CREATE INDEXTYPE TO R3;
  GRANT CREATE LIBRARY TO R3;
  GRANT CREATE OPERATOR TO R3;
  GRANT CREATE PROCEDURE TO R3;
  GRANT CREATE PROFILE TO R3;
  GRANT CREATE PUBLIC DATABASE LINK TO R3;
  GRANT CREATE PUBLIC SYNONYM TO R3;
  GRANT CREATE ROLE TO R3;
  GRANT CREATE ROLLBACK SEGMENT TO R3;
  GRANT CREATE SEQUENCE TO R3;
  GRANT CREATE SESSION TO R3;
  GRANT CREATE SNAPSHOT TO R3;
  GRANT CREATE SYNONYM TO R3;
  GRANT CREATE TABLE TO R3;
  GRANT CREATE TABLESPACE TO R3;
  GRANT CREATE TRIGGER TO R3;
  GRANT CREATE TYPE TO R3;
  GRANT CREATE USER TO R3;
  GRANT CREATE VIEW TO R3;
  GRANT DELETE ANY TABLE TO R3;
  GRANT DROP ANY CLUSTER TO R3;
  GRANT DROP ANY CONTEXT TO R3;
  GRANT DROP ANY DIMENSION TO R3;
  GRANT DROP ANY DIRECTORY TO R3;
  GRANT DROP ANY INDEX TO R3;
  GRANT DROP ANY INDEXTYPE TO R3;
  GRANT DROP ANY LIBRARY TO R3;
  GRANT DROP ANY OPERATOR TO R3;
  GRANT DROP ANY OUTLINE TO R3;
  GRANT DROP ANY PROCEDURE TO R3;
  GRANT DROP ANY ROLE TO R3;
  GRANT DROP ANY SEQUENCE TO R3;
  GRANT DROP ANY SNAPSHOT TO R3;
  GRANT DROP ANY SYNONYM TO R3;
  GRANT DROP ANY TABLE TO R3;
  GRANT DROP ANY TRIGGER TO R3;
  GRANT DROP ANY TYPE TO R3;
  GRANT DROP ANY VIEW TO R3;
  GRANT DROP PROFILE TO R3;
  GRANT DROP PUBLIC DATABASE LINK TO R3;
  GRANT DROP PUBLIC SYNONYM TO R3;
  GRANT DROP ROLLBACK SEGMENT TO R3;
  GRANT DROP TABLESPACE TO R3;
  GRANT DROP USER TO R3;
  GRANT EXECUTE ANY INDEXTYPE TO R3;
  GRANT EXECUTE ANY LIBRARY TO R3;
  GRANT EXECUTE ANY OPERATOR TO R3;
  GRANT EXECUTE ANY PROCEDURE TO R3;
  GRANT EXECUTE ANY TYPE TO R3;
  GRANT FORCE ANY TRANSACTION TO R3;
  GRANT FORCE TRANSACTION TO R3;
  GRANT GLOBAL QUERY REWRITE TO R3;
  GRANT GRANT ANY PRIVILEGE TO R3;
  GRANT GRANT ANY ROLE TO R3;
  GRANT INSERT ANY TABLE TO R3;
  GRANT LOCK ANY TABLE TO R3;
  GRANT MANAGE TABLESPACE TO R3;
  GRANT QUERY REWRITE TO R3;
  GRANT RESTRICTED SESSION TO R3;
  GRANT SELECT ANY SEQUENCE TO R3;
  GRANT SELECT ANY TABLE TO R3;
  GRANT UNLIMITED TABLESPACE TO R3;
  GRANT UPDATE ANY TABLE TO R3;


CREATE USER RARTEEVA
  IDENTIFIED BY VALUES '1375CB8F42554FED'
  DEFAULT TABLESPACE USERS
  TEMPORARY TABLESPACE TEMP
  PROFILE USERS
  ACCOUNT UNLOCK;
  -- 3 Roles for RARTEEVA 
  GRANT CONNECT TO RARTEEVA;
  GRANT REPORT TO RARTEEVA;
  GRANT WORKSPACE TO RARTEEVA;
  ALTER USER RARTEEVA DEFAULT ROLE CONNECT;


CREATE USER REPL
  IDENTIFIED BY VALUES 'C23D280F065F0EFB'
  DEFAULT TABLESPACE REPL
  TEMPORARY TABLESPACE TEMP
  PROFILE ADMIN
  ACCOUNT UNLOCK;
  -- 4 Roles for REPL 
  GRANT CONNECT TO REPL;
  GRANT DBA TO REPL;
  GRANT EXP_FULL_DATABASE TO REPL;
  GRANT IMP_FULL_DATABASE TO REPL;
  ALTER USER REPL DEFAULT ROLE ALL;
  -- 1 System Privilege for REPL 
  GRANT UNLIMITED TABLESPACE TO REPL;
  -- 1 Tablespace Quota for REPL 
  ALTER USER REPL QUOTA UNLIMITED ON REPL;
  -- 4 Object Privileges for REPL 
    GRANT EXECUTE ON LIDER.PCK_CAG_REPL TO REPL;
    GRANT EXECUTE ON LIDER.PCK_CAG_TRANSFER TO REPL;
    GRANT SELECT ON LIDER.ZREPL_CONFIG TO REPL;
    GRANT SELECT ON LIDER.ZREPL_SRV TO REPL;


CREATE USER REPL1
  IDENTIFIED BY VALUES '65A6E68E56A93C21'
  DEFAULT TABLESPACE REPL
  TEMPORARY TABLESPACE TEMP
  PROFILE ADMIN
  ACCOUNT UNLOCK;
  -- 2 Roles for REPL1 
  GRANT CONNECT TO REPL1;
  GRANT DBA TO REPL1;
  ALTER USER REPL1 DEFAULT ROLE ALL;
  -- 1 System Privilege for REPL1 
  GRANT UNLIMITED TABLESPACE TO REPL1;
  -- 1 Tablespace Quota for REPL1 
  ALTER USER REPL1 QUOTA UNLIMITED ON REPL;
  -- 2 Object Privileges for REPL1 
    GRANT EXECUTE ON LIDER.PCK_CAG_REPL TO REPL1;
    GRANT EXECUTE ON LIDER.PCK_CAG_TRANSFER TO REPL1;


CREATE USER REPL2
  IDENTIFIED BY VALUES '757F573276BA52A4'
  DEFAULT TABLESPACE REPL
  TEMPORARY TABLESPACE TEMP
  PROFILE ADMIN
  ACCOUNT UNLOCK;
  -- 2 Roles for REPL2 
  GRANT CONNECT TO REPL2;
  GRANT DBA TO REPL2;
  ALTER USER REPL2 DEFAULT ROLE ALL;
  -- 1 System Privilege for REPL2 
  GRANT UNLIMITED TABLESPACE TO REPL2;
  -- 1 Tablespace Quota for REPL2 
  ALTER USER REPL2 QUOTA UNLIMITED ON REPL;


CREATE USER REPL6
  IDENTIFIED BY VALUES '072FE43C1DF8A6CF'
  DEFAULT TABLESPACE REPL
  TEMPORARY TABLESPACE TEMP
  PROFILE ADMIN
  ACCOUNT UNLOCK;
  -- 2 Roles for REPL6 
  GRANT CONNECT TO REPL6;
  GRANT DBA TO REPL6;
  ALTER USER REPL6 DEFAULT ROLE ALL;
  -- 1 System Privilege for REPL6 
  GRANT UNLIMITED TABLESPACE TO REPL6;
  -- 1 Tablespace Quota for REPL6 
  ALTER USER REPL6 QUOTA UNLIMITED ON REPL;


CREATE USER SIDOROVA
  IDENTIFIED BY VALUES '3DA5E383DFED72C4'
  DEFAULT TABLESPACE USERS
  TEMPORARY TABLESPACE TEMP
  PROFILE USERS
  ACCOUNT UNLOCK;
  -- 3 Roles for SIDOROVA 
  GRANT CONNECT TO SIDOROVA;
  GRANT REPORT TO SIDOROVA;
  GRANT WORKSPACE TO SIDOROVA;
  ALTER USER SIDOROVA DEFAULT ROLE CONNECT;


CREATE USER STBUH1
  IDENTIFIED BY VALUES '1AB9F93622769F3D'
  DEFAULT TABLESPACE USERS
  TEMPORARY TABLESPACE TEMP
  PROFILE USERS
  ACCOUNT UNLOCK;
  -- 3 Roles for STBUH1 
  GRANT CONNECT TO STBUH1;
  GRANT REPORT TO STBUH1;
  GRANT WORKSPACE TO STBUH1;
  ALTER USER STBUH1 DEFAULT ROLE CONNECT;


CREATE USER STOPER1
  IDENTIFIED BY VALUES 'E22992DB1A218B48'
  DEFAULT TABLESPACE USERS
  TEMPORARY TABLESPACE TEMP
  PROFILE USERS
  ACCOUNT UNLOCK;
  -- 3 Roles for STOPER1 
  GRANT CONNECT TO STOPER1;
  GRANT REPORT TO STOPER1;
  GRANT WORKSPACE TO STOPER1;
  ALTER USER STOPER1 DEFAULT ROLE CONNECT;


CREATE USER TAX_REPORT
  IDENTIFIED BY VALUES 'E57CD50D8B809585'
  DEFAULT TABLESPACE USERS
  TEMPORARY TABLESPACE TEMP
  PROFILE USERS
  ACCOUNT UNLOCK;
  -- 2 System Privileges for TAX_REPORT 
  GRANT CREATE SESSION TO TAX_REPORT;
  GRANT SELECT ANY TABLE TO TAX_REPORT;
  -- 3 Object Privileges for TAX_REPORT 
    GRANT EXECUTE ON LIDER.PCK_GL TO TAX_REPORT;
    GRANT EXECUTE ON LIDER.PRC_WRITE_XML_STRING TO TAX_REPORT;
    GRANT DELETE, INSERT ON LIDER.TAX_XML_TMP TO TAX_REPORT;


CREATE USER TERENTYEVA
  IDENTIFIED BY VALUES '567ADCF9B0032F6D'
  DEFAULT TABLESPACE USERS
  TEMPORARY TABLESPACE TEMP
  PROFILE USERS
  ACCOUNT UNLOCK;
  -- 3 Roles for TERENTYEVA 
  GRANT CONNECT TO TERENTYEVA;
  GRANT REPORT TO TERENTYEVA;
  GRANT WORKSPACE TO TERENTYEVA;
  ALTER USER TERENTYEVA DEFAULT ROLE CONNECT;


CREATE USER TEST
  IDENTIFIED BY VALUES '7A0F2B316C212D67'
  DEFAULT TABLESPACE USERS
  TEMPORARY TABLESPACE TEMP
  PROFILE TEST
  ACCOUNT UNLOCK;
  -- 3 Roles for TEST 
  GRANT CONNECT TO TEST;
  GRANT REPORT TO TEST;
  GRANT WORKSPACE TO TEST;
  ALTER USER TEST DEFAULT ROLE CONNECT;


CREATE USER TOVOPER1
  IDENTIFIED BY VALUES '7E0ED8F81A64FD40'
  DEFAULT TABLESPACE USERS
  TEMPORARY TABLESPACE TEMP
  PROFILE USERS
  ACCOUNT UNLOCK;
  -- 3 Roles for TOVOPER1 
  GRANT CONNECT TO TOVOPER1;
  GRANT REPORT TO TOVOPER1;
  GRANT WORKSPACE TO TOVOPER1;
  ALTER USER TOVOPER1 DEFAULT ROLE CONNECT;


CREATE USER TSUHORUCHKO
  IDENTIFIED BY VALUES '18EAAFDC1481660C'
  DEFAULT TABLESPACE USERS
  TEMPORARY TABLESPACE TEMP
  PROFILE USERS
  ACCOUNT UNLOCK;
  -- 3 Roles for TSUHORUCHKO 
  GRANT CONNECT TO TSUHORUCHKO;
  GRANT REPORT TO TSUHORUCHKO;
  GRANT WORKSPACE TO TSUHORUCHKO;
  ALTER USER TSUHORUCHKO DEFAULT ROLE CONNECT;


CREATE USER USENHAN
  IDENTIFIED BY VALUES 'A2F2793EB424411D'
  DEFAULT TABLESPACE USERS
  TEMPORARY TABLESPACE TEMP
  PROFILE USERS
  ACCOUNT UNLOCK;
  -- 3 Roles for USENHAN 
  GRANT CONNECT TO USENHAN;
  GRANT REPORT TO USENHAN;
  GRANT WORKSPACE TO USENHAN;
  ALTER USER USENHAN DEFAULT ROLE CONNECT;


CREATE USER USTINOV
  IDENTIFIED BY VALUES 'A3467A9F637E6184'
  DEFAULT TABLESPACE USERS
  TEMPORARY TABLESPACE TEMP
  PROFILE USERS
  ACCOUNT UNLOCK;
  -- 3 Roles for USTINOV 
  GRANT CONNECT TO USTINOV;
  GRANT REPORT TO USTINOV;
  GRANT WORKSPACE TO USTINOV;
  ALTER USER USTINOV DEFAULT ROLE CONNECT;


CREATE USER VANEEV
  IDENTIFIED BY VALUES '5637681F470390BA'
  DEFAULT TABLESPACE USERS
  TEMPORARY TABLESPACE TEMP
  PROFILE USERS
  ACCOUNT UNLOCK;
  -- 3 Roles for VANEEV 
  GRANT CONNECT TO VANEEV;
  GRANT REPORT TO VANEEV;
  GRANT WORKSPACE TO VANEEV;
  ALTER USER VANEEV DEFAULT ROLE CONNECT;


CREATE USER VANUFRIEVA
  IDENTIFIED BY VALUES '636084D43604633E'
  DEFAULT TABLESPACE USERS
  TEMPORARY TABLESPACE TEMP
  PROFILE USERS
  ACCOUNT UNLOCK;
  -- 3 Roles for VANUFRIEVA 
  GRANT CONNECT TO VANUFRIEVA;
  GRANT REPORT TO VANUFRIEVA;
  GRANT WORKSPACE TO VANUFRIEVA;
  ALTER USER VANUFRIEVA DEFAULT ROLE CONNECT;


CREATE USER VASINDV
  IDENTIFIED BY VALUES '527A6001CBC106F2'
  DEFAULT TABLESPACE USERS
  TEMPORARY TABLESPACE TEMP
  PROFILE USERS
  ACCOUNT UNLOCK;
  -- 3 Roles for VASINDV 
  GRANT CONNECT TO VASINDV;
  GRANT REPORT TO VASINDV;
  GRANT WORKSPACE TO VASINDV;
  ALTER USER VASINDV DEFAULT ROLE CONNECT;


CREATE USER VASINVM
  IDENTIFIED BY VALUES 'AFC678C8F9225032'
  DEFAULT TABLESPACE USERS
  TEMPORARY TABLESPACE TEMP
  PROFILE USERS
  ACCOUNT UNLOCK;
  -- 3 Roles for VASINVM 
  GRANT CONNECT TO VASINVM;
  GRANT REPORT TO VASINVM;
  GRANT WORKSPACE TO VASINVM;
  ALTER USER VASINVM DEFAULT ROLE CONNECT;


CREATE USER VIBOROV
  IDENTIFIED BY VALUES 'DD0BE09ED241CF76'
  DEFAULT TABLESPACE USERS
  TEMPORARY TABLESPACE TEMP
  PROFILE FOX_PROFILE
  ACCOUNT UNLOCK;
  -- 4 Roles for VIBOROV 
  GRANT CONNECT TO VIBOROV;
  GRANT KERNEL_MANAGER TO VIBOROV;
  GRANT REPORT TO VIBOROV;
  GRANT WORKSPACE TO VIBOROV;
  ALTER USER VIBOROV DEFAULT ROLE CONNECT, KERNEL_MANAGER;


CREATE USER VOKUEVA
  IDENTIFIED BY VALUES '7E7F9EA1557FFF00'
  DEFAULT TABLESPACE USERS
  TEMPORARY TABLESPACE TEMP
  PROFILE USERS
  ACCOUNT UNLOCK;
  -- 3 Roles for VOKUEVA 
  GRANT CONNECT TO VOKUEVA;
  GRANT REPORT TO VOKUEVA;
  GRANT WORKSPACE TO VOKUEVA;
  ALTER USER VOKUEVA DEFAULT ROLE CONNECT;


CREATE USER YUDIN
  IDENTIFIED BY VALUES '1AD57A07FE46C809'
  DEFAULT TABLESPACE USERS
  TEMPORARY TABLESPACE TEMP
  PROFILE USERS
  ACCOUNT UNLOCK;
  -- 3 Roles for YUDIN 
  GRANT CONNECT TO YUDIN;
  GRANT REPORT TO YUDIN;
  GRANT WORKSPACE TO YUDIN;
  ALTER USER YUDIN DEFAULT ROLE CONNECT;


CREATE USER ZARIPOV
  IDENTIFIED BY VALUES '757882BF59DE116D'
  DEFAULT TABLESPACE USERS
  TEMPORARY TABLESPACE TEMP
  PROFILE USERS
  ACCOUNT UNLOCK;
  -- 3 Roles for ZARIPOV 
  GRANT CONNECT TO ZARIPOV;
  GRANT REPORT TO ZARIPOV;
  GRANT WORKSPACE TO ZARIPOV;
  ALTER USER ZARIPOV DEFAULT ROLE CONNECT;


CREATE USER ZARVA
  IDENTIFIED BY VALUES 'F1DAC653C1832F7C'
  DEFAULT TABLESPACE USERS
  TEMPORARY TABLESPACE TEMP
  PROFILE USERS
  ACCOUNT UNLOCK;
  -- 3 Roles for ZARVA 
  GRANT CONNECT TO ZARVA;
  GRANT REPORT TO ZARVA;
  GRANT WORKSPACE TO ZARVA;
  ALTER USER ZARVA DEFAULT ROLE CONNECT;


CREATE USER ZINAK
  IDENTIFIED BY VALUES '1A195CB5B4D11BB8'
  DEFAULT TABLESPACE USERS
  TEMPORARY TABLESPACE TEMP
  PROFILE USERS
  ACCOUNT UNLOCK;
  -- 3 Roles for ZINAK 
  GRANT CONNECT TO ZINAK;
  GRANT REPORT TO ZINAK;
  GRANT WORKSPACE TO ZINAK;
  ALTER USER ZINAK DEFAULT ROLE CONNECT;


