WHENEVER SQLERROR CONTINUE

spool restcopy.log

Connect / as sysdba

shutdown immediate

startup mount

RECOVER AUTOMATIC DATABASE UNTIL CANCEL USING BACKUP CONTROLFILE;

ALTER DATABASE OPEN RESETLOGS;

DROP TABLESPACE "TEMP" INCLUDING CONTENTS CASCADE CONSTRAINTS;

CREATE TEMPORARY TABLESPACE TEMP TEMPFILE '&2' SIZE 300M REUSE AUTOEXTEND ON NEXT 100M MAXSIZE 1000M EXTENT MANAGEMENT LOCAL;

spool off

exit
