CREATE TABLESPACE INDX DATAFILE 
  'K:\DB_UPDT\INDX01.DBF' SIZE 5M AUTOEXTEND ON NEXT 1280K MAXSIZE UNLIMITED
MINIMUM EXTENT 128K
LOGGING
DEFAULT STORAGE ( 
                  INITIAL     128K
                  NEXT        128K
                  MINEXTENTS  1
                  MAXEXTENTS  2147483645
                  PCTINCREASE 0
                )
ONLINE
PERMANENT
EXTENT MANAGEMENT DICTIONARY;


CREATE TABLESPACE PARUS DATAFILE 
  'K:\DB_UPDT\PARUS.ORA' SIZE 9450752K AUTOEXTEND ON NEXT 256M MAXSIZE 32767M
LOGGING
DEFAULT STORAGE ( 
                  INITIAL     128K
                  NEXT        128K
                  MINEXTENTS  1
                  MAXEXTENTS  2147483645
                  PCTINCREASE 0
                )
ONLINE
PERMANENT
EXTENT MANAGEMENT DICTIONARY;


CREATE TABLESPACE TEMP DATAFILE 
  'K:\DB_UPDT\TEMP01.DBF' SIZE 698880K AUTOEXTEND ON NEXT 640K MAXSIZE UNLIMITED
MINIMUM EXTENT 64K
LOGGING
DEFAULT STORAGE ( 
                  INITIAL     64K
                  NEXT        64K
                  MINEXTENTS  1
                  PCTINCREASE 0
                )
ONLINE
TEMPORARY
EXTENT MANAGEMENT DICTIONARY;




