CREATE USER PARUS
  IDENTIFIED BY 'admpar'
  DEFAULT TABLESPACE PARUS
  TEMPORARY TABLESPACE TEMP
  PROFILE DEFAULT
  ACCOUNT UNLOCK;
  GRANT DBA TO PARUS WITH ADMIN OPTION;
  ALTER USER PARUS DEFAULT ROLE ALL;
  GRANT ALTER ANY PROCEDURE TO PARUS;
  GRANT ALTER ANY TABLE TO PARUS;
  GRANT ALTER ANY TRIGGER TO PARUS;
  GRANT ALTER TABLESPACE TO PARUS;
  GRANT ANALYZE ANY TO PARUS;
  GRANT CREATE ANY PROCEDURE TO PARUS;
  GRANT CREATE ANY TABLE TO PARUS;
  GRANT DELETE ANY TABLE TO PARUS;
  GRANT DROP ANY INDEX TO PARUS;
  GRANT DROP ANY TABLE TO PARUS;
  GRANT EXECUTE ANY PROCEDURE TO PARUS;
  GRANT INSERT ANY TABLE TO PARUS;
  GRANT LOCK ANY TABLE TO PARUS;
  GRANT SELECT ANY TABLE TO PARUS WITH ADMIN OPTION;
  GRANT UNLIMITED TABLESPACE TO PARUS WITH ADMIN OPTION;
  GRANT UPDATE ANY TABLE TO PARUS;

  GRANT SELECT ON  SYS.QUEST_SPC_X$KDXST TO PARUS;
  GRANT SELECT ON  SYS.QUEST_SPC_X$KTFBFE TO PARUS;
  GRANT SELECT ON  SYS.QUEST_SPC_X$KTFBHC TO PARUS;
  GRANT SELECT ON  SYS.QUEST_SPC_X$KTFBUE TO PARUS;


