ALTER DATABASE ADD LOGFILE GROUP 1 ('D:\DB_ORCL\redo01_1', 'I:\DB_ORCL\redo01_2.ora') SIZE 50M;
ALTER DATABASE ADD LOGFILE GROUP 2 ('E:\DB_ORCL\redo02_1', 'J:\DB_ORCL\redo02_2.ora') SIZE 50M;
ALTER DATABASE ADD LOGFILE GROUP 3 ('D:\DB_ORCL\redo03_1', 'I:\DB_ORCL\redo03_2.ora') SIZE 50M;
ALTER DATABASE ADD LOGFILE GROUP 4 ('E:\DB_ORCL\redo04_1', 'J:\DB_ORCL\redo04_2.ora') SIZE 50M;
