-- USERS

CREATE USER OPERATIV
  IDENTIFIED BY VALUES '72F9AC678AE2449A'
  DEFAULT TABLESPACE FORS
  TEMPORARY TABLESPACE TEMP
  PROFILE DEFAULT
  ACCOUNT UNLOCK;
  -- 2 Roles for OPERATIV 
  GRANT CONNECT TO OPERATIV;
  GRANT RESOURCE TO OPERATIV;
  ALTER USER OPERATIV DEFAULT ROLE ALL;
  -- 1 System Privilege for OPERATIV 
  GRANT UNLIMITED TABLESPACE TO OPERATIV;



CREATE USER UNP
  IDENTIFIED BY VALUES '992D127D5C98BEC4'
  DEFAULT TABLESPACE USERS
  TEMPORARY TABLESPACE TEMP
  PROFILE DEFAULT
  ACCOUNT UNLOCK;
  -- 1 Role for UNP 
  GRANT CONNECT TO UNP;
  ALTER USER UNP DEFAULT ROLE ALL;
  -- 2 System Privileges for UNP 
  GRANT SELECT ANY TABLE TO UNP;
  GRANT SELECT ANY DICTIONARY TO UNP;
  -- 2 Tablespace Quotas for UNP 
  ALTER USER UNP QUOTA UNLIMITED ON USERS;
  ALTER USER UNP QUOTA UNLIMITED ON TEMP;


CREATE USER MASTER_GD
  IDENTIFIED BY VALUES 'BC9C855A10859ABD'
  DEFAULT TABLESPACE USERS
  TEMPORARY TABLESPACE TEMP
  PROFILE DEFAULT
  ACCOUNT UNLOCK;
  -- 2 Roles for MASTER_GD 
  GRANT CONNECT TO MASTER_GD;
  GRANT RESOURCE TO MASTER_GD;
  ALTER USER MASTER_GD DEFAULT ROLE ALL;
  -- 3 System Privileges for MASTER_GD 
  GRANT CREATE TRIGGER TO MASTER_GD;
  GRANT CREATE PROCEDURE TO MASTER_GD;
  GRANT UNLIMITED TABLESPACE TO MASTER_GD;
  -- 5 Object Privileges for MASTER_GD 
    GRANT REFERENCES ON  MASTER.APP_USERS TO MASTER_GD;
    GRANT SELECT ON  MASTER.MONTH_REE TO MASTER_GD;
    GRANT DELETE, INSERT, SELECT, UPDATE ON  MASTER.MONTH_VISIR TO MASTER_GD;
    GRANT SELECT ON  MASTER.V_MONTH_GD TO MASTER_GD;
    GRANT SELECT ON  MASTER.V_MONTH_REE TO MASTER_GD;


CREATE USER MASTER
  IDENTIFIED BY VALUES '76626E2F3790C349'
  DEFAULT TABLESPACE USERS
  TEMPORARY TABLESPACE TEMP
  PROFILE DEFAULT
  ACCOUNT UNLOCK;
  -- 3 Roles for MASTER 
  GRANT CONNECT TO MASTER;
  GRANT RESOURCE TO MASTER;
  GRANT QUEST_SL_SQLAB_ROLE TO MASTER;
  ALTER USER MASTER DEFAULT ROLE ALL;
  -- 9 System Privileges for MASTER 
  GRANT DROP ANY TABLE TO MASTER;
  GRANT CREATE SNAPSHOT TO MASTER;
  GRANT CREATE ANY TABLE TO MASTER;
  GRANT DELETE ANY TABLE TO MASTER;
  GRANT INSERT ANY TABLE TO MASTER;
  GRANT SELECT ANY TABLE TO MASTER;
  GRANT UPDATE ANY TABLE TO MASTER;
  GRANT UNLIMITED TABLESPACE TO MASTER;
  GRANT EXECUTE ANY PROCEDURE TO MASTER;
  -- 143 Object Privileges for MASTER 
    GRANT DELETE, INSERT, SELECT, UPDATE ON  LOAD_BUFFER.ALFAMON TO MASTER;
    GRANT SELECT, UPDATE ON  LOAD_BUFFER.ARC_REZ_LOC TO MASTER;
    GRANT SELECT ON  LOAD_BUFFER.BANKS TO MASTER;
    GRANT SELECT ON  LOAD_BUFFER.BANK_KORS TO MASTER;
    GRANT SELECT ON  LOAD_BUFFER.CAT_CEN TO MASTER;
    GRANT SELECT ON  LOAD_BUFFER.CIST_TYP TO MASTER;
    GRANT SELECT ON  LOAD_BUFFER.DOG TO MASTER;
    GRANT SELECT ON  LOAD_BUFFER.DOG_STRA TO MASTER;
    GRANT DELETE, INSERT, SELECT, UPDATE ON  LOAD_BUFFER.DOP_KVIT TO MASTER;
    GRANT SELECT ON  LOAD_BUFFER.DOVER TO MASTER;
    GRANT SELECT ON  LOAD_BUFFER.DOV_LINE TO MASTER;
    GRANT SELECT ON  LOAD_BUFFER.EXPED TO MASTER;
    GRANT SELECT ON  LOAD_BUFFER.EXPORT TO MASTER;
    GRANT SELECT ON  LOAD_BUFFER.EXPORT_GRP TO MASTER;
    GRANT SELECT ON  LOAD_BUFFER.FORMA TO MASTER;
    GRANT SELECT ON  LOAD_BUFFER.FOR_O TO MASTER;
    GRANT SELECT ON  LOAD_BUFFER.F_OTSR TO MASTER;
    GRANT SELECT ON  LOAD_BUFFER.GDOR TO MASTER;
    GRANT SELECT ON  LOAD_BUFFER.GP_NAPR TO MASTER;
    GRANT SELECT ON  LOAD_BUFFER.GROUP_ TO MASTER;
    GRANT SELECT, UPDATE ON  LOAD_BUFFER.GR_REAL TO MASTER;
    GRANT SELECT ON  LOAD_BUFFER.GTD_ALL TO MASTER;
    GRANT SELECT ON  LOAD_BUFFER.HOLDING TO MASTER;
    GRANT SELECT ON  LOAD_BUFFER.IDENT TO MASTER;
    GRANT SELECT ON  LOAD_BUFFER.K2N_KVIT TO MASTER;
    GRANT SELECT ON  LOAD_BUFFER.K2N_SVED TO MASTER;
    GRANT SELECT ON  LOAD_BUFFER.KINDPROD TO MASTER;
    GRANT SELECT ON  LOAD_BUFFER.KINDPROD_LUK TO MASTER;
    GRANT SELECT ON  LOAD_BUFFER.KINDPROD_SNP TO MASTER;
    GRANT DELETE, INSERT, SELECT, UPDATE ON  LOAD_BUFFER.KSSS_PREDPR TO MASTER;
    GRANT SELECT ON  LOAD_BUFFER.KTS_ALL TO MASTER;
    GRANT SELECT ON  LOAD_BUFFER.KTU2NPO TO MASTER;
    GRANT SELECT ON  LOAD_BUFFER.KTU_2_NPO TO MASTER;
    GRANT DELETE, INSERT, SELECT, UPDATE ON  LOAD_BUFFER.KVIT TO MASTER;
    GRANT DELETE, INSERT, SELECT, UPDATE ON  LOAD_BUFFER.KVITALFA TO MASTER;
    GRANT SELECT ON  LOAD_BUFFER.LOG_EVENTS TO MASTER;
    GRANT SELECT ON  LOAD_BUFFER.MESTO TO MASTER;
    GRANT SELECT ON  LOAD_BUFFER.MONTH TO MASTER;
    GRANT SELECT ON  LOAD_BUFFER.MONTH_FOR_RENEW TO MASTER;
    GRANT SELECT ON  LOAD_BUFFER.NAPR TO MASTER;
    GRANT SELECT ON  LOAD_BUFFER.NARIAD TO MASTER;
    GRANT SELECT ON  LOAD_BUFFER.NAR_LINE TO MASTER;
    GRANT SELECT ON  LOAD_BUFFER.NAZN_OTG TO MASTER;
    GRANT SELECT ON  LOAD_BUFFER.NKODIFIK TO MASTER;
    GRANT DELETE, SELECT, UPDATE ON  LOAD_BUFFER.NPR_CEN TO MASTER;
    GRANT SELECT ON  LOAD_BUFFER.NTABLPOK TO MASTER;
    GRANT SELECT ON  LOAD_BUFFER.OPL TO MASTER;
    GRANT DELETE, INSERT, SELECT, UPDATE ON  LOAD_BUFFER.OUT_PLAT TO MASTER;
    GRANT DELETE, INSERT, SELECT, UPDATE ON  LOAD_BUFFER.OUT_PLAT_POS TO MASTER;
    GRANT SELECT, UPDATE ON  LOAD_BUFFER.OUT_PLAT_SNP TO MASTER;
    GRANT ALTER, DELETE, INDEX, INSERT, REFERENCES, SELECT, UPDATE ON  LOAD_BUFFER.PARUS_DICACCFO TO MASTER;
    GRANT ALTER, DELETE, INDEX, INSERT, REFERENCES, SELECT, UPDATE ON  LOAD_BUFFER.PARUS_DICLACFO TO MASTER;
    GRANT SELECT ON  LOAD_BUFFER.PARUS_GRAPHPOINT TO MASTER;
    GRANT SELECT ON  LOAD_BUFFER.PERERAB TO MASTER;
    GRANT SELECT ON  LOAD_BUFFER.PERTYPE TO MASTER;
    GRANT SELECT ON  LOAD_BUFFER.PLOTG TO MASTER;
    GRANT SELECT, UPDATE ON  LOAD_BUFFER.PREDPR TO MASTER;
    GRANT SELECT ON  LOAD_BUFFER.PROD TO MASTER;
    GRANT SELECT ON  LOAD_BUFFER.PROD_LUK TO MASTER;
    GRANT SELECT ON  LOAD_BUFFER.PROD_OK TO MASTER;
    GRANT SELECT ON  LOAD_BUFFER.PROD_SNP TO MASTER;
    GRANT SELECT ON  LOAD_BUFFER.PROGRAM TO MASTER;
    GRANT SELECT ON  LOAD_BUFFER.PROTOKOL TO MASTER;
    GRANT SELECT ON  LOAD_BUFFER.REAL_OPL TO MASTER;
    GRANT SELECT ON  LOAD_BUFFER.REAL_OPL_KTU TO MASTER;
    GRANT DELETE, INSERT, SELECT, UPDATE ON  LOAD_BUFFER.REESTR TO MASTER;
    GRANT DELETE, INSERT, SELECT, UPDATE ON  LOAD_BUFFER.REESTR_KVIT TO MASTER;
    GRANT SELECT ON  LOAD_BUFFER.REGION TO MASTER;
    GRANT SELECT ON  LOAD_BUFFER.RS TO MASTER;
    GRANT SELECT, UPDATE ON  LOAD_BUFFER.SF_PR TO MASTER;
    GRANT SELECT ON  LOAD_BUFFER.SF_PR_BILLS TO MASTER;
    GRANT SELECT ON  LOAD_BUFFER.SF_PR_POS TO MASTER;
    GRANT DELETE, INSERT, SELECT, UPDATE ON  LOAD_BUFFER.SOBSTV TO MASTER;
    GRANT SELECT ON  LOAD_BUFFER.SPECIF TO MASTER;
    GRANT SELECT ON  LOAD_BUFFER.SPR_SOB TO MASTER;
    GRANT SELECT ON  LOAD_BUFFER.STAN TO MASTER;
    GRANT SELECT ON  LOAD_BUFFER.STAN_PREDPR TO MASTER;
    GRANT SELECT ON  LOAD_BUFFER.STATES TO MASTER;
    GRANT INSERT, SELECT, UPDATE ON  LOAD_BUFFER.SVED TO MASTER;
    GRANT INSERT, SELECT, UPDATE ON  LOAD_BUFFER.SVED_REESTR TO MASTER;
    GRANT SELECT ON  LOAD_BUFFER.TEX_PD TO MASTER;
    GRANT DELETE, INSERT, SELECT, UPDATE ON  LOAD_BUFFER.TMP_FIL_REALIZ TO MASTER;
    GRANT DELETE, INSERT, SELECT, UPDATE ON  LOAD_BUFFER.TO_SS TO MASTER;
    GRANT DELETE, INSERT, SELECT, UPDATE ON  LOAD_BUFFER.TO_SS_TMP TO MASTER;
    GRANT SELECT ON  LOAD_BUFFER.TRACKS TO MASTER;
    GRANT SELECT ON  LOAD_BUFFER.TYPES TO MASTER;
    GRANT SELECT ON  LOAD_BUFFER.UHTA_REE TO MASTER;
    GRANT SELECT ON  LOAD_BUFFER.USL_OPL TO MASTER;
    GRANT SELECT ON  LOAD_BUFFER.U_DOG TO MASTER;
    GRANT SELECT ON  LOAD_BUFFER.VAG_TYPE TO MASTER;
    GRANT SELECT ON  LOAD_BUFFER.VALPASP TO MASTER;
    GRANT SELECT ON  LOAD_BUFFER.VALSVED TO MASTER;
    GRANT SELECT ON  LOAD_BUFFER.VALSVED_REESTR TO MASTER;
    GRANT SELECT, UPDATE ON  LOAD_BUFFER.VETKA TO MASTER;
    GRANT SELECT ON  LOAD_BUFFER.VID_DOG TO MASTER;
    GRANT SELECT ON  LOAD_BUFFER.VID_LOAD TO MASTER;
    GRANT SELECT ON  LOAD_BUFFER.VID_OTGR TO MASTER;
    GRANT SELECT ON  LOAD_BUFFER.VID_USL TO MASTER;
    GRANT DELETE, INSERT, SELECT, UPDATE ON  LOAD_BUFFER.V_DICACCFO TO MASTER;
    GRANT DELETE, INSERT, SELECT, UPDATE ON  LOAD_BUFFER.V_DICLACFO TO MASTER;
    GRANT DELETE, INSERT, SELECT, UPDATE ON  LOAD_BUFFER.V_OUT_PLAT_WITH_TO_SS TO MASTER;
    GRANT SELECT ON  LOAD_BUFFER.V_R3_BILLS TO MASTER;
    GRANT SELECT ON  LOAD_BUFFER.V_R3_BILL_POS TO MASTER;
    GRANT SELECT ON  LOAD_BUFFER.ZAGPASP TO MASTER;
    GRANT INSERT, SELECT ON  MASTER_SHADOW.TABLE_ACTIVITY_LOG TO MASTER;
    GRANT EXECUTE ON  REPADMIN.GET_IND TO MASTER;
    GRANT DELETE, INSERT, SELECT, UPDATE ON  SAIO04.BU_BILL TO MASTER;
    GRANT ALTER, DELETE, INSERT, SELECT, UPDATE ON  SAIO04.LORP_BUF TO MASTER;
    GRANT EXECUTE ON  SAIO04.LORP_LOAD TO MASTER;
    GRANT DELETE, SELECT ON  SAIO04.LORP_REPORT_ELEMENTS TO MASTER;
    GRANT DELETE, SELECT ON  SAIO04.LORP_REPORT_HEADERS TO MASTER;
    GRANT DELETE, SELECT ON  SAIO04.LORP_TMP_CHECK TO MASTER;
    GRANT SELECT, UPDATE ON  SAIO04.LO_BILL TO MASTER;
    GRANT SELECT ON  SAIO04.LO_PRODUCT TO MASTER;
    GRANT DELETE, INSERT, SELECT, UPDATE ON  SFDBF.MOVEPROD TO MASTER;
    GRANT DELETE, INSERT, SELECT, UPDATE ON  SFDBF.MOVEPROD_TEST TO MASTER;
    GRANT EXECUTE ON  SVETA.GET_AV_PLRDOCS TO MASTER;
    GRANT DELETE, INSERT, SELECT, UPDATE ON  SVETA.SEND_OTGR_POKUP TO MASTER;
    GRANT DELETE, INSERT, SELECT, UPDATE ON  SVETA.SEND_POZ_POKUP TO MASTER;
    GRANT DELETE, INSERT, SELECT, UPDATE ON  SVETA.SEND_POZ_POKUP_USL TO MASTER;
    GRANT DELETE, INSERT, SELECT, UPDATE ON  SVETA.SEND_SFAK_POKUP TO MASTER;
    GRANT DELETE, INSERT, SELECT, UPDATE ON  SVETA.SEND_SFAK_POKUP_USL TO MASTER;
    GRANT EXECUTE ON  SVETA.SF_F_GET_PROPISI_SFPROD TO MASTER;
    GRANT EXECUTE ON  SVETA.SF_F_GET_PROPISI_SFPRODNDS TO MASTER;
    GRANT EXECUTE ON  SVETA.SF_F_GET_PROPISI_SFPRODNONDS TO MASTER;
    GRANT EXECUTE ON  SVETA.SF_F_GET_PROPISI_VES TO MASTER;
    GRANT SELECT ON  SVETA.SF_KLS_PRED TO MASTER;
    GRANT SELECT ON  SVETA.SF_OPL_PROD TO MASTER;
    GRANT SELECT ON  SVETA.SF_POZ_PROD TO MASTER;
    GRANT ALTER, DELETE, INDEX, INSERT, REFERENCES, SELECT, UPDATE, ON COMMIT REFRESH, QUERY REWRITE, DEBUG, FLASHBACK ON  SVETA.SF_POZ_VYR TO MASTER;
    GRANT SELECT ON  SVETA.SF_POZ_VYR_OLD TO MASTER;
    GRANT ALTER, DELETE, INSERT, REFERENCES, SELECT, UPDATE ON  SVETA.SF_POZ_VYR_PROBA TO MASTER;
    GRANT SELECT ON  SVETA.SF_SFAK_PROD TO MASTER;
    GRANT SELECT ON  SVETA.SF_STAT0_POZ_PROD TO MASTER;
    GRANT EXECUTE ON  SYS.DBMS_REPCAT_INTERNAL_PACKAGE TO MASTER;
    GRANT EXECUTE ON  SYS.DBMS_SYSTEM TO MASTER;
    GRANT SELECT ON  SYS.V_$SESSION TO MASTER;
    GRANT SELECT ON  TEL.ATSLOG TO MASTER;
    GRANT SELECT ON  TEL.GATSLOG TO MASTER;
    GRANT SELECT ON  TEL.KLS_COST TO MASTER;
    GRANT SELECT ON  TEL.KLS_DESTINATION TO MASTER;
    GRANT SELECT ON  TEL.KLS_GTSDESTINATION TO MASTER;
    GRANT SELECT ON  TEL.KLS_PHONES TO MASTER;


CREATE USER ISA
  IDENTIFIED BY VALUES '98C27A15A5CDAEF4'
  DEFAULT TABLESPACE USERS
  TEMPORARY TABLESPACE TEMP
  PROFILE DEFAULT
  ACCOUNT UNLOCK;
  -- 2 Roles for ISA 
  GRANT CONNECT TO ISA;
  GRANT RESOURCE TO ISA;
  ALTER USER ISA DEFAULT ROLE CONNECT;
  -- 1 System Privilege for ISA 
  GRANT UNLIMITED TABLESPACE TO ISA;


CREATE USER INFIN_PRED
  IDENTIFIED BY VALUES 'F5AF93AA1A1F6220'
  DEFAULT TABLESPACE USERS
  TEMPORARY TABLESPACE TEMP
  PROFILE DEFAULT
  ACCOUNT UNLOCK;
  -- 2 System Privileges for INFIN_PRED 
  GRANT SELECT ANY TABLE TO INFIN_PRED;
  GRANT UNLIMITED TABLESPACE TO INFIN_PRED;
  -- 1 Object Privilege for INFIN_PRED 
    GRANT EXECUTE ON  REPADMIN.GET_IND TO INFIN_PRED;


CREATE USER DOLGOBORODOV
  IDENTIFIED BY VALUES 'B6C3D12F0CEB0979'
  DEFAULT TABLESPACE USERS
  TEMPORARY TABLESPACE TEMP
  PROFILE DEFAULT
  ACCOUNT UNLOCK;
  -- 2 Roles for DOLGOBORODOV 
  GRANT CONNECT TO DOLGOBORODOV;
  GRANT RESOURCE TO DOLGOBORODOV;
  ALTER USER DOLGOBORODOV DEFAULT ROLE ALL;
  -- 4 System Privileges for DOLGOBORODOV 
  GRANT SELECT ANY TABLE TO DOLGOBORODOV;
  GRANT SELECT ANY SEQUENCE TO DOLGOBORODOV;
  GRANT UNLIMITED TABLESPACE TO DOLGOBORODOV;
  GRANT SELECT ANY DICTIONARY TO DOLGOBORODOV;
  -- 2 Tablespace Quotas for DOLGOBORODOV 
  ALTER USER DOLGOBORODOV QUOTA UNLIMITED ON USERS;
  ALTER USER DOLGOBORODOV QUOTA UNLIMITED ON TEMP;


CREATE USER ARCH_VEGA
  IDENTIFIED BY VALUES '9A6F8F4D14E2F68E'
  DEFAULT TABLESPACE USERS
  TEMPORARY TABLESPACE TEMP
  PROFILE DEFAULT
  ACCOUNT UNLOCK;
  -- 4 Roles for ARCH_VEGA 
  GRANT CONNECT TO ARCH_VEGA;
  GRANT RESOURCE TO ARCH_VEGA;
  GRANT EXP_FULL_DATABASE TO ARCH_VEGA;
  GRANT IMP_FULL_DATABASE TO ARCH_VEGA;
  ALTER USER ARCH_VEGA DEFAULT ROLE ALL;
  -- 1 System Privilege for ARCH_VEGA 
  GRANT UNLIMITED TABLESPACE TO ARCH_VEGA;
  -- 1 Tablespace Quota for ARCH_VEGA 
  ALTER USER ARCH_VEGA QUOTA UNLIMITED ON USERS;


CREATE USER TOAD
  IDENTIFIED BY VALUES '0502C8F4FDF08685'
  DEFAULT TABLESPACE TOOLS
  TEMPORARY TABLESPACE TEMP
  PROFILE DEFAULT
  ACCOUNT UNLOCK;
  -- 5 Roles for TOAD 
  GRANT CONNECT TO TOAD;
  GRANT RESOURCE TO TOAD;
  GRANT TC_LDR_ROLE TO TOAD WITH ADMIN OPTION;
  GRANT TC_MGR_ROLE TO TOAD WITH ADMIN OPTION;
  GRANT TC_ADMIN_ROLE TO TOAD WITH ADMIN OPTION;
  ALTER USER TOAD DEFAULT ROLE ALL;
  -- 6 System Privileges for TOAD 
  GRANT CREATE ROLE TO TOAD;
  GRANT DROP PUBLIC SYNONYM TO TOAD;
  GRANT UNLIMITED TABLESPACE TO TOAD;
  GRANT CREATE PUBLIC SYNONYM TO TOAD;
  GRANT EXECUTE ANY PROCEDURE TO TOAD;
  GRANT SELECT ANY DICTIONARY TO TOAD;
  -- 1 Tablespace Quota for TOAD 
  ALTER USER TOAD QUOTA UNLIMITED ON TOOLS;


CREATE USER SQLLAB
  IDENTIFIED BY VALUES 'B88FFC1AB8F31B8A'
  DEFAULT TABLESPACE TOOLS
  TEMPORARY TABLESPACE TEMP
  PROFILE DEFAULT
  ACCOUNT UNLOCK;
  -- 6 Roles for SQLLAB 
  GRANT DBA TO SQLLAB;
  GRANT CONNECT TO SQLLAB WITH ADMIN OPTION;
  GRANT RESOURCE TO SQLLAB WITH ADMIN OPTION;
  GRANT QUEST_SL_95_USER TO SQLLAB WITH ADMIN OPTION;
  GRANT QUEST_SLP_95_USER TO SQLLAB WITH ADMIN OPTION;
  GRANT QUEST_SPC_APP_PRIV TO SQLLAB WITH ADMIN OPTION;
  ALTER USER SQLLAB DEFAULT ROLE ALL;
  -- 32 System Privileges for SQLLAB 
  GRANT ALTER USER TO SQLLAB;
  GRANT ANALYZE ANY TO SQLLAB;
  GRANT CREATE ROLE TO SQLLAB;
  GRANT CREATE VIEW TO SQLLAB WITH ADMIN OPTION;
  GRANT ALTER SYSTEM TO SQLLAB WITH ADMIN OPTION;
  GRANT CREATE TABLE TO SQLLAB WITH ADMIN OPTION;
  GRANT ALTER SESSION TO SQLLAB;
  GRANT DROP ANY VIEW TO SQLLAB WITH ADMIN OPTION;
  GRANT DROP ANY INDEX TO SQLLAB;
  GRANT DROP ANY TABLE TO SQLLAB WITH ADMIN OPTION;
  GRANT LOCK ANY TABLE TO SQLLAB;
  GRANT ALTER ANY TABLE TO SQLLAB;
  GRANT ALTER TABLESPACE TO SQLLAB;
  GRANT CREATE ANY TABLE TO SQLLAB;
  GRANT CREATE PROCEDURE TO SQLLAB WITH ADMIN OPTION;
  GRANT DELETE ANY TABLE TO SQLLAB;
  GRANT DROP ANY SYNONYM TO SQLLAB WITH ADMIN OPTION;
  GRANT DROP ANY TRIGGER TO SQLLAB;
  GRANT INSERT ANY TABLE TO SQLLAB;
  GRANT SELECT ANY TABLE TO SQLLAB WITH ADMIN OPTION;
  GRANT UPDATE ANY TABLE TO SQLLAB;
  GRANT ALTER ANY TRIGGER TO SQLLAB;
  GRANT CREATE ANY SYNONYM TO SQLLAB WITH ADMIN OPTION;
  GRANT CREATE ANY TRIGGER TO SQLLAB;
  GRANT DROP ANY PROCEDURE TO SQLLAB WITH ADMIN OPTION;
  GRANT ALTER ANY PROCEDURE TO SQLLAB;
  GRANT DROP PUBLIC SYNONYM TO SQLLAB WITH ADMIN OPTION;
  GRANT CREATE ANY PROCEDURE TO SQLLAB;
  GRANT UNLIMITED TABLESPACE TO SQLLAB WITH ADMIN OPTION;
  GRANT CREATE PUBLIC SYNONYM TO SQLLAB WITH ADMIN OPTION;
  GRANT EXECUTE ANY PROCEDURE TO SQLLAB;
  GRANT SELECT ANY DICTIONARY TO SQLLAB WITH ADMIN OPTION;
  -- 1 Tablespace Quota for SQLLAB 
  ALTER USER SQLLAB QUOTA UNLIMITED ON TOOLS;
  -- 368 Object Privileges for SQLLAB 
    GRANT SELECT ON  SYS.CCOL$ TO SQLLAB;
    GRANT SELECT ON  SYS.CDEF$ TO SQLLAB;
    GRANT SELECT ON  SYS.COL$ TO SQLLAB;
    GRANT SELECT ON  SYS.CON$ TO SQLLAB;
    GRANT SELECT ON  SYS.DBA_CONS_COLUMNS TO SQLLAB;
    GRANT SELECT ON  SYS.DBA_DATA_FILES TO SQLLAB WITH GRANT OPTION;
    GRANT SELECT ON  SYS.DBA_EXTENTS TO SQLLAB WITH GRANT OPTION;
    GRANT SELECT ON  SYS.DBA_FREE_SPACE TO SQLLAB WITH GRANT OPTION;
    GRANT SELECT ON  SYS.DBA_INDEXES TO SQLLAB WITH GRANT OPTION;
    GRANT SELECT ON  SYS.DBA_IND_COLUMNS TO SQLLAB WITH GRANT OPTION;
    GRANT SELECT ON  SYS.DBA_JOBS TO SQLLAB WITH GRANT OPTION;
    GRANT SELECT ON  SYS.DBA_JOBS_RUNNING TO SQLLAB WITH GRANT OPTION;
    GRANT SELECT ON  SYS.DBA_OBJECTS TO SQLLAB WITH GRANT OPTION;
    GRANT SELECT ON  SYS.DBA_ROLE_PRIVS TO SQLLAB WITH GRANT OPTION;
    GRANT SELECT ON  SYS.DBA_ROLLBACK_SEGS TO SQLLAB;
    GRANT SELECT ON  SYS.DBA_SEGMENTS TO SQLLAB;
    GRANT SELECT ON  SYS.DBA_SEQUENCES TO SQLLAB;
    GRANT SELECT ON  SYS.DBA_TABLES TO SQLLAB;
    GRANT SELECT ON  SYS.DBA_TABLESPACES TO SQLLAB WITH GRANT OPTION;
    GRANT SELECT ON  SYS.DBA_TAB_COLUMNS TO SQLLAB WITH GRANT OPTION;
    GRANT SELECT ON  SYS.DBA_TAB_PRIVS TO SQLLAB WITH GRANT OPTION;
    GRANT SELECT ON  SYS.DBA_TEMP_FILES TO SQLLAB WITH GRANT OPTION;
    GRANT SELECT ON  SYS.DBA_USERS TO SQLLAB;
    GRANT EXECUTE ON  SYS.DBMS_IJOB TO SQLLAB;
    GRANT EXECUTE ON  SYS.DBMS_JOB TO SQLLAB WITH GRANT OPTION;
    GRANT EXECUTE ON  SYS.DBMS_LOCK TO SQLLAB;
    GRANT EXECUTE ON  SYS.DBMS_LOGMNR TO SQLLAB WITH GRANT OPTION;
    GRANT EXECUTE ON  SYS.DBMS_LOGMNR_D TO SQLLAB WITH GRANT OPTION;
    GRANT EXECUTE ON  SYS.DBMS_PIPE TO SQLLAB;
    GRANT EXECUTE ON  SYS.DBMS_REPAIR TO SQLLAB;
    GRANT EXECUTE ON  SYS.DBMS_SPACE TO SQLLAB WITH GRANT OPTION;
    GRANT EXECUTE ON  SYS.DBMS_SPACE_ADMIN TO SQLLAB;
    GRANT EXECUTE ON  SYS.DBMS_SYSTEM TO SQLLAB WITH GRANT OPTION;
    GRANT EXECUTE ON  SYS.DBMS_SYS_SQL TO SQLLAB;
    GRANT SELECT ON  SYS.DEPENDENCY$ TO SQLLAB WITH GRANT OPTION;
    GRANT SELECT ON  SYS.EXTERNAL_TAB$ TO SQLLAB;
    GRANT SELECT ON  SYS.FET$ TO SQLLAB WITH GRANT OPTION;
    GRANT SELECT ON  SYS.FILE$ TO SQLLAB WITH GRANT OPTION;
    GRANT SELECT ON  SYS.GV_$INSTANCE TO SQLLAB;
    GRANT SELECT ON  SYS.GV_$SYSSTAT TO SQLLAB;
    GRANT SELECT ON  SYS.HIST_HEAD$ TO SQLLAB;
    GRANT SELECT ON  SYS.ICOL$ TO SQLLAB;
    GRANT SELECT ON  SYS.IND$ TO SQLLAB;
    GRANT SELECT ON  SYS.OBJ$ TO SQLLAB WITH GRANT OPTION;
    GRANT SELECT ON  SYS.QUEST_SLP_DBA_CONSTRAINTS TO SQLLAB WITH GRANT OPTION;
    GRANT SELECT ON  SYS.QUEST_SLP_IND_COLUMNS TO SQLLAB WITH GRANT OPTION;
    GRANT SELECT ON  SYS.QUEST_SLP_TABLE_ROWS TO SQLLAB WITH GRANT OPTION;
    GRANT SELECT ON  SYS.QUEST_SLP_TAB_COLUMNS TO SQLLAB WITH GRANT OPTION;
    GRANT SELECT ON  SYS.QUEST_SL_ALL_JOBS TO SQLLAB WITH GRANT OPTION;
    GRANT SELECT ON  SYS.QUEST_SL_CONSTRAINTS TO SQLLAB WITH GRANT OPTION;
    GRANT SELECT ON  SYS.QUEST_SL_CONS_COLUMNS TO SQLLAB WITH GRANT OPTION;
    GRANT SELECT ON  SYS.QUEST_SL_DBA_CONSTRAINTS TO SQLLAB WITH GRANT OPTION;
    GRANT SELECT ON  SYS.QUEST_SL_DESCRIBE_DETAILS TO SQLLAB WITH GRANT OPTION;
    GRANT SELECT ON  SYS.QUEST_SL_FILE_SEGMENTS TO SQLLAB WITH GRANT OPTION;
    GRANT SELECT ON  SYS.QUEST_SL_FILE_TABLE_SEGMENTS TO SQLLAB WITH GRANT OPTION;
    GRANT SELECT ON  SYS.QUEST_SL_INDEXED_DEPENDENCIES TO SQLLAB WITH GRANT OPTION;
    GRANT SELECT ON  SYS.QUEST_SL_IND_COLUMNS TO SQLLAB WITH GRANT OPTION;
    GRANT SELECT ON  SYS.QUEST_SL_TABLES TO SQLLAB WITH GRANT OPTION;
    GRANT SELECT ON  SYS.QUEST_SL_TABLE_ROWS TO SQLLAB WITH GRANT OPTION;
    GRANT SELECT ON  SYS.QUEST_SL_TAB_COLUMNS TO SQLLAB WITH GRANT OPTION;
    GRANT SELECT ON  SYS.QUEST_SL_UET_ALL TO SQLLAB WITH GRANT OPTION;
    GRANT SELECT ON  SYS.QUEST_SL_UNINDEX_FOREIGN_KEYS TO SQLLAB WITH GRANT OPTION;
    GRANT SELECT ON  SYS.QUEST_SL_VIEW_DEPENDENCY TO SQLLAB WITH GRANT OPTION;
    GRANT SELECT ON  SYS.QUEST_SPC_X$KDXST TO SQLLAB;
    GRANT SELECT ON  SYS.QUEST_SPC_X$KTFBFE TO SQLLAB;
    GRANT SELECT ON  SYS.QUEST_SPC_X$KTFBHC TO SQLLAB;
    GRANT SELECT ON  SYS.QUEST_SPC_X$KTFBUE TO SQLLAB;
    GRANT SELECT ON  SYS.SEG$ TO SQLLAB WITH GRANT OPTION;
    GRANT SELECT ON  SYS.SEQ$ TO SQLLAB;
    GRANT SELECT ON  SYS.TAB$ TO SQLLAB;
    GRANT SELECT ON  SYS.TABPART$ TO SQLLAB;
    GRANT SELECT ON  SYS.TABSUBPART$ TO SQLLAB;
    GRANT SELECT ON  SYS.TS$ TO SQLLAB WITH GRANT OPTION;
    GRANT SELECT ON  SYS.UET$ TO SQLLAB WITH GRANT OPTION;
    GRANT SELECT ON  SYS.UNDO$ TO SQLLAB WITH GRANT OPTION;
    GRANT SELECT ON  SYS.USER$ TO SQLLAB WITH GRANT OPTION;
    GRANT SELECT ON  SYS.V_$ACCESS TO SQLLAB WITH GRANT OPTION;
    GRANT SELECT ON  SYS.V_$ACTIVE_INSTANCES TO SQLLAB WITH GRANT OPTION;
    GRANT SELECT ON  SYS.V_$ACTIVE_SESS_POOL_MTH TO SQLLAB WITH GRANT OPTION;
    GRANT SELECT ON  SYS.V_$AQ1 TO SQLLAB WITH GRANT OPTION;
    GRANT SELECT ON  SYS.V_$ARCHIVE TO SQLLAB WITH GRANT OPTION;
    GRANT SELECT ON  SYS.V_$ARCHIVED_LOG TO SQLLAB WITH GRANT OPTION;
    GRANT SELECT ON  SYS.V_$ARCHIVE_DEST TO SQLLAB WITH GRANT OPTION;
    GRANT SELECT ON  SYS.V_$ARCHIVE_DEST_STATUS TO SQLLAB WITH GRANT OPTION;
    GRANT SELECT ON  SYS.V_$ARCHIVE_GAP TO SQLLAB WITH GRANT OPTION;
    GRANT SELECT ON  SYS.V_$ARCHIVE_PROCESSES TO SQLLAB WITH GRANT OPTION;
    GRANT SELECT ON  SYS.V_$AW_CALC TO SQLLAB WITH GRANT OPTION;
    GRANT SELECT ON  SYS.V_$AW_OLAP TO SQLLAB WITH GRANT OPTION;
    GRANT SELECT ON  SYS.V_$AW_SESSION_INFO TO SQLLAB WITH GRANT OPTION;
    GRANT SELECT ON  SYS.V_$BACKUP TO SQLLAB WITH GRANT OPTION;
    GRANT SELECT ON  SYS.V_$BACKUP_ASYNC_IO TO SQLLAB WITH GRANT OPTION;
    GRANT SELECT ON  SYS.V_$BACKUP_CORRUPTION TO SQLLAB WITH GRANT OPTION;
    GRANT SELECT ON  SYS.V_$BACKUP_DATAFILE TO SQLLAB WITH GRANT OPTION;
    GRANT SELECT ON  SYS.V_$BACKUP_DEVICE TO SQLLAB WITH GRANT OPTION;
    GRANT SELECT ON  SYS.V_$BACKUP_PIECE TO SQLLAB WITH GRANT OPTION;
    GRANT SELECT ON  SYS.V_$BACKUP_REDOLOG TO SQLLAB WITH GRANT OPTION;
    GRANT SELECT ON  SYS.V_$BACKUP_SET TO SQLLAB WITH GRANT OPTION;
    GRANT SELECT ON  SYS.V_$BACKUP_SPFILE TO SQLLAB WITH GRANT OPTION;
    GRANT SELECT ON  SYS.V_$BACKUP_SYNC_IO TO SQLLAB WITH GRANT OPTION;
    GRANT SELECT ON  SYS.V_$BGPROCESS TO SQLLAB WITH GRANT OPTION;
    GRANT SELECT ON  SYS.V_$BH TO SQLLAB WITH GRANT OPTION;
    GRANT SELECT ON  SYS.V_$BSP TO SQLLAB WITH GRANT OPTION;
    GRANT SELECT ON  SYS.V_$BUFFER_POOL TO SQLLAB WITH GRANT OPTION;
    GRANT SELECT ON  SYS.V_$BUFFER_POOL_STATISTICS TO SQLLAB WITH GRANT OPTION;
    GRANT SELECT ON  SYS.V_$CIRCUIT TO SQLLAB WITH GRANT OPTION;
    GRANT SELECT ON  SYS.V_$CLASS_CACHE_TRANSFER TO SQLLAB WITH GRANT OPTION;
    GRANT SELECT ON  SYS.V_$CLASS_PING TO SQLLAB WITH GRANT OPTION;
    GRANT SELECT ON  SYS.V_$COMPATIBILITY TO SQLLAB WITH GRANT OPTION;
    GRANT SELECT ON  SYS.V_$COMPATSEG TO SQLLAB WITH GRANT OPTION;
    GRANT SELECT ON  SYS.V_$CONTEXT TO SQLLAB WITH GRANT OPTION;
    GRANT SELECT ON  SYS.V_$CONTROLFILE TO SQLLAB WITH GRANT OPTION;
    GRANT SELECT ON  SYS.V_$CONTROLFILE_RECORD_SECTION TO SQLLAB WITH GRANT OPTION;
    GRANT SELECT ON  SYS.V_$COPY_CORRUPTION TO SQLLAB WITH GRANT OPTION;
    GRANT SELECT ON  SYS.V_$CR_BLOCK_SERVER TO SQLLAB WITH GRANT OPTION;
    GRANT SELECT ON  SYS.V_$DATABASE TO SQLLAB WITH GRANT OPTION;
    GRANT SELECT ON  SYS.V_$DATABASE_BLOCK_CORRUPTION TO SQLLAB WITH GRANT OPTION;
    GRANT SELECT ON  SYS.V_$DATABASE_INCARNATION TO SQLLAB WITH GRANT OPTION;
    GRANT SELECT ON  SYS.V_$DATAFILE TO SQLLAB WITH GRANT OPTION;
    GRANT SELECT ON  SYS.V_$DATAFILE_COPY TO SQLLAB WITH GRANT OPTION;
    GRANT SELECT ON  SYS.V_$DATAFILE_HEADER TO SQLLAB WITH GRANT OPTION;
    GRANT SELECT ON  SYS.V_$DATAGUARD_STATUS TO SQLLAB WITH GRANT OPTION;
    GRANT SELECT ON  SYS.V_$DBFILE TO SQLLAB WITH GRANT OPTION;
    GRANT SELECT ON  SYS.V_$DBLINK TO SQLLAB WITH GRANT OPTION;
    GRANT SELECT ON  SYS.V_$DB_CACHE_ADVICE TO SQLLAB WITH GRANT OPTION;
    GRANT SELECT ON  SYS.V_$DB_OBJECT_CACHE TO SQLLAB WITH GRANT OPTION;
    GRANT SELECT ON  SYS.V_$DB_PIPES TO SQLLAB WITH GRANT OPTION;
    GRANT SELECT ON  SYS.V_$DELETED_OBJECT TO SQLLAB WITH GRANT OPTION;
    GRANT SELECT ON  SYS.V_$DISPATCHER TO SQLLAB WITH GRANT OPTION;
    GRANT SELECT ON  SYS.V_$DISPATCHER_RATE TO SQLLAB WITH GRANT OPTION;
    GRANT SELECT ON  SYS.V_$DLM_ALL_LOCKS TO SQLLAB WITH GRANT OPTION;
    GRANT SELECT ON  SYS.V_$DLM_CONVERT_LOCAL TO SQLLAB WITH GRANT OPTION;
    GRANT SELECT ON  SYS.V_$DLM_CONVERT_REMOTE TO SQLLAB WITH GRANT OPTION;
    GRANT SELECT ON  SYS.V_$DLM_LATCH TO SQLLAB WITH GRANT OPTION;
    GRANT SELECT ON  SYS.V_$DLM_LOCKS TO SQLLAB WITH GRANT OPTION;
    GRANT SELECT ON  SYS.V_$DLM_MISC TO SQLLAB WITH GRANT OPTION;
    GRANT SELECT ON  SYS.V_$DLM_RESS TO SQLLAB WITH GRANT OPTION;
    GRANT SELECT ON  SYS.V_$DLM_TRAFFIC_CONTROLLER TO SQLLAB WITH GRANT OPTION;
    GRANT SELECT ON  SYS.V_$ENABLEDPRIVS TO SQLLAB WITH GRANT OPTION;
    GRANT SELECT ON  SYS.V_$ENQUEUE_LOCK TO SQLLAB WITH GRANT OPTION;
    GRANT SELECT ON  SYS.V_$ENQUEUE_STAT TO SQLLAB WITH GRANT OPTION;
    GRANT SELECT ON  SYS.V_$EVENT_NAME TO SQLLAB WITH GRANT OPTION;
    GRANT SELECT ON  SYS.V_$EXECUTION TO SQLLAB WITH GRANT OPTION;
    GRANT SELECT ON  SYS.V_$FAST_START_SERVERS TO SQLLAB WITH GRANT OPTION;
    GRANT SELECT ON  SYS.V_$FAST_START_TRANSACTIONS TO SQLLAB WITH GRANT OPTION;
    GRANT SELECT ON  SYS.V_$FILESTAT TO SQLLAB WITH GRANT OPTION;
    GRANT SELECT ON  SYS.V_$FILE_CACHE_TRANSFER TO SQLLAB WITH GRANT OPTION;
    GRANT SELECT ON  SYS.V_$FILE_PING TO SQLLAB WITH GRANT OPTION;
    GRANT SELECT ON  SYS.V_$FIXED_TABLE TO SQLLAB WITH GRANT OPTION;
    GRANT SELECT ON  SYS.V_$FIXED_VIEW_DEFINITION TO SQLLAB WITH GRANT OPTION;
    GRANT SELECT ON  SYS.V_$GCSHVMASTER_INFO TO SQLLAB WITH GRANT OPTION;
    GRANT SELECT ON  SYS.V_$GCSPFMASTER_INFO TO SQLLAB WITH GRANT OPTION;
    GRANT SELECT ON  SYS.V_$GC_ELEMENT TO SQLLAB WITH GRANT OPTION;
    GRANT SELECT ON  SYS.V_$GC_ELEMENTS_WITH_COLLISIONS TO SQLLAB WITH GRANT OPTION;
    GRANT SELECT ON  SYS.V_$GES_BLOCKING_ENQUEUE TO SQLLAB WITH GRANT OPTION;
    GRANT SELECT ON  SYS.V_$GES_ENQUEUE TO SQLLAB WITH GRANT OPTION;
    GRANT SELECT ON  SYS.V_$GLOBALCONTEXT TO SQLLAB WITH GRANT OPTION;
    GRANT SELECT ON  SYS.V_$GLOBAL_BLOCKED_LOCKS TO SQLLAB WITH GRANT OPTION;
    GRANT SELECT ON  SYS.V_$GLOBAL_TRANSACTION TO SQLLAB WITH GRANT OPTION;
    GRANT SELECT ON  SYS.V_$HS_AGENT TO SQLLAB WITH GRANT OPTION;
    GRANT SELECT ON  SYS.V_$HS_PARAMETER TO SQLLAB WITH GRANT OPTION;
    GRANT SELECT ON  SYS.V_$HS_SESSION TO SQLLAB WITH GRANT OPTION;
    GRANT SELECT ON  SYS.V_$HVMASTER_INFO TO SQLLAB WITH GRANT OPTION;
    GRANT SELECT ON  SYS.V_$INDEXED_FIXED_COLUMN TO SQLLAB WITH GRANT OPTION;
    GRANT SELECT ON  SYS.V_$INSTANCE TO SQLLAB WITH GRANT OPTION;
    GRANT SELECT ON  SYS.V_$INSTANCE_RECOVERY TO SQLLAB WITH GRANT OPTION;
    GRANT SELECT ON  SYS.V_$LATCH TO SQLLAB WITH GRANT OPTION;
    GRANT SELECT ON  SYS.V_$LATCHHOLDER TO SQLLAB WITH GRANT OPTION;
    GRANT SELECT ON  SYS.V_$LATCHNAME TO SQLLAB WITH GRANT OPTION;
    GRANT SELECT ON  SYS.V_$LATCH_CHILDREN TO SQLLAB WITH GRANT OPTION;
    GRANT SELECT ON  SYS.V_$LATCH_MISSES TO SQLLAB WITH GRANT OPTION;
    GRANT SELECT ON  SYS.V_$LATCH_PARENT TO SQLLAB WITH GRANT OPTION;
    GRANT SELECT ON  SYS.V_$LIBRARYCACHE TO SQLLAB WITH GRANT OPTION;
    GRANT SELECT ON  SYS.V_$LIBRARY_CACHE_MEMORY TO SQLLAB WITH GRANT OPTION;
    GRANT SELECT ON  SYS.V_$LICENSE TO SQLLAB WITH GRANT OPTION;
    GRANT SELECT ON  SYS.V_$LOADISTAT TO SQLLAB WITH GRANT OPTION;
    GRANT SELECT ON  SYS.V_$LOADPSTAT TO SQLLAB WITH GRANT OPTION;
    GRANT SELECT ON  SYS.V_$LOCK TO SQLLAB WITH GRANT OPTION;
    GRANT SELECT ON  SYS.V_$LOCKED_OBJECT TO SQLLAB WITH GRANT OPTION;
    GRANT SELECT ON  SYS.V_$LOCKS_WITH_COLLISIONS TO SQLLAB WITH GRANT OPTION;
    GRANT SELECT ON  SYS.V_$LOCK_ACTIVITY TO SQLLAB WITH GRANT OPTION;
    GRANT SELECT ON  SYS.V_$LOCK_ELEMENT TO SQLLAB WITH GRANT OPTION;
    GRANT SELECT ON  SYS.V_$LOG TO SQLLAB WITH GRANT OPTION;
    GRANT SELECT ON  SYS.V_$LOGFILE TO SQLLAB WITH GRANT OPTION;
    GRANT SELECT ON  SYS.V_$LOGHIST TO SQLLAB WITH GRANT OPTION;
    GRANT SELECT ON  SYS.V_$LOGMNR_CALLBACK TO SQLLAB WITH GRANT OPTION;
    GRANT SELECT ON  SYS.V_$LOGMNR_CONTENTS TO SQLLAB WITH GRANT OPTION;
    GRANT SELECT ON  SYS.V_$LOGMNR_DICTIONARY TO SQLLAB WITH GRANT OPTION;
    GRANT SELECT ON  SYS.V_$LOGMNR_LOGFILE TO SQLLAB WITH GRANT OPTION;
    GRANT SELECT ON  SYS.V_$LOGMNR_LOGS TO SQLLAB WITH GRANT OPTION;
    GRANT SELECT ON  SYS.V_$LOGMNR_PARAMETERS TO SQLLAB WITH GRANT OPTION;
    GRANT SELECT ON  SYS.V_$LOGMNR_PROCESS TO SQLLAB WITH GRANT OPTION;
    GRANT SELECT ON  SYS.V_$LOGMNR_REGION TO SQLLAB WITH GRANT OPTION;
    GRANT SELECT ON  SYS.V_$LOGMNR_SESSION TO SQLLAB WITH GRANT OPTION;
    GRANT SELECT ON  SYS.V_$LOGMNR_STATS TO SQLLAB WITH GRANT OPTION;
    GRANT SELECT ON  SYS.V_$LOGMNR_TRANSACTION TO SQLLAB WITH GRANT OPTION;
    GRANT SELECT ON  SYS.V_$LOGSTDBY TO SQLLAB WITH GRANT OPTION;
    GRANT SELECT ON  SYS.V_$LOGSTDBY_STATS TO SQLLAB WITH GRANT OPTION;
    GRANT SELECT ON  SYS.V_$LOG_HISTORY TO SQLLAB WITH GRANT OPTION;
    GRANT SELECT ON  SYS.V_$MANAGED_STANDBY TO SQLLAB WITH GRANT OPTION;
    GRANT SELECT ON  SYS.V_$MAP_COMP_LIST TO SQLLAB WITH GRANT OPTION;
    GRANT SELECT ON  SYS.V_$MAP_ELEMENT TO SQLLAB WITH GRANT OPTION;
    GRANT SELECT ON  SYS.V_$MAP_EXT_ELEMENT TO SQLLAB WITH GRANT OPTION;
    GRANT SELECT ON  SYS.V_$MAP_FILE TO SQLLAB WITH GRANT OPTION;
    GRANT SELECT ON  SYS.V_$MAP_FILE_EXTENT TO SQLLAB WITH GRANT OPTION;
    GRANT SELECT ON  SYS.V_$MAP_FILE_IO_STACK TO SQLLAB WITH GRANT OPTION;
    GRANT SELECT ON  SYS.V_$MAP_LIBRARY TO SQLLAB WITH GRANT OPTION;
    GRANT SELECT ON  SYS.V_$MAP_SUBELEMENT TO SQLLAB WITH GRANT OPTION;
    GRANT SELECT ON  SYS.V_$MAX_ACTIVE_SESS_TARGET_MTH TO SQLLAB WITH GRANT OPTION;
    GRANT SELECT ON  SYS.V_$MTTR_TARGET_ADVICE TO SQLLAB WITH GRANT OPTION;
    GRANT SELECT ON  SYS.V_$MVREFRESH TO SQLLAB WITH GRANT OPTION;
    GRANT SELECT ON  SYS.V_$MYSTAT TO SQLLAB WITH GRANT OPTION;
    GRANT SELECT ON  SYS.V_$NLS_PARAMETERS TO SQLLAB WITH GRANT OPTION;
    GRANT SELECT ON  SYS.V_$NLS_VALID_VALUES TO SQLLAB WITH GRANT OPTION;
    GRANT SELECT ON  SYS.V_$OBJECT_DEPENDENCY TO SQLLAB WITH GRANT OPTION;
    GRANT SELECT ON  SYS.V_$OBSOLETE_PARAMETER TO SQLLAB WITH GRANT OPTION;
    GRANT SELECT ON  SYS.V_$OFFLINE_RANGE TO SQLLAB WITH GRANT OPTION;
    GRANT SELECT ON  SYS.V_$OPEN_CURSOR TO SQLLAB WITH GRANT OPTION;
    GRANT SELECT ON  SYS.V_$OPTION TO SQLLAB WITH GRANT OPTION;
    GRANT SELECT ON  SYS.V_$PARALLEL_DEGREE_LIMIT_MTH TO SQLLAB WITH GRANT OPTION;
    GRANT SELECT ON  SYS.V_$PARAMETER TO SQLLAB WITH GRANT OPTION;
    GRANT SELECT ON  SYS.V_$PARAMETER2 TO SQLLAB WITH GRANT OPTION;
    GRANT SELECT ON  SYS.V_$PGASTAT TO SQLLAB WITH GRANT OPTION;
    GRANT SELECT ON  SYS.V_$PGA_TARGET_ADVICE TO SQLLAB WITH GRANT OPTION;
    GRANT SELECT ON  SYS.V_$PGA_TARGET_ADVICE_HISTOGRAM TO SQLLAB WITH GRANT OPTION;
    GRANT SELECT ON  SYS.V_$PQ_SESSTAT TO SQLLAB WITH GRANT OPTION;
    GRANT SELECT ON  SYS.V_$PQ_SLAVE TO SQLLAB WITH GRANT OPTION;
    GRANT SELECT ON  SYS.V_$PQ_SYSSTAT TO SQLLAB WITH GRANT OPTION;
    GRANT SELECT ON  SYS.V_$PQ_TQSTAT TO SQLLAB WITH GRANT OPTION;
    GRANT SELECT ON  SYS.V_$PROCESS TO SQLLAB WITH GRANT OPTION;
    GRANT SELECT ON  SYS.V_$PROXY_ARCHIVEDLOG TO SQLLAB WITH GRANT OPTION;
    GRANT SELECT ON  SYS.V_$PROXY_DATAFILE TO SQLLAB WITH GRANT OPTION;
    GRANT SELECT ON  SYS.V_$PWFILE_USERS TO SQLLAB WITH GRANT OPTION;
    GRANT SELECT ON  SYS.V_$PX_PROCESS TO SQLLAB WITH GRANT OPTION;
    GRANT SELECT ON  SYS.V_$PX_PROCESS_SYSSTAT TO SQLLAB WITH GRANT OPTION;
    GRANT SELECT ON  SYS.V_$PX_SESSION TO SQLLAB WITH GRANT OPTION;
    GRANT SELECT ON  SYS.V_$PX_SESSTAT TO SQLLAB WITH GRANT OPTION;
    GRANT SELECT ON  SYS.V_$QUEST_SLP_SQLAREA TO SQLLAB WITH GRANT OPTION;
    GRANT SELECT ON  SYS.V_$QUEUE TO SQLLAB WITH GRANT OPTION;
    GRANT SELECT ON  SYS.V_$QUEUEING_MTH TO SQLLAB WITH GRANT OPTION;
    GRANT SELECT ON  SYS.V_$RECOVERY_FILE_STATUS TO SQLLAB WITH GRANT OPTION;
    GRANT SELECT ON  SYS.V_$RECOVERY_LOG TO SQLLAB WITH GRANT OPTION;
    GRANT SELECT ON  SYS.V_$RECOVERY_PROGRESS TO SQLLAB WITH GRANT OPTION;
    GRANT SELECT ON  SYS.V_$RECOVERY_STATUS TO SQLLAB WITH GRANT OPTION;
    GRANT SELECT ON  SYS.V_$RECOVER_FILE TO SQLLAB WITH GRANT OPTION;
    GRANT SELECT ON  SYS.V_$REPLPROP TO SQLLAB WITH GRANT OPTION;
    GRANT SELECT ON  SYS.V_$REPLQUEUE TO SQLLAB WITH GRANT OPTION;
    GRANT SELECT ON  SYS.V_$REQDIST TO SQLLAB WITH GRANT OPTION;
    GRANT SELECT ON  SYS.V_$RESERVED_WORDS TO SQLLAB WITH GRANT OPTION;
    GRANT SELECT ON  SYS.V_$RESOURCE TO SQLLAB WITH GRANT OPTION;
    GRANT SELECT ON  SYS.V_$RESOURCE_LIMIT TO SQLLAB WITH GRANT OPTION;
    GRANT SELECT ON  SYS.V_$RESUMABLE TO SQLLAB WITH GRANT OPTION;
    GRANT SELECT ON  SYS.V_$RMAN_CONFIGURATION TO SQLLAB WITH GRANT OPTION;
    GRANT SELECT ON  SYS.V_$ROLLNAME TO SQLLAB WITH GRANT OPTION;
    GRANT SELECT ON  SYS.V_$ROLLSTAT TO SQLLAB WITH GRANT OPTION;
    GRANT SELECT ON  SYS.V_$ROWCACHE TO SQLLAB WITH GRANT OPTION;
    GRANT SELECT ON  SYS.V_$ROWCACHE_PARENT TO SQLLAB WITH GRANT OPTION;
    GRANT SELECT ON  SYS.V_$ROWCACHE_SUBORDINATE TO SQLLAB WITH GRANT OPTION;
    GRANT SELECT ON  SYS.V_$RSRC_CONSUMER_GROUP TO SQLLAB WITH GRANT OPTION;
    GRANT SELECT ON  SYS.V_$RSRC_CONSUMER_GROUP_CPU_MTH TO SQLLAB WITH GRANT OPTION;
    GRANT SELECT ON  SYS.V_$RSRC_PLAN TO SQLLAB WITH GRANT OPTION;
    GRANT SELECT ON  SYS.V_$RSRC_PLAN_CPU_MTH TO SQLLAB WITH GRANT OPTION;
    GRANT SELECT ON  SYS.V_$SEGMENT_STATISTICS TO SQLLAB WITH GRANT OPTION;
    GRANT SELECT ON  SYS.V_$SEGSTAT TO SQLLAB WITH GRANT OPTION;
    GRANT SELECT ON  SYS.V_$SEGSTAT_NAME TO SQLLAB WITH GRANT OPTION;
    GRANT SELECT ON  SYS.V_$SESSION TO SQLLAB WITH GRANT OPTION;
    GRANT SELECT ON  SYS.V_$SESSION_CONNECT_INFO TO SQLLAB WITH GRANT OPTION;
    GRANT SELECT ON  SYS.V_$SESSION_CURSOR_CACHE TO SQLLAB WITH GRANT OPTION;
    GRANT SELECT ON  SYS.V_$SESSION_EVENT TO SQLLAB WITH GRANT OPTION;
    GRANT SELECT ON  SYS.V_$SESSION_LONGOPS TO SQLLAB WITH GRANT OPTION;
    GRANT SELECT ON  SYS.V_$SESSION_OBJECT_CACHE TO SQLLAB WITH GRANT OPTION;
    GRANT SELECT ON  SYS.V_$SESSION_WAIT TO SQLLAB WITH GRANT OPTION;
    GRANT SELECT ON  SYS.V_$SESSTAT TO SQLLAB WITH GRANT OPTION;
    GRANT SELECT ON  SYS.V_$SESS_IO TO SQLLAB WITH GRANT OPTION;
    GRANT SELECT ON  SYS.V_$SGA TO SQLLAB WITH GRANT OPTION;
    GRANT SELECT ON  SYS.V_$SGASTAT TO SQLLAB WITH GRANT OPTION;
    GRANT SELECT ON  SYS.V_$SGA_CURRENT_RESIZE_OPS TO SQLLAB WITH GRANT OPTION;
    GRANT SELECT ON  SYS.V_$SGA_DYNAMIC_COMPONENTS TO SQLLAB WITH GRANT OPTION;
    GRANT SELECT ON  SYS.V_$SGA_DYNAMIC_FREE_MEMORY TO SQLLAB WITH GRANT OPTION;
    GRANT SELECT ON  SYS.V_$SGA_RESIZE_OPS TO SQLLAB WITH GRANT OPTION;
    GRANT SELECT ON  SYS.V_$SHARED_POOL_ADVICE TO SQLLAB WITH GRANT OPTION;
    GRANT SELECT ON  SYS.V_$SHARED_POOL_RESERVED TO SQLLAB WITH GRANT OPTION;
    GRANT SELECT ON  SYS.V_$SHARED_SERVER TO SQLLAB WITH GRANT OPTION;
    GRANT SELECT ON  SYS.V_$SHARED_SERVER_MONITOR TO SQLLAB WITH GRANT OPTION;
    GRANT SELECT ON  SYS.V_$SORT_SEGMENT TO SQLLAB WITH GRANT OPTION;
    GRANT SELECT ON  SYS.V_$SORT_USAGE TO SQLLAB WITH GRANT OPTION;
    GRANT SELECT ON  SYS.V_$SPPARAMETER TO SQLLAB WITH GRANT OPTION;
    GRANT SELECT ON  SYS.V_$SQL TO SQLLAB WITH GRANT OPTION;
    GRANT SELECT ON  SYS.V_$SQLAB_FILE TO SQLLAB WITH GRANT OPTION;
    GRANT SELECT ON  SYS.V_$SQLAB_OBJECT TO SQLLAB WITH GRANT OPTION;
    GRANT SELECT ON  SYS.V_$SQLAB_PLAN_VIEW TO SQLLAB WITH GRANT OPTION;
    GRANT SELECT ON  SYS.V_$SQLAB_SESSION TO SQLLAB WITH GRANT OPTION;
    GRANT SELECT ON  SYS.V_$SQLAB_SQLAREA TO SQLLAB WITH GRANT OPTION;
    GRANT SELECT ON  SYS.V_$SQLAB_SQL_ACTIVITY TO SQLLAB WITH GRANT OPTION;
    GRANT SELECT ON  SYS.V_$SQLAREA TO SQLLAB WITH GRANT OPTION;
    GRANT SELECT ON  SYS.V_$SQLTEXT TO SQLLAB WITH GRANT OPTION;
    GRANT SELECT ON  SYS.V_$SQLTEXT_WITH_NEWLINES TO SQLLAB WITH GRANT OPTION;
    GRANT SELECT ON  SYS.V_$SQL_BIND_DATA TO SQLLAB WITH GRANT OPTION;
    GRANT SELECT ON  SYS.V_$SQL_BIND_METADATA TO SQLLAB WITH GRANT OPTION;
    GRANT SELECT ON  SYS.V_$SQL_CURSOR TO SQLLAB WITH GRANT OPTION;
    GRANT SELECT ON  SYS.V_$SQL_PLAN TO SQLLAB WITH GRANT OPTION;
    GRANT SELECT ON  SYS.V_$SQL_PLAN_STATISTICS TO SQLLAB WITH GRANT OPTION;
    GRANT SELECT ON  SYS.V_$SQL_PLAN_STATISTICS_ALL TO SQLLAB WITH GRANT OPTION;
    GRANT SELECT ON  SYS.V_$SQL_REDIRECTION TO SQLLAB WITH GRANT OPTION;
    GRANT SELECT ON  SYS.V_$SQL_SHARED_CURSOR TO SQLLAB WITH GRANT OPTION;
    GRANT SELECT ON  SYS.V_$SQL_SHARED_MEMORY TO SQLLAB WITH GRANT OPTION;
    GRANT SELECT ON  SYS.V_$SQL_WORKAREA TO SQLLAB WITH GRANT OPTION;
    GRANT SELECT ON  SYS.V_$SQL_WORKAREA_ACTIVE TO SQLLAB WITH GRANT OPTION;
    GRANT SELECT ON  SYS.V_$SQL_WORKAREA_HISTOGRAM TO SQLLAB WITH GRANT OPTION;
    GRANT SELECT ON  SYS.V_$STANDBY_LOG TO SQLLAB WITH GRANT OPTION;
    GRANT SELECT ON  SYS.V_$STATISTICS_LEVEL TO SQLLAB WITH GRANT OPTION;
    GRANT SELECT ON  SYS.V_$STATNAME TO SQLLAB WITH GRANT OPTION;
    GRANT SELECT ON  SYS.V_$STREAMS_APPLY_COORDINATOR TO SQLLAB WITH GRANT OPTION;
    GRANT SELECT ON  SYS.V_$STREAMS_APPLY_READER TO SQLLAB WITH GRANT OPTION;
    GRANT SELECT ON  SYS.V_$STREAMS_APPLY_SERVER TO SQLLAB WITH GRANT OPTION;
    GRANT SELECT ON  SYS.V_$STREAMS_CAPTURE TO SQLLAB WITH GRANT OPTION;
    GRANT SELECT ON  SYS.V_$SUBCACHE TO SQLLAB WITH GRANT OPTION;
    GRANT SELECT ON  SYS.V_$SYSSTAT TO SQLLAB WITH GRANT OPTION;
    GRANT SELECT ON  SYS.V_$SYSTEM_CURSOR_CACHE TO SQLLAB WITH GRANT OPTION;
    GRANT SELECT ON  SYS.V_$SYSTEM_EVENT TO SQLLAB WITH GRANT OPTION;
    GRANT SELECT ON  SYS.V_$SYSTEM_PARAMETER TO SQLLAB WITH GRANT OPTION;
    GRANT SELECT ON  SYS.V_$SYSTEM_PARAMETER2 TO SQLLAB WITH GRANT OPTION;
    GRANT SELECT ON  SYS.V_$TABLESPACE TO SQLLAB WITH GRANT OPTION;
    GRANT SELECT ON  SYS.V_$TEMPFILE TO SQLLAB WITH GRANT OPTION;
    GRANT SELECT ON  SYS.V_$TEMPORARY_LOBS TO SQLLAB WITH GRANT OPTION;
    GRANT SELECT ON  SYS.V_$TEMPSTAT TO SQLLAB WITH GRANT OPTION;
    GRANT SELECT ON  SYS.V_$TEMP_CACHE_TRANSFER TO SQLLAB WITH GRANT OPTION;
    GRANT SELECT ON  SYS.V_$TEMP_EXTENT_MAP TO SQLLAB WITH GRANT OPTION;
    GRANT SELECT ON  SYS.V_$TEMP_EXTENT_POOL TO SQLLAB WITH GRANT OPTION;
    GRANT SELECT ON  SYS.V_$TEMP_PING TO SQLLAB WITH GRANT OPTION;
    GRANT SELECT ON  SYS.V_$TEMP_SPACE_HEADER TO SQLLAB WITH GRANT OPTION;
    GRANT SELECT ON  SYS.V_$THREAD TO SQLLAB WITH GRANT OPTION;
    GRANT SELECT ON  SYS.V_$TIMER TO SQLLAB WITH GRANT OPTION;
    GRANT SELECT ON  SYS.V_$TIMEZONE_NAMES TO SQLLAB WITH GRANT OPTION;
    GRANT SELECT ON  SYS.V_$TRANSACTION TO SQLLAB WITH GRANT OPTION;
    GRANT SELECT ON  SYS.V_$TRANSACTION_ENQUEUE TO SQLLAB WITH GRANT OPTION;
    GRANT SELECT ON  SYS.V_$TYPE_SIZE TO SQLLAB WITH GRANT OPTION;
    GRANT SELECT ON  SYS.V_$UNDOSTAT TO SQLLAB WITH GRANT OPTION;
    GRANT SELECT ON  SYS.V_$VERSION TO SQLLAB WITH GRANT OPTION;
    GRANT SELECT ON  SYS.V_$VPD_POLICY TO SQLLAB WITH GRANT OPTION;
    GRANT SELECT ON  SYS.V_$WAITSTAT TO SQLLAB WITH GRANT OPTION;
    GRANT SELECT ON  SYS.V_$_LOCK TO SQLLAB WITH GRANT OPTION;
    GRANT SELECT ON  SYS.V_$_LOCK1 TO SQLLAB WITH GRANT OPTION;
    GRANT SELECT ON  SYS.V_$_SEQUENCES TO SQLLAB WITH GRANT OPTION;
    GRANT SELECT ON  SYS.X_$BH TO SQLLAB WITH GRANT OPTION;
    GRANT SELECT ON  SYS.X_$KCBFWAIT TO SQLLAB WITH GRANT OPTION;
    GRANT SELECT ON  SYS.X_$KCBWBPD TO SQLLAB WITH GRANT OPTION;
    GRANT SELECT ON  SYS.X_$KCBWDS TO SQLLAB WITH GRANT OPTION;
    GRANT SELECT ON  SYS.X_$KGLCURSOR TO SQLLAB;
    GRANT SELECT ON  SYS.X_$KSBDP TO SQLLAB WITH GRANT OPTION;
    GRANT SELECT ON  SYS.X_$KSLED TO SQLLAB WITH GRANT OPTION;
    GRANT SELECT ON  SYS.X_$KSLEI TO SQLLAB WITH GRANT OPTION;
    GRANT SELECT ON  SYS.X_$KSLES TO SQLLAB WITH GRANT OPTION;
    GRANT SELECT ON  SYS.X_$KSLLD TO SQLLAB WITH GRANT OPTION;
    GRANT SELECT ON  SYS.X_$KSLLT TO SQLLAB WITH GRANT OPTION;
    GRANT SELECT ON  SYS.X_$KSMLRU TO SQLLAB WITH GRANT OPTION;
    GRANT SELECT ON  SYS.X_$KSMSP TO SQLLAB WITH GRANT OPTION;
    GRANT SELECT ON  SYS.X_$KSMSS TO SQLLAB;
    GRANT SELECT ON  SYS.X_$KSPPCV TO SQLLAB WITH GRANT OPTION;
    GRANT SELECT ON  SYS.X_$KSPPI TO SQLLAB WITH GRANT OPTION;
    GRANT SELECT ON  SYS.X_$KSQRS TO SQLLAB WITH GRANT OPTION;
    GRANT SELECT ON  SYS.X_$KSQST TO SQLLAB WITH GRANT OPTION;
    GRANT SELECT ON  SYS.X_$KSUSE TO SQLLAB;
    GRANT SELECT ON  SYS.X_$KSUSECST TO SQLLAB WITH GRANT OPTION;
    GRANT SELECT ON  SYS.X_$KSUSESTA TO SQLLAB WITH GRANT OPTION;
    GRANT SELECT ON  SYS.X_$KTCXB TO SQLLAB;
    GRANT SELECT ON  SYS.X_$KTFBFE TO SQLLAB WITH GRANT OPTION;
    GRANT SELECT ON  SYS.X_$KTFBHC TO SQLLAB WITH GRANT OPTION;
    GRANT SELECT ON  SYS.X_$KTFBUE TO SQLLAB WITH GRANT OPTION;


CREATE USER TEL
  IDENTIFIED BY VALUES '44AA3AA5F37EB553'
  DEFAULT TABLESPACE LOADER
  TEMPORARY TABLESPACE TEMP
  PROFILE DEFAULT
  ACCOUNT UNLOCK;
  -- 2 Roles for TEL 
  GRANT CONNECT TO TEL;
  GRANT RESOURCE TO TEL;
  ALTER USER TEL DEFAULT ROLE ALL;
  -- 1 System Privilege for TEL 
  GRANT UNLIMITED TABLESPACE TO TEL;
  -- 2 Tablespace Quotas for TEL 
  ALTER USER TEL QUOTA UNLIMITED ON LOADER;
  ALTER USER TEL QUOTA UNLIMITED ON USERS;


CREATE USER REPL
  IDENTIFIED BY VALUES '1E7DAE850C6549B3'
  DEFAULT TABLESPACE LOADER
  TEMPORARY TABLESPACE TEMP
  PROFILE DEFAULT
  ACCOUNT UNLOCK;
  -- 3 Roles for REPL 
  GRANT CONNECT TO REPL;
  GRANT RESOURCE TO REPL;
  GRANT IMP_FULL_DATABASE TO REPL;
  ALTER USER REPL DEFAULT ROLE ALL;
  -- 1 System Privilege for REPL 
  GRANT UNLIMITED TABLESPACE TO REPL;
  -- 2 Tablespace Quotas for REPL 
  ALTER USER REPL QUOTA UNLIMITED ON LOADER;
  ALTER USER REPL QUOTA UNLIMITED ON USERS;


CREATE USER MASTER_SHADOW
  IDENTIFIED BY VALUES '7585B857DDDFBF0B'
  DEFAULT TABLESPACE LOADER
  TEMPORARY TABLESPACE TEMP
  PROFILE DEFAULT
  ACCOUNT UNLOCK;
  -- 2 Roles for MASTER_SHADOW 
  GRANT CONNECT TO MASTER_SHADOW;
  GRANT RESOURCE TO MASTER_SHADOW;
  ALTER USER MASTER_SHADOW DEFAULT ROLE ALL;
  -- 1 System Privilege for MASTER_SHADOW 
  GRANT UNLIMITED TABLESPACE TO MASTER_SHADOW;


CREATE USER LOAD_BUFFER
  IDENTIFIED BY VALUES '4EF8C4F721C58EDF'
  DEFAULT TABLESPACE LOADER
  TEMPORARY TABLESPACE TEMP
  PROFILE DEFAULT
  ACCOUNT UNLOCK;
  -- 2 Roles for LOAD_BUFFER 
  GRANT CONNECT TO LOAD_BUFFER;
  GRANT RESOURCE TO LOAD_BUFFER;
  ALTER USER LOAD_BUFFER DEFAULT ROLE ALL;
  -- 2 System Privileges for LOAD_BUFFER 
  GRANT CREATE SNAPSHOT TO LOAD_BUFFER;
  GRANT UNLIMITED TABLESPACE TO LOAD_BUFFER;
  -- 4 Object Privileges for LOAD_BUFFER 
    GRANT SELECT ON  MASTER.DOP_KVIT TO LOAD_BUFFER WITH GRANT OPTION;
    GRANT SELECT ON  MASTER.KVIT TO LOAD_BUFFER WITH GRANT OPTION;
    GRANT SELECT ON  MASTER.V_KVIT_ALL TO LOAD_BUFFER WITH GRANT OPTION;
    GRANT SELECT ON  SYS.V_$SESSION TO LOAD_BUFFER;


CREATE USER LIDER
  IDENTIFIED BY VALUES '0172EA30515FCED4'
  DEFAULT TABLESPACE LOADER
  TEMPORARY TABLESPACE TEMP
  PROFILE DEFAULT
  ACCOUNT UNLOCK;
  -- 3 Roles for LIDER 
  GRANT CONNECT TO LIDER;
  GRANT RESOURCE TO LIDER;
  GRANT IMP_FULL_DATABASE TO LIDER;
  ALTER USER LIDER DEFAULT ROLE ALL;
  -- 1 System Privilege for LIDER 
  GRANT UNLIMITED TABLESPACE TO LIDER;
  -- 2 Tablespace Quotas for LIDER 
  ALTER USER LIDER QUOTA UNLIMITED ON LOADER;
  ALTER USER LIDER QUOTA UNLIMITED ON USERS;


CREATE USER UE
  IDENTIFIED BY VALUES '85F47927FC119FF4'
  DEFAULT TABLESPACE FORS
  TEMPORARY TABLESPACE TEMP
  PROFILE DEFAULT
  ACCOUNT UNLOCK;
  -- 2 Roles for UE 
  GRANT CONNECT TO UE;
  GRANT RESOURCE TO UE;
  ALTER USER UE DEFAULT ROLE ALL;
  -- 2 System Privileges for UE 
  GRANT SELECT ANY TABLE TO UE;
  GRANT UNLIMITED TABLESPACE TO UE;
  -- 1 Object Privilege for UE 
    GRANT EXECUTE ON  REPADMIN.GET_IND TO UE;


CREATE USER SVOD
  IDENTIFIED BY VALUES '43B42829241D227F'
  DEFAULT TABLESPACE FORS
  TEMPORARY TABLESPACE TEMP
  PROFILE DEFAULT
  ACCOUNT UNLOCK;
  -- 2 Roles for SVOD 
  GRANT CONNECT TO SVOD;
  GRANT RESOURCE TO SVOD;
  ALTER USER SVOD DEFAULT ROLE ALL;
  -- 1 System Privilege for SVOD 
  GRANT UNLIMITED TABLESPACE TO SVOD;
  -- 74 Object Privileges for SVOD 
    GRANT EXECUTE ON  REPADMIN.GET_IND TO SVOD;
    GRANT SELECT ON  SVETA.RN_KLS_ANAL TO SVOD;
    GRANT SELECT ON  SVETA.RN_KLS_FROM TO SVOD;
    GRANT SELECT ON  SVETA.RN_KLS_TO TO SVOD;
    GRANT SELECT ON  SVETA.RN_KLS_VALTYPE TO SVOD;
    GRANT SELECT ON  SVETA.RN_KLS_WHAT TO SVOD;
    GRANT SELECT ON  SVETA.RP_01 TO SVOD;
    GRANT SELECT ON  SVETA.RP_02 TO SVOD;
    GRANT SELECT ON  SVETA.RP_03 TO SVOD;
    GRANT SELECT ON  SVETA.RP_04 TO SVOD;
    GRANT SELECT ON  SVETA.RP_OPL TO SVOD;
    GRANT SELECT ON  SVETA.RP_OPL_ALL TO SVOD;
    GRANT SELECT ON  SVETA.RP_OTG TO SVOD;
    GRANT SELECT ON  SVETA.RP_OTG_ALL TO SVOD;
    GRANT SELECT ON  SVETA.SF_VR_AJPOK TO SVOD WITH GRANT OPTION;
    GRANT SELECT ON  SVETA.SF_VR_AJPOK_2001 TO SVOD WITH GRANT OPTION;
    GRANT SELECT ON  SVETA.SF_VR_AJPOK_2001_BEZEXP TO SVOD WITH GRANT OPTION;
    GRANT SELECT ON  SVETA.SF_VR_AJPOK_2001_WITHEXP TO SVOD WITH GRANT OPTION;
    GRANT SELECT ON  SVETA.SF_VR_AJPOK_BEZEXP TO SVOD WITH GRANT OPTION;
    GRANT SELECT ON  SVETA.SF_VR_AJPOK_WITHEXP TO SVOD WITH GRANT OPTION;
    GRANT SELECT ON  SVETA.SF_VR_AJPRO TO SVOD WITH GRANT OPTION;
    GRANT SELECT ON  SVETA.SF_VR_AJPRO_2001 TO SVOD WITH GRANT OPTION;
    GRANT SELECT ON  SVETA.SF_VR_AJPRO_2001_BEZEXP TO SVOD WITH GRANT OPTION;
    GRANT SELECT ON  SVETA.SF_VR_AJPRO_2001_WITHEXP TO SVOD WITH GRANT OPTION;
    GRANT SELECT ON  SVETA.SF_VR_AJPRO_BEZEXP TO SVOD WITH GRANT OPTION;
    GRANT SELECT ON  SVETA.SF_VR_AJPRO_WITHEXP TO SVOD WITH GRANT OPTION;
    GRANT SELECT ON  SVETA.SF_VR_AKPOK TO SVOD WITH GRANT OPTION;
    GRANT SELECT ON  SVETA.SF_VR_AKPOK_2001 TO SVOD WITH GRANT OPTION;
    GRANT SELECT ON  SVETA.SF_VR_AKPOK_2001_BEZEXP TO SVOD WITH GRANT OPTION;
    GRANT SELECT ON  SVETA.SF_VR_AKPOK_2001_WITHEXP TO SVOD WITH GRANT OPTION;
    GRANT SELECT ON  SVETA.SF_VR_AKPOK_BEZEXP TO SVOD WITH GRANT OPTION;
    GRANT SELECT ON  SVETA.SF_VR_AKPOK_WITHEXP TO SVOD WITH GRANT OPTION;
    GRANT SELECT ON  SVETA.SF_VR_AKPRO TO SVOD WITH GRANT OPTION;
    GRANT SELECT ON  SVETA.SF_VR_AKPRO_2001 TO SVOD WITH GRANT OPTION;
    GRANT SELECT ON  SVETA.SF_VR_AKPRO_2001_BEZEXP TO SVOD WITH GRANT OPTION;
    GRANT SELECT ON  SVETA.SF_VR_AKPRO_2001_WITHEXP TO SVOD WITH GRANT OPTION;
    GRANT SELECT ON  SVETA.SF_VR_AKPRO_BEZEXP TO SVOD WITH GRANT OPTION;
    GRANT SELECT ON  SVETA.SF_VR_AKPRO_WITHEXP TO SVOD WITH GRANT OPTION;
    GRANT SELECT ON  SVETA.SF_VR_JPOK TO SVOD WITH GRANT OPTION;
    GRANT SELECT ON  SVETA.SF_VR_JPOK_2001 TO SVOD WITH GRANT OPTION;
    GRANT SELECT ON  SVETA.SF_VR_JPOK_2001_BEZEXP TO SVOD WITH GRANT OPTION;
    GRANT SELECT ON  SVETA.SF_VR_JPOK_2001_PREV TO SVOD WITH GRANT OPTION;
    GRANT SELECT ON  SVETA.SF_VR_JPOK_2001_WITHEXP TO SVOD WITH GRANT OPTION;
    GRANT SELECT ON  SVETA.SF_VR_JPOK_BEZEXP TO SVOD WITH GRANT OPTION;
    GRANT SELECT ON  SVETA.SF_VR_JPOK_PREV TO SVOD WITH GRANT OPTION;
    GRANT SELECT ON  SVETA.SF_VR_JPOK_WITHEXP TO SVOD WITH GRANT OPTION;
    GRANT SELECT ON  SVETA.SF_VR_JPRO TO SVOD WITH GRANT OPTION;
    GRANT SELECT ON  SVETA.SF_VR_JPRO_2001_BEZEXP TO SVOD WITH GRANT OPTION;
    GRANT SELECT ON  SVETA.SF_VR_JPRO_2001_PREV TO SVOD WITH GRANT OPTION;
    GRANT SELECT ON  SVETA.SF_VR_JPRO_2001_WITHEXP TO SVOD WITH GRANT OPTION;
    GRANT SELECT ON  SVETA.SF_VR_JPRO_BEZEXP TO SVOD WITH GRANT OPTION;
    GRANT SELECT ON  SVETA.SF_VR_JPRO_PREV TO SVOD WITH GRANT OPTION;
    GRANT SELECT ON  SVETA.SF_VR_JPRO_WITHEXP TO SVOD WITH GRANT OPTION;
    GRANT SELECT ON  SVETA.SF_VR_KPOK TO SVOD WITH GRANT OPTION;
    GRANT SELECT ON  SVETA.SF_VR_KPOK_2001 TO SVOD WITH GRANT OPTION;
    GRANT SELECT ON  SVETA.SF_VR_KPOK_2001_BEZEXP TO SVOD WITH GRANT OPTION;
    GRANT SELECT ON  SVETA.SF_VR_KPOK_2001_PREV TO SVOD WITH GRANT OPTION;
    GRANT SELECT ON  SVETA.SF_VR_KPOK_2001_STNDS TO SVOD WITH GRANT OPTION;
    GRANT SELECT ON  SVETA.SF_VR_KPOK_2001_WITHEXP TO SVOD WITH GRANT OPTION;
    GRANT SELECT ON  SVETA.SF_VR_KPOK_BEZEXP TO SVOD WITH GRANT OPTION;
    GRANT SELECT ON  SVETA.SF_VR_KPOK_PREV TO SVOD WITH GRANT OPTION;
    GRANT SELECT ON  SVETA.SF_VR_KPOK_STNDS TO SVOD WITH GRANT OPTION;
    GRANT SELECT ON  SVETA.SF_VR_KPOK_STNDS_2001_BEZEXP TO SVOD WITH GRANT OPTION;
    GRANT SELECT ON  SVETA.SF_VR_KPOK_STNDS_2001_WITHEXP TO SVOD WITH GRANT OPTION;
    GRANT SELECT ON  SVETA.SF_VR_KPOK_STNDS_BEZEXP TO SVOD WITH GRANT OPTION;
    GRANT SELECT ON  SVETA.SF_VR_KPOK_STNDS_WITHEXP TO SVOD WITH GRANT OPTION;
    GRANT SELECT ON  SVETA.SF_VR_KPOK_WITHEXP TO SVOD WITH GRANT OPTION;
    GRANT SELECT ON  SVETA.SF_VR_KPRO TO SVOD WITH GRANT OPTION;
    GRANT SELECT ON  SVETA.SF_VR_KPRO_2001_BEZEXP TO SVOD WITH GRANT OPTION;
    GRANT SELECT ON  SVETA.SF_VR_KPRO_2001_PREV TO SVOD WITH GRANT OPTION;
    GRANT SELECT ON  SVETA.SF_VR_KPRO_2001_WITHEXP TO SVOD WITH GRANT OPTION;
    GRANT SELECT ON  SVETA.SF_VR_KPRO_BEZEXP TO SVOD WITH GRANT OPTION;
    GRANT SELECT ON  SVETA.SF_VR_KPRO_PREV TO SVOD WITH GRANT OPTION;
    GRANT SELECT ON  SVETA.SF_VR_KPRO_WITHEXP TO SVOD WITH GRANT OPTION;


CREATE USER SVETA
  IDENTIFIED BY VALUES 'AE770EBD15E1A344'
  DEFAULT TABLESPACE FORS
  TEMPORARY TABLESPACE TEMP
  PROFILE DEFAULT
  ACCOUNT UNLOCK;
  -- 2 Roles for SVETA 
  GRANT CONNECT TO SVETA;
  GRANT RESOURCE TO SVETA;
  ALTER USER SVETA DEFAULT ROLE ALL;
  -- 3 System Privileges for SVETA 
  GRANT SELECT ANY TABLE TO SVETA;
  GRANT UPDATE ANY TABLE TO SVETA;
  GRANT UNLIMITED TABLESPACE TO SVETA;
  -- 9 Object Privileges for SVETA 
    GRANT SELECT ON  MASTER.KSSS_PROD TO SVETA;
    GRANT EXECUTE ON  REPADMIN.GET_IND TO SVETA;
    GRANT SELECT ON  SAIO04.LO_FACTORY TO SVETA;
    GRANT SELECT ON  SAIO04.LO_PRODUCT TO SVETA;
    GRANT SELECT ON  SYS.DBA_INDEXES TO SVETA;
    GRANT SELECT ON  SYS.DBA_IND_COLUMNS TO SVETA;
    GRANT SELECT ON  SYS.DBA_OBJECTS TO SVETA;
    GRANT SELECT ON  SYS.DBA_SYNONYMS TO SVETA;
    GRANT SELECT ON  SYS.V_$SESSION TO SVETA;


CREATE USER SFTMP
  IDENTIFIED BY VALUES '37938E663C4AD3BF'
  DEFAULT TABLESPACE FORS
  TEMPORARY TABLESPACE TEMP
  PROFILE DEFAULT
  ACCOUNT UNLOCK;
  -- 2 Roles for SFTMP 
  GRANT CONNECT TO SFTMP;
  GRANT RESOURCE TO SFTMP;
  ALTER USER SFTMP DEFAULT ROLE ALL;
  -- 4 System Privileges for SFTMP 
  GRANT DROP ANY TABLE TO SFTMP;
  GRANT CREATE ANY TABLE TO SFTMP;
  GRANT SELECT ANY TABLE TO SFTMP;
  GRANT UNLIMITED TABLESPACE TO SFTMP;
  -- 1 Object Privilege for SFTMP 
    GRANT EXECUTE ON  REPADMIN.GET_IND TO SFTMP;


CREATE USER SFSYS
  IDENTIFIED BY VALUES '6D34CFCE394BD99F'
  DEFAULT TABLESPACE FORS
  TEMPORARY TABLESPACE TEMP
  PROFILE DEFAULT
  ACCOUNT UNLOCK;
  -- 2 Roles for SFSYS 
  GRANT CONNECT TO SFSYS;
  GRANT RESOURCE TO SFSYS;
  ALTER USER SFSYS DEFAULT ROLE ALL;
  -- 1 System Privilege for SFSYS 
  GRANT UNLIMITED TABLESPACE TO SFSYS;
  -- 1 Object Privilege for SFSYS 
    GRANT EXECUTE ON  REPADMIN.GET_IND TO SFSYS;


CREATE USER SFDBF
  IDENTIFIED BY VALUES 'CB2BD1FCA0CA49F8'
  DEFAULT TABLESPACE FORS
  TEMPORARY TABLESPACE TEMP
  PROFILE DEFAULT
  ACCOUNT UNLOCK;
  -- 2 Roles for SFDBF 
  GRANT CONNECT TO SFDBF;
  GRANT RESOURCE TO SFDBF;
  ALTER USER SFDBF DEFAULT ROLE ALL;
  -- 2 System Privileges for SFDBF 
  GRANT SELECT ANY TABLE TO SFDBF;
  GRANT UNLIMITED TABLESPACE TO SFDBF;
  -- 9 Object Privileges for SFDBF 
    GRANT EXECUTE, DEBUG ON  MASTER.FOR_KVIT TO SFDBF;
    GRANT SELECT ON  MASTER.KSSS_PROD TO SFDBF;
    GRANT EXECUTE ON  REPADMIN.GET_IND TO SFDBF;
    GRANT INSERT, SELECT ON  SVETA.SF_KLS_DOGOV TO SFDBF;
    GRANT SELECT ON  SVETA.SF_KLS_PRED TO SFDBF;
    GRANT ALTER, DELETE, INDEX, INSERT, REFERENCES, SELECT, UPDATE ON  SVETA.SF_POZ_PROD TO SFDBF;
    GRANT ALTER, DELETE, INDEX, INSERT, REFERENCES, SELECT, UPDATE, ON COMMIT REFRESH, QUERY REWRITE, DEBUG, FLASHBACK ON  SVETA.SF_POZ_VYR TO SFDBF;
    GRANT ALTER, DELETE, INDEX, INSERT, REFERENCES, SELECT, UPDATE ON  SVETA.SF_POZ_VYR_OLD TO SFDBF;
    GRANT ALTER, DELETE, INDEX, INSERT, REFERENCES, SELECT, UPDATE ON  SVETA.SF_POZ_VYR_PROBA TO SFDBF;


CREATE USER SAIO04
  IDENTIFIED BY VALUES '0FB0964BBF766F75'
  DEFAULT TABLESPACE FORS
  TEMPORARY TABLESPACE TEMP
  PROFILE DEFAULT
  ACCOUNT UNLOCK;
  -- 3 Roles for SAIO04 
  GRANT DBA TO SAIO04;
  GRANT CONNECT TO SAIO04;
  GRANT RESOURCE TO SAIO04;
  ALTER USER SAIO04 DEFAULT ROLE ALL;
  -- 111 System Privileges for SAIO04 
  GRANT AUDIT ANY TO SAIO04;
  GRANT DROP USER TO SAIO04;
  GRANT ALTER USER TO SAIO04;
  GRANT ANALYZE ANY TO SAIO04;
  GRANT BECOME USER TO SAIO04;
  GRANT CREATE ROLE TO SAIO04;
  GRANT CREATE TYPE TO SAIO04;
  GRANT CREATE USER TO SAIO04;
  GRANT CREATE VIEW TO SAIO04;
  GRANT ALTER SYSTEM TO SAIO04;
  GRANT AUDIT SYSTEM TO SAIO04;
  GRANT CREATE TABLE TO SAIO04;
  GRANT DROP PROFILE TO SAIO04;
  GRANT ALTER PROFILE TO SAIO04;
  GRANT ALTER SESSION TO SAIO04;
  GRANT DROP ANY ROLE TO SAIO04;
  GRANT DROP ANY TYPE TO SAIO04;
  GRANT DROP ANY VIEW TO SAIO04;
  GRANT QUERY REWRITE TO SAIO04;
  GRANT ALTER ANY ROLE TO SAIO04;
  GRANT ALTER ANY TYPE TO SAIO04;
  GRANT ALTER DATABASE TO SAIO04;
  GRANT CREATE CLUSTER TO SAIO04;
  GRANT CREATE LIBRARY TO SAIO04;
  GRANT CREATE PROFILE TO SAIO04;
  GRANT CREATE SESSION TO SAIO04;
  GRANT CREATE SYNONYM TO SAIO04;
  GRANT CREATE TRIGGER TO SAIO04;
  GRANT DROP ANY INDEX TO SAIO04;
  GRANT DROP ANY TABLE TO SAIO04;
  GRANT GRANT ANY ROLE TO SAIO04;
  GRANT LOCK ANY TABLE TO SAIO04;
  GRANT ALTER ANY INDEX TO SAIO04;
  GRANT ALTER ANY TABLE TO SAIO04;
  GRANT CREATE ANY TYPE TO SAIO04;
  GRANT CREATE ANY VIEW TO SAIO04;
  GRANT CREATE OPERATOR TO SAIO04;
  GRANT CREATE SEQUENCE TO SAIO04;
  GRANT CREATE SNAPSHOT TO SAIO04;
  GRANT DROP TABLESPACE TO SAIO04;
  GRANT ALTER TABLESPACE TO SAIO04;
  GRANT BACKUP ANY TABLE TO SAIO04;
  GRANT CREATE ANY INDEX TO SAIO04;
  GRANT CREATE ANY TABLE TO SAIO04;
  GRANT CREATE DIMENSION TO SAIO04;
  GRANT CREATE INDEXTYPE TO SAIO04;
  GRANT CREATE PROCEDURE TO SAIO04;
  GRANT DELETE ANY TABLE TO SAIO04;
  GRANT DROP ANY CLUSTER TO SAIO04;
  GRANT DROP ANY CONTEXT TO SAIO04;
  GRANT DROP ANY LIBRARY TO SAIO04;
  GRANT DROP ANY OUTLINE TO SAIO04;
  GRANT DROP ANY SYNONYM TO SAIO04;
  GRANT DROP ANY TRIGGER TO SAIO04;
  GRANT EXECUTE ANY TYPE TO SAIO04;
  GRANT INSERT ANY TABLE TO SAIO04;
  GRANT SELECT ANY TABLE TO SAIO04;
  GRANT UPDATE ANY TABLE TO SAIO04;
  GRANT ALTER ANY CLUSTER TO SAIO04;
  GRANT ALTER ANY LIBRARY TO SAIO04;
  GRANT ALTER ANY OUTLINE TO SAIO04;
  GRANT ALTER ANY TRIGGER TO SAIO04;
  GRANT COMMENT ANY TABLE TO SAIO04;
  GRANT CREATE TABLESPACE TO SAIO04;
  GRANT DROP ANY OPERATOR TO SAIO04;
  GRANT DROP ANY SEQUENCE TO SAIO04;
  GRANT DROP ANY SNAPSHOT TO SAIO04;
  GRANT FORCE TRANSACTION TO SAIO04;
  GRANT MANAGE TABLESPACE TO SAIO04;
  GRANT ALTER ANY SEQUENCE TO SAIO04;
  GRANT ALTER ANY SNAPSHOT TO SAIO04;
  GRANT CREATE ANY CLUSTER TO SAIO04;
  GRANT CREATE ANY CONTEXT TO SAIO04;
  GRANT CREATE ANY LIBRARY TO SAIO04;
  GRANT CREATE ANY OUTLINE TO SAIO04;
  GRANT CREATE ANY SYNONYM TO SAIO04;
  GRANT CREATE ANY TRIGGER TO SAIO04;
  GRANT DROP ANY DIMENSION TO SAIO04;
  GRANT DROP ANY DIRECTORY TO SAIO04;
  GRANT DROP ANY INDEXTYPE TO SAIO04;
  GRANT DROP ANY PROCEDURE TO SAIO04;
  GRANT RESTRICTED SESSION TO SAIO04;
  GRANT ALTER ANY DIMENSION TO SAIO04;
  GRANT ALTER ANY INDEXTYPE TO SAIO04;
  GRANT ALTER ANY PROCEDURE TO SAIO04;
  GRANT ALTER RESOURCE COST TO SAIO04;
  GRANT CREATE ANY OPERATOR TO SAIO04;
  GRANT CREATE ANY SEQUENCE TO SAIO04;
  GRANT CREATE ANY SNAPSHOT TO SAIO04;
  GRANT DROP PUBLIC SYNONYM TO SAIO04;
  GRANT EXECUTE ANY LIBRARY TO SAIO04;
  GRANT GRANT ANY PRIVILEGE TO SAIO04;
  GRANT SELECT ANY SEQUENCE TO SAIO04;
  GRANT CREATE ANY DIMENSION TO SAIO04;
  GRANT CREATE ANY DIRECTORY TO SAIO04;
  GRANT CREATE ANY INDEXTYPE TO SAIO04;
  GRANT CREATE ANY PROCEDURE TO SAIO04;
  GRANT CREATE DATABASE LINK TO SAIO04;
  GRANT EXECUTE ANY OPERATOR TO SAIO04;
  GRANT GLOBAL QUERY REWRITE TO SAIO04;
  GRANT UNLIMITED TABLESPACE TO SAIO04;
  GRANT CREATE PUBLIC SYNONYM TO SAIO04;
  GRANT DROP ROLLBACK SEGMENT TO SAIO04;
  GRANT EXECUTE ANY INDEXTYPE TO SAIO04;
  GRANT EXECUTE ANY PROCEDURE TO SAIO04;
  GRANT FORCE ANY TRANSACTION TO SAIO04;
  GRANT ALTER ROLLBACK SEGMENT TO SAIO04;
  GRANT CREATE ROLLBACK SEGMENT TO SAIO04;
  GRANT DROP PUBLIC DATABASE LINK TO SAIO04;
  GRANT ADMINISTER DATABASE TRIGGER TO SAIO04;
  GRANT CREATE PUBLIC DATABASE LINK TO SAIO04;
  -- 1 Object Privilege for SAIO04 
    GRANT SELECT ON  SYS.V_$SESSION TO SAIO04;


CREATE USER REPADMIN
  IDENTIFIED BY VALUES '915C93F34954F5F8'
  DEFAULT TABLESPACE FORS
  TEMPORARY TABLESPACE TEMP
  PROFILE DEFAULT
  ACCOUNT UNLOCK;
  -- 4 Roles for REPADMIN 
  GRANT DBA TO REPADMIN;
  GRANT CONNECT TO REPADMIN;
  GRANT RESOURCE TO REPADMIN;
  GRANT SELECT_CATALOG_ROLE TO REPADMIN;
  ALTER USER REPADMIN DEFAULT ROLE ALL;
  -- 111 System Privileges for REPADMIN 
  GRANT AUDIT ANY TO REPADMIN;
  GRANT DROP USER TO REPADMIN;
  GRANT ALTER USER TO REPADMIN;
  GRANT ANALYZE ANY TO REPADMIN;
  GRANT BECOME USER TO REPADMIN;
  GRANT CREATE ROLE TO REPADMIN;
  GRANT CREATE TYPE TO REPADMIN;
  GRANT CREATE USER TO REPADMIN;
  GRANT CREATE VIEW TO REPADMIN;
  GRANT ALTER SYSTEM TO REPADMIN;
  GRANT AUDIT SYSTEM TO REPADMIN;
  GRANT CREATE TABLE TO REPADMIN;
  GRANT DROP PROFILE TO REPADMIN;
  GRANT ALTER PROFILE TO REPADMIN;
  GRANT ALTER SESSION TO REPADMIN;
  GRANT DROP ANY ROLE TO REPADMIN;
  GRANT DROP ANY TYPE TO REPADMIN;
  GRANT DROP ANY VIEW TO REPADMIN;
  GRANT QUERY REWRITE TO REPADMIN;
  GRANT ALTER ANY ROLE TO REPADMIN;
  GRANT ALTER ANY TYPE TO REPADMIN;
  GRANT ALTER DATABASE TO REPADMIN;
  GRANT CREATE CLUSTER TO REPADMIN;
  GRANT CREATE LIBRARY TO REPADMIN;
  GRANT CREATE PROFILE TO REPADMIN;
  GRANT CREATE SESSION TO REPADMIN;
  GRANT CREATE SYNONYM TO REPADMIN;
  GRANT CREATE TRIGGER TO REPADMIN;
  GRANT DROP ANY INDEX TO REPADMIN;
  GRANT DROP ANY TABLE TO REPADMIN;
  GRANT GRANT ANY ROLE TO REPADMIN;
  GRANT LOCK ANY TABLE TO REPADMIN;
  GRANT ALTER ANY INDEX TO REPADMIN;
  GRANT ALTER ANY TABLE TO REPADMIN;
  GRANT CREATE ANY TYPE TO REPADMIN;
  GRANT CREATE ANY VIEW TO REPADMIN;
  GRANT CREATE OPERATOR TO REPADMIN;
  GRANT CREATE SEQUENCE TO REPADMIN;
  GRANT CREATE SNAPSHOT TO REPADMIN;
  GRANT DROP TABLESPACE TO REPADMIN;
  GRANT ALTER TABLESPACE TO REPADMIN;
  GRANT BACKUP ANY TABLE TO REPADMIN;
  GRANT CREATE ANY INDEX TO REPADMIN;
  GRANT CREATE ANY TABLE TO REPADMIN;
  GRANT CREATE DIMENSION TO REPADMIN;
  GRANT CREATE INDEXTYPE TO REPADMIN;
  GRANT CREATE PROCEDURE TO REPADMIN;
  GRANT DELETE ANY TABLE TO REPADMIN;
  GRANT DROP ANY CLUSTER TO REPADMIN;
  GRANT DROP ANY CONTEXT TO REPADMIN;
  GRANT DROP ANY LIBRARY TO REPADMIN;
  GRANT DROP ANY OUTLINE TO REPADMIN;
  GRANT DROP ANY SYNONYM TO REPADMIN;
  GRANT DROP ANY TRIGGER TO REPADMIN;
  GRANT EXECUTE ANY TYPE TO REPADMIN;
  GRANT INSERT ANY TABLE TO REPADMIN;
  GRANT SELECT ANY TABLE TO REPADMIN;
  GRANT UPDATE ANY TABLE TO REPADMIN;
  GRANT ALTER ANY CLUSTER TO REPADMIN;
  GRANT ALTER ANY LIBRARY TO REPADMIN;
  GRANT ALTER ANY OUTLINE TO REPADMIN;
  GRANT ALTER ANY TRIGGER TO REPADMIN;
  GRANT COMMENT ANY TABLE TO REPADMIN;
  GRANT CREATE TABLESPACE TO REPADMIN;
  GRANT DROP ANY OPERATOR TO REPADMIN;
  GRANT DROP ANY SEQUENCE TO REPADMIN;
  GRANT DROP ANY SNAPSHOT TO REPADMIN;
  GRANT FORCE TRANSACTION TO REPADMIN;
  GRANT MANAGE TABLESPACE TO REPADMIN;
  GRANT ALTER ANY SEQUENCE TO REPADMIN;
  GRANT ALTER ANY SNAPSHOT TO REPADMIN;
  GRANT CREATE ANY CLUSTER TO REPADMIN;
  GRANT CREATE ANY CONTEXT TO REPADMIN;
  GRANT CREATE ANY LIBRARY TO REPADMIN;
  GRANT CREATE ANY OUTLINE TO REPADMIN;
  GRANT CREATE ANY SYNONYM TO REPADMIN;
  GRANT CREATE ANY TRIGGER TO REPADMIN;
  GRANT DROP ANY DIMENSION TO REPADMIN;
  GRANT DROP ANY DIRECTORY TO REPADMIN;
  GRANT DROP ANY INDEXTYPE TO REPADMIN;
  GRANT DROP ANY PROCEDURE TO REPADMIN;
  GRANT RESTRICTED SESSION TO REPADMIN;
  GRANT ALTER ANY DIMENSION TO REPADMIN;
  GRANT ALTER ANY INDEXTYPE TO REPADMIN;
  GRANT ALTER ANY PROCEDURE TO REPADMIN;
  GRANT ALTER RESOURCE COST TO REPADMIN;
  GRANT CREATE ANY OPERATOR TO REPADMIN;
  GRANT CREATE ANY SEQUENCE TO REPADMIN;
  GRANT CREATE ANY SNAPSHOT TO REPADMIN;
  GRANT DROP PUBLIC SYNONYM TO REPADMIN;
  GRANT EXECUTE ANY LIBRARY TO REPADMIN;
  GRANT GRANT ANY PRIVILEGE TO REPADMIN;
  GRANT SELECT ANY SEQUENCE TO REPADMIN;
  GRANT CREATE ANY DIMENSION TO REPADMIN;
  GRANT CREATE ANY DIRECTORY TO REPADMIN;
  GRANT CREATE ANY INDEXTYPE TO REPADMIN;
  GRANT CREATE ANY PROCEDURE TO REPADMIN;
  GRANT CREATE DATABASE LINK TO REPADMIN;
  GRANT EXECUTE ANY OPERATOR TO REPADMIN;
  GRANT GLOBAL QUERY REWRITE TO REPADMIN;
  GRANT UNLIMITED TABLESPACE TO REPADMIN;
  GRANT CREATE PUBLIC SYNONYM TO REPADMIN;
  GRANT DROP ROLLBACK SEGMENT TO REPADMIN;
  GRANT EXECUTE ANY INDEXTYPE TO REPADMIN;
  GRANT EXECUTE ANY PROCEDURE TO REPADMIN;
  GRANT FORCE ANY TRANSACTION TO REPADMIN;
  GRANT ALTER ROLLBACK SEGMENT TO REPADMIN;
  GRANT CREATE ROLLBACK SEGMENT TO REPADMIN;
  GRANT DROP PUBLIC DATABASE LINK TO REPADMIN;
  GRANT ADMINISTER DATABASE TRIGGER TO REPADMIN;
  GRANT CREATE PUBLIC DATABASE LINK TO REPADMIN;
  -- 21 Object Privileges for REPADMIN 
    GRANT EXECUTE ON  SYS.DBMSOBJGWRAPPER TO REPADMIN;
    GRANT EXECUTE ON  SYS.DBMS_ALERT TO REPADMIN;
    GRANT EXECUTE ON  SYS.DBMS_DEFER_INTERNAL_QUERY TO REPADMIN;
    GRANT EXECUTE ON  SYS.DBMS_DEFER_INTERNAL_SYS TO REPADMIN;
    GRANT EXECUTE ON  SYS.DBMS_DEFER_QUERY TO REPADMIN;
    GRANT EXECUTE ON  SYS.DBMS_DEFER_SYS TO REPADMIN;
    GRANT EXECUTE ON  SYS.DBMS_INTERNAL_REPCAT TO REPADMIN;
    GRANT EXECUTE ON  SYS.DBMS_OFFLINE_OG TO REPADMIN;
    GRANT EXECUTE ON  SYS.DBMS_OFFLINE_SNAPSHOT TO REPADMIN;
    GRANT EXECUTE ON  SYS.DBMS_RECTIFIER_DIFF TO REPADMIN;
    GRANT EXECUTE ON  SYS.DBMS_REPCAT TO REPADMIN;
    GRANT EXECUTE ON  SYS.DBMS_REPCAT_DECL TO REPADMIN;
    GRANT EXECUTE ON  SYS.DBMS_REPCAT_RGT TO REPADMIN;
    GRANT EXECUTE ON  SYS.DBMS_REPCAT_RPC TO REPADMIN;
    GRANT EXECUTE ON  SYS.DBMS_REPCAT_UNTRUSTED TO REPADMIN;
    GRANT EXECUTE ON  SYS.DBMS_REPCAT_UTL TO REPADMIN;
    GRANT EXECUTE ON  SYS.DBMS_SNAPSHOT TO REPADMIN;
    GRANT EXECUTE ON  SYS.DBMS_SNAP_REPAPI TO REPADMIN;
    GRANT SELECT ON  SYS.DEFLOB TO REPADMIN;
    GRANT SELECT ON  SYS.V_$SESSION TO REPADMIN;
    GRANT SELECT ON  SYSTEM.DEF$_LOB TO REPADMIN;


CREATE USER OPERATIV
  IDENTIFIED BY VALUES '72F9AC678AE2449A'
  DEFAULT TABLESPACE FORS
  TEMPORARY TABLESPACE TEMP
  PROFILE DEFAULT
  ACCOUNT UNLOCK;
  -- 2 Roles for OPERATIV 
  GRANT CONNECT TO OPERATIV;
  GRANT RESOURCE TO OPERATIV;
  ALTER USER OPERATIV DEFAULT ROLE ALL;
  -- 1 System Privilege for OPERATIV 
  GRANT UNLIMITED TABLESPACE TO OPERATIV;


CREATE USER DESIGNER6
  IDENTIFIED BY VALUES 'EB1FDB839EAEFE59'
  DEFAULT TABLESPACE DESIGNER
  TEMPORARY TABLESPACE TEMP
  PROFILE DEFAULT
  ACCOUNT UNLOCK;
  -- 2 Roles for DESIGNER6 
  GRANT CONNECT TO DESIGNER6 WITH ADMIN OPTION;
  GRANT RESOURCE TO DESIGNER6 WITH ADMIN OPTION;
  ALTER USER DESIGNER6 DEFAULT ROLE ALL;
  -- 7 System Privileges for DESIGNER6 
  GRANT CREATE ROLE TO DESIGNER6 WITH ADMIN OPTION;
  GRANT DROP ANY SYNONYM TO DESIGNER6 WITH ADMIN OPTION;
  GRANT CREATE ANY SYNONYM TO DESIGNER6 WITH ADMIN OPTION;
  GRANT DROP PUBLIC SYNONYM TO DESIGNER6 WITH ADMIN OPTION;
  GRANT SELECT ANY SEQUENCE TO DESIGNER6 WITH ADMIN OPTION;
  GRANT UNLIMITED TABLESPACE TO DESIGNER6 WITH ADMIN OPTION;
  GRANT CREATE PUBLIC SYNONYM TO DESIGNER6 WITH ADMIN OPTION;
  -- 2 Tablespace Quotas for DESIGNER6 
  ALTER USER DESIGNER6 QUOTA UNLIMITED ON DESIGNER;
  ALTER USER DESIGNER6 QUOTA UNLIMITED ON USERS;
  -- 3 Object Privileges for DESIGNER6 
    GRANT EXECUTE ON  SYS.DBMS_LOCK TO DESIGNER6 WITH GRANT OPTION;
    GRANT EXECUTE ON  SYS.DBMS_PIPE TO DESIGNER6 WITH GRANT OPTION;
    GRANT SELECT ON  SYS.V_$PARAMETER TO DESIGNER6;


CREATE USER AZSBUFFER
  IDENTIFIED BY VALUES 'A11A7F8F3F0E1F6A'
  DEFAULT TABLESPACE AZS
  TEMPORARY TABLESPACE TEMP
  PROFILE DEFAULT
  ACCOUNT UNLOCK;
  -- 2 Roles for AZSBUFFER 
  GRANT CONNECT TO AZSBUFFER;
  GRANT RESOURCE TO AZSBUFFER;
  ALTER USER AZSBUFFER DEFAULT ROLE ALL;
  -- 3 System Privileges for AZSBUFFER 
  GRANT ALTER SYSTEM TO AZSBUFFER;
  GRANT UNLIMITED TABLESPACE TO AZSBUFFER;
  GRANT SELECT ANY DICTIONARY TO AZSBUFFER;
  -- 2 Tablespace Quotas for AZSBUFFER 
  ALTER USER AZSBUFFER QUOTA UNLIMITED ON LOADER;
  ALTER USER AZSBUFFER QUOTA UNLIMITED ON AZS;
  -- 1 Object Privilege for AZSBUFFER 
    GRANT SELECT ON  SYS.V_$SESSION TO AZSBUFFER;


-- DBLINKS 

CREATE PUBLIC DATABASE LINK "ORACLE.WORLD"
 CONNECT TO VANEEV
 IDENTIFIED BY <PWD>
 USING 'P5.WORLD';


CREATE PUBLIC DATABASE LINK "ORA.LUNP.RU"
 CONNECT TO SYSTEM
 IDENTIFIED BY <PWD>
 USING 'LIN.WORLD';



-- JOBS

DECLARE
  X NUMBER;
BEGIN
  SYS.DBMS_JOB.SUBMIT
  ( job       => X 
   ,what      => 'BEGIN
  FOR_ZAKAZ.LOAD_CONSORDS(NULL,NULL);
END;    '
   ,next_date => to_date('01.01.4000 00:00:00','dd/mm/yyyy hh24:mi:ss')
   ,interval  => 'TRUNC(SYSDATE+1)+23/24'
   ,no_parse  => FALSE
  );
END;
/



DECLARE
  X NUMBER;
BEGIN
  SYS.DBMS_JOB.SUBMIT
  ( job       => X 
   ,what      => 'FOR_PARUS.Renew_dog_PARUS;'
   ,next_date => to_date('31.01.2008 21:28:38','dd/mm/yyyy hh24:mi:ss')
   ,interval  => 'SYSDATE+1/6'
   ,no_parse  => FALSE
  );
END;
/



DECLARE
  X NUMBER;
BEGIN
  SYS.DBMS_JOB.SUBMIT
  ( job       => X 
   ,what      => 'For_Temp.CLEAR_TEMP_VARI;  '
   ,next_date => to_date('01.02.2008 00:00:00','dd/mm/yyyy hh24:mi:ss')
   ,interval  => 'TRUNC(SYSDATE+1)'
   ,no_parse  => FALSE
  );
END;
/






DECLARE
  X NUMBER;
BEGIN
  SYS.DBMS_JOB.SUBMIT
  ( job       => X 
   ,what      => 'BEGIN
EXECUTE IMMEDIATE ''TRUNCATE TABLE AZS_R_TEMP REUSE STORAGE'';
EXECUTE IMMEDIATE ''TRUNCATE TABLE AZS_V_TMP REUSE STORAGE'';
EXECUTE IMMEDIATE ''TRUNCATE TABLE AZS_T_TMP REUSE STORAGE'';
EXECUTE IMMEDIATE ''TRUNCATE TABLE AZS_RIN_TEMP REUSE STORAGE'';
EXECUTE IMMEDIATE ''TRUNCATE TABLE AZS_M_TEMP REUSE STORAGE'';


   EXCEPTION
     WHEN NO_DATA_FOUND THEN
       NULL;
     WHEN OTHERS THEN
       -- Consider logging the error and then re-raise
       NULL;
END;'
   ,next_date => to_date('31.01.2008 18:59:55','dd/mm/yyyy hh24:mi:ss')
   ,interval  => 'SYSDATE+10/1440 '
   ,no_parse  => FALSE
  );
END;
/


DECLARE
  X NUMBER;
BEGIN
  SYS.DBMS_JOB.SUBMIT
  ( job       => X 
   ,what      => 'dbms_refresh.refresh(''"MASTER"."UNP_PASPORT"'');'
   ,next_date => to_date('01.01.4000 00:00:00','dd/mm/yyyy hh24:mi:ss')
   ,interval  => 'sysdate + 1/144 '
   ,no_parse  => FALSE
  );
END;
/



