
CREATE TABLESPACE USERSINDX DATAFILE 
  'E:\ORACLE\MASTER\ORADATA\USERSINDX01.DBF' SIZE 2500M AUTOEXTEND ON NEXT 100M MAXSIZE 16000M
LOGGING
ONLINE
PERMANENT
EXTENT MANAGEMENT LOCAL AUTOALLOCATE
BLOCKSIZE 8K
SEGMENT SPACE MANAGEMENT AUTO;


CREATE TABLESPACE USERS2 DATAFILE 
  'E:\ORACLE\MASTER\ORADATA\USERS02.DBF' SIZE 1500M AUTOEXTEND ON NEXT 100M MAXSIZE 16000M
LOGGING
ONLINE
PERMANENT
EXTENT MANAGEMENT LOCAL AUTOALLOCATE
BLOCKSIZE 8K
SEGMENT SPACE MANAGEMENT AUTO;


CREATE TABLESPACE USERS_INDX DATAFILE 
  'E:\ORACLE\MASTER\ORADATA\USERS_INDX01.DBF' SIZE 100M AUTOEXTEND ON NEXT 100M MAXSIZE 16000M
LOGGING
ONLINE
PERMANENT
EXTENT MANAGEMENT LOCAL AUTOALLOCATE
BLOCKSIZE 8K
SEGMENT SPACE MANAGEMENT AUTO;


CREATE TABLESPACE USERS DATAFILE 
  'E:\ORACLE\MASTER\ORADATA\USERS01.DBF' SIZE 100M AUTOEXTEND ON NEXT 100M MAXSIZE 16000M
LOGGING
ONLINE
PERMANENT
EXTENT MANAGEMENT LOCAL AUTOALLOCATE
BLOCKSIZE 8K
SEGMENT SPACE MANAGEMENT AUTO;


CREATE TABLESPACE UPDATELIST DATAFILE 
  'E:\ORACLE\MASTER\ORADATA\UPDATELIST1.DBF' SIZE 17000M AUTOEXTEND ON NEXT 100M MAXSIZE 18000M
LOGGING
ONLINE
PERMANENT
EXTENT MANAGEMENT LOCAL AUTOALLOCATE
BLOCKSIZE 8K
SEGMENT SPACE MANAGEMENT AUTO;


CREATE TABLESPACE TOOLS DATAFILE 
  'E:\ORACLE\MASTER\ORADATA\TOOLS01.DBF' SIZE 200M AUTOEXTEND ON NEXT 100M MAXSIZE 16000M
LOGGING
ONLINE
PERMANENT
EXTENT MANAGEMENT LOCAL AUTOALLOCATE
BLOCKSIZE 8K
SEGMENT SPACE MANAGEMENT AUTO;





CREATE TABLESPACE LOADERINDX DATAFILE 
  'E:\ORACLE\MASTER\ORADATA\LOADERINDX01.DBF' SIZE 1000M AUTOEXTEND ON NEXT 100M MAXSIZE 16000M
LOGGING
ONLINE
PERMANENT
EXTENT MANAGEMENT LOCAL AUTOALLOCATE
BLOCKSIZE 8K
SEGMENT SPACE MANAGEMENT AUTO;


CREATE TABLESPACE LOADER2 DATAFILE 
  'E:\ORACLE\MASTER\ORADATA\LOADER02.DBF' SIZE 1000M AUTOEXTEND ON NEXT 100M MAXSIZE 16000M
NOLOGGING
ONLINE
PERMANENT
EXTENT MANAGEMENT LOCAL AUTOALLOCATE
BLOCKSIZE 8K
SEGMENT SPACE MANAGEMENT AUTO;


CREATE TABLESPACE LOADER_INDX DATAFILE 
  'E:\ORACLE\MASTER\ORADATA\LOADER_INDX01.DBF' SIZE 100M AUTOEXTEND ON NEXT 100M MAXSIZE 16000M
LOGGING
ONLINE
PERMANENT
EXTENT MANAGEMENT LOCAL AUTOALLOCATE
BLOCKSIZE 8K
SEGMENT SPACE MANAGEMENT AUTO;


CREATE TABLESPACE LOADER DATAFILE 
  'E:\ORACLE\MASTER\ORADATA\LOADER01.DBF' SIZE 1000M AUTOEXTEND ON NEXT 100M MAXSIZE 16000M
NOLOGGING
ONLINE
PERMANENT
EXTENT MANAGEMENT LOCAL AUTOALLOCATE
BLOCKSIZE 8K
SEGMENT SPACE MANAGEMENT AUTO;


CREATE TABLESPACE INDX DATAFILE 
  'E:\ORACLE\MASTER\ORADATA\INDX01.DBF' SIZE 100M AUTOEXTEND ON NEXT 100M MAXSIZE 16000M
LOGGING
ONLINE
PERMANENT
EXTENT MANAGEMENT LOCAL AUTOALLOCATE
BLOCKSIZE 8K
SEGMENT SPACE MANAGEMENT AUTO;


CREATE TABLESPACE FORSINDX DATAFILE 
  'E:\ORACLE\MASTER\ORADATA\FORSINDX01.DBF' SIZE 100M AUTOEXTEND ON NEXT 100M MAXSIZE 16000M
LOGGING
ONLINE
PERMANENT
EXTENT MANAGEMENT LOCAL AUTOALLOCATE
BLOCKSIZE 8K
SEGMENT SPACE MANAGEMENT AUTO;


CREATE TABLESPACE FORS_INDX DATAFILE 
  'E:\ORACLE\MASTER\ORADATA\FORS_INDX01.DBF' SIZE 1000M AUTOEXTEND ON NEXT 100M MAXSIZE 16000M
LOGGING
ONLINE
PERMANENT
EXTENT MANAGEMENT LOCAL AUTOALLOCATE
BLOCKSIZE 8K
SEGMENT SPACE MANAGEMENT AUTO;


CREATE TABLESPACE FORS DATAFILE 
  'E:\ORACLE\MASTER\ORADATA\FORS01.DBF' SIZE 2000M AUTOEXTEND ON NEXT 100M MAXSIZE 16000M
LOGGING
ONLINE
PERMANENT
EXTENT MANAGEMENT LOCAL AUTOALLOCATE
BLOCKSIZE 8K
SEGMENT SPACE MANAGEMENT AUTO;


CREATE TABLESPACE DESIINDX DATAFILE 
  'E:\ORACLE\MASTER\ORADATA\DESIINDX01.DBF' SIZE 200M AUTOEXTEND ON NEXT 100M MAXSIZE 16000M
LOGGING
ONLINE
PERMANENT
EXTENT MANAGEMENT LOCAL AUTOALLOCATE
BLOCKSIZE 8K
SEGMENT SPACE MANAGEMENT AUTO;


CREATE TABLESPACE DESIGNER DATAFILE 
  'E:\ORACLE\MASTER\ORADATA\DESIGNER01.DBF' SIZE 100M AUTOEXTEND ON NEXT 100M MAXSIZE 16000M
LOGGING
ONLINE
PERMANENT
EXTENT MANAGEMENT LOCAL AUTOALLOCATE
BLOCKSIZE 8K
SEGMENT SPACE MANAGEMENT AUTO;


CREATE TABLESPACE AZSINDX DATAFILE 
  'E:\ORACLE\MASTER\ORADATA\AZSINDX01.DBF' SIZE 6000M AUTOEXTEND ON NEXT 100M MAXSIZE 16000M
LOGGING
ONLINE
PERMANENT
EXTENT MANAGEMENT LOCAL AUTOALLOCATE
BLOCKSIZE 8K
SEGMENT SPACE MANAGEMENT AUTO;


CREATE TABLESPACE AZS2 DATAFILE 
  'E:\ORACLE\MASTER\ORADATA\AZS02.DBF' SIZE 100M AUTOEXTEND ON NEXT 100M MAXSIZE 16000M
LOGGING
ONLINE
PERMANENT
EXTENT MANAGEMENT LOCAL AUTOALLOCATE
BLOCKSIZE 8K
SEGMENT SPACE MANAGEMENT AUTO;


CREATE TABLESPACE AZS_INDX DATAFILE 
  'E:\ORACLE\MASTER\ORADATA\AZS_INDX01.DBF' SIZE 100M AUTOEXTEND ON NEXT 100M MAXSIZE 16000M
LOGGING
ONLINE
PERMANENT
EXTENT MANAGEMENT LOCAL AUTOALLOCATE
BLOCKSIZE 8K
SEGMENT SPACE MANAGEMENT AUTO;


CREATE TABLESPACE AZS DATAFILE 
  'E:\ORACLE\MASTER\ORADATA\AZS01.DBF' SIZE 17000M AUTOEXTEND ON NEXT 100M MAXSIZE 20000M
LOGGING
ONLINE
PERMANENT
EXTENT MANAGEMENT LOCAL AUTOALLOCATE
BLOCKSIZE 8K
SEGMENT SPACE MANAGEMENT AUTO;


