/* Уменьшение временной табличной области */

--  DROP TABLESPACE TEMP;

--  CREATE TEMPORARY TABLESPACE TEMP TEMPFILE 
--    'G:\DB_ORCL\TEMP1.ORA' SIZE 100M REUSE AUTOEXTEND ON NEXT 100M MAXSIZE 10000M
--  EXTENT MANAGEMENT LOCAL UNIFORM SIZE 408K;

  ALTER DATABASE TEMPFILE 'G:\DB_ORCL\TEMP1.ORA' DROP;
  ALTER TABLESPACE TEMP ADD TEMPFILE 'G:\DB_ORCL\TEMP1.ORA' SIZE 300M REUSE AUTOEXTEND ON NEXT 100M MAXSIZE 10000M;

  ALTER DATABASE TEMPFILE 'I:\DB_ORCL\TEMP2.ORA' DROP;
  ALTER TABLESPACE TEMP ADD TEMPFILE 'I:\DB_ORCL\TEMP2.ORA' SIZE 300M REUSE AUTOEXTEND ON NEXT 100M MAXSIZE 1000M;

--ALTER DATABASE TEMPFILE 'G:\DB_ORCL\TEMP1.ORA' RESIZE  500M;

--ALTER DATABASE TEMPFILE 'N:\DB_ORCL\TEMP2.ORA' RESIZE  500M;

--ALTER DATABASE TEMPFILE 'I:\DB_ORCL\TEMP3.ORA' RESIZE  500M;

exit;


