DROP TABLESPACE "TEMP" INCLUDING CONTENTS CASCADE CONSTRAINTS;

CREATE TEMPORARY TABLESPACE "TEMP" TEMPFILE 'D:\ORACLE\ORADATA\NB\TEMP1.ORA' SIZE 300M REUSE AUTOEXTEND ON NEXT 100M MAXSIZE 2000M EXTENT MANAGEMENT LOCAL;

