truncate table zakaz;
/

insert into zakaz
( ID, IS_AGENT, DATE_PLAN, CLIENT_NUMBER, CLIENT_DATE, INPUT_NUMBER, INPUT_DATE, BEGIN_DATE, IS_ACCEPT, FILIAL_ID, 
PLAT_ID, DOG_ID, PROD_ID_NPR, USL_OPL_ID, LOAD_ABBR, STAN_ID, VETKA_ID, POLUCH_ID, POTREB_ID, POTREB_NAME, NEFTEBASA, 
PAYFORM_ID, PLANSTRU_ID, PRICE_CLIENT, PRICE, VES, KOL, SPEED_VES, SPEED_KOL, NOM_ZD_LIST, FACT_VES, FACT_KOL, 
PRIM, GR4 )
select 
ID, IS_AGENT, DATE_PLAN, CLIENT_NUMBER, CLIENT_DATE, INPUT_NUMBER, INPUT_DATE, BEGIN_DATE, IS_REQUESTED, ORGSTRU_ID,
KLS_PREDPR_ID, KLS_DOG_ID, KLS_PROD_ID,USL_OPL_ID,LOAD_ABBR,STAN_ID,VETKA_ID,POLUCH_ID,POTREB_ID, POTREB_NAME,STORE_NAME,
PAYFORM_ID,KLS_PLANSTRUID,NULL,PRICE,REQUEST,KOL,SPEED_VES, SPEED_KOL,NOM_ZD,NVL(EXECUTED,0),0,
PRICH,GR4
from month_all
where date_plan>=to_date('01.01.2004','dd.mm.yyyy')
and parus_rn is null;
/

truncate table zakaz_parus;
/

insert into zakaz_parus
( PARUS_RN,DATE_PLAN, CLIENT_NUMBER, CLIENT_DATE, INPUT_NUMBER, INPUT_DATE, IS_ACCEPT, FILIAL_ID, 
PARUS_AGENT_RN, PARUS_AGENT_TAG, PARUS_AGENT_NAME, PARUS_DOGOVOR, PARUS_NOMEN_RN, PARUS_NOMEN_TAG, PARUS_NOMEN_NAME,
PARUS_MODIF_RN, PARUS_MODIF_TAG, PARUS_MODIF_NAME, USL_OPL_ID, POLUCH_NAME, POTREB_NAME, NEFTEBASA, 
PRICE_CLIENT, PRICE, VES, FACT_VES, PRIM,IS_WORK )
select 
PARUS_RN, DATE_PLAN, CLIENT_NUMBER, CLIENT_DATE, INPUT_NUMBER, INPUT_DATE, IS_REQUESTED, ORGSTRU_ID,
PARUS_AGENT_RN, PARUS_AGENT_TAG, PARUS_AGENT_NAME, PARUS_DOGOVOR, PARUS_NOMEN_RN, PARUS_NOMEN_TAG, PARUS_NOMEN_NAME,
PARUS_MODIF_RN, PARUS_MODIF_TAG, PARUS_MODIF_NAME, USL_OPL_ID, POLUCH_NAME, POTREB_NAME,STORE_NAME,
NULL,PRICE,REQUEST,NVL(EXECUTED,0),PRICH,IS_WORK
from month_all
where date_plan>=to_date('01.01.2004','dd.mm.yyyy')
and parus_rn is not null;
/

truncate table zakaz_hist;
/

insert into zakaz_HIST
( ID, ZAKAZ_ID, SORTBY, STATUS_ZAKAZ_ID, CLIENT_NUMBER, CLIENT_DATE, INPUT_NUMBER, INPUT_DATE, 
PROD_ID_NPR, OLD_STAN_ID, STAN_ID, POLUCH_ID, 
PRICE, VES, KOL, SPEED_VES, SPEED_KOL, NOM_ZD, FACT_VES, FACT_KOL )
select 
ID, month_all_id, sortby, STATUS_ZAKAZ_ID, CLIENT_NUMBER, CLIENT_DATE, INPUT_NUMBER, INPUT_DATE, 
KLS_PROD_ID,STAN_OLD_ID,  STAN_ID,POLUCH_ID,
PRICE,REQUEST,KOL,SPEED_VES, SPEED_KOL,NOM_ZD,0,0
from month_all_row
where status_zakaz_id>10;
/
