SELECT * FROM docinpt WHERE rn=900001445653

DECLARE 
  PTABLE VARCHAR2(200);
  PFROM_RN NUMBER;
  PTO_RN NUMBER;
  PUPDL NUMBER;
BEGIN 
  PTABLE := 'DOCINPT';
  PFROM_RN := 455268585;
  PTO_RN := 900001430466;
  PUPDL := 1;
  PARUS.PR_REPLICATE_CHANGE_RN ( PTABLE, PFROM_RN, PTO_RN, PUPDL );
  COMMIT; 
END; 

SELECT * FROM doclinks WHERE in_doc=900001418225


SELECT DISTINCT 'BEGIN PARUS.PR_REPLICATE_DOCUMENT_SNP('''',''DOCINPT'','||TO_CHAR(DOCINPT.RN)||',1,1); END;' as SQL 
FROM DOCINPT 
WHERE RN IN (SELECT /*+ RULE */  d.IN_DOC 
                FROM snp_repl.REPL_CALL_OUT a, snp_repl.REPL_SCHEMA_ROW b , snp_repl.REPL_TABLE c, DOCLINKS d 
                WHERE a.schemarow_rn=b.rn AND b.table_dest_rn=c.rn AND a.counter>=4
				AND c.TABLENAME='DOCLINKS' AND a.operation IN ('I','U')
				AND a.TABLERN=d.RN)
--ORDER BY SQL DESC				
UNION ALL
SELECT DISTINCT 'BEGIN PARUS.PR_REPLICATE_DOCUMENT_SNP('''',''DOCOUTPT'','||TO_CHAR(DOCOUTPT.RN)||',1,1); END;' as SQL 
FROM DOCOUTPT 
WHERE RN IN (SELECT /*+ RULE */  d.OUT_DOC 
                FROM snp_repl.REPL_CALL_OUT a, snp_repl.REPL_SCHEMA_ROW b , snp_repl.REPL_TABLE c, DOCLINKS d 
                WHERE a.schemarow_rn=b.rn AND b.table_dest_rn=c.rn AND a.counter>=4
				AND c.TABLENAME='DOCLINKS' AND a.operation IN ('I','U')
				AND a.TABLERN=d.RN)
ORDER BY SQL DESC				


SELECT 'SELECT ''BEGIN'' FROM dual UNION ALL'  FROM dual
UNION ALL	
(
SELECT * FROM
(			
SELECT DISTINCT 'SELECT '' PARUS.PR_REPLICATE_CHANGE_RN(''''DOCINPT'''','||TO_CHAR(DOCINPT.RN)||',''||TO_CHAR(RN)||'',1); '' FROM DOCINPT WHERE DOCUMENT='||TO_CHAR(DOCINPT.DOCUMENT)||' AND '||TO_CHAR(DOCINPT.RN)||'<>DOCINPT.RN UNION ALL' as SQL 
FROM DOCINPT 
WHERE RN IN (SELECT /*+ RULE */  a.TABLERN 
                FROM snp_repl.REPL_CALL_OUT a, snp_repl.REPL_SCHEMA_ROW b , snp_repl.REPL_TABLE c 
                WHERE a.schemarow_rn=b.rn AND b.table_dest_rn=c.rn AND a.counter>=4
				AND c.TABLENAME='DOCINPT' AND a.operation IN ('I','U'))
UNION ALL
SELECT DISTINCT 'SELECT '' PARUS.PR_REPLICATE_CHANGE_RN(''''DOCOUTPT'''','||TO_CHAR(DOCOUTPT.RN)||',''||TO_CHAR(RN)||'',1); '' FROM DOCOUTPT WHERE DOCUMENT='||TO_CHAR(DOCOUTPT.DOCUMENT)||' AND '||TO_CHAR(DOCOUTPT.RN)||'<>DOCOUTPT.RN UNION ALL' as SQL 
FROM DOCLINKS,DOCOUTPT
WHERE DOCLINKS.OUT_DOC=DOCOUTPT.RN AND DOCLINKS.RN IN (SELECT /*+ RULE */  a.TABLERN 
                FROM snp_repl.REPL_CALL_OUT a, snp_repl.REPL_SCHEMA_ROW b , snp_repl.REPL_TABLE c 
                WHERE a.schemarow_rn=b.rn AND b.table_dest_rn=c.rn AND a.counter>=4
				AND c.TABLENAME='DOCLINKS' AND a.operation IN ('I','U'))
ORDER BY SQL DESC	
)
)
UNION ALL
SELECT 'SELECT ''END;'' FROM dual UNION ALL' FROM dual
UNION ALL				
SELECT 'SELECT ''/'' FROM dual' FROM dual				

