insert into updatelist (TABLENAME, TABLERN, AUTHID, MODIFDATE, OPERATION, NOTE)
select 'INCOMDOC',RN,'SNP_REPL_MANUAL',SYSDATE,'U','?' from snp_repl.v_arh_incomdoc


DECLARE 
  PUNITCODE VARCHAR2(200);
  PTABLENAME VARCHAR2(200);
  PTABLERN NUMBER;
  PSELF NUMBER;
  PCOMMIT NUMBER;
BEGIN 
  PUNITCODE := NULL;
  PTABLENAME := 'WROFFACTS';
  PTABLERN := 405898154;
  PSELF := 1;
  PCOMMIT := 1;
  PARUS.Pr_Replicate_Document_Snp ( PUNITCODE, PTABLENAME, PTABLERN, PSELF, PCOMMIT );
  COMMIT; 
END; 