CREATE INDEX PARUS.I_DOCINPT_AUTHID_FK ON PARUS.DOCINPT
(AUTHID)
LOGGING
TABLESPACE PARUSIDX3
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          1200K
            MINEXTENTS       1
            MAXEXTENTS       2147483645
            PCTINCREASE      0
            FREELISTS        1
            FREELIST GROUPS  1
            BUFFER_POOL      DEFAULT
           )
NOPARALLEL;



CREATE INDEX PARUS.I_DOCINPT_COMPANY_FK ON PARUS.DOCINPT
(COMPANY)
LOGGING
TABLESPACE PARUSIDX3
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          1200K
            MINEXTENTS       1
            MAXEXTENTS       2147483645
            PCTINCREASE      0
            FREELISTS        1
            FREELIST GROUPS  1
            BUFFER_POOL      DEFAULT
           )
NOPARALLEL;


CREATE INDEX PARUS.I_DOCOUTPT_AUTHID_FK ON PARUS.DOCOUTPT
(AUTHID)
LOGGING
TABLESPACE PARUSIDX3
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          1200K
            MINEXTENTS       1
            MAXEXTENTS       2147483645
            PCTINCREASE      0
            FREELISTS        1
            FREELIST GROUPS  1
            BUFFER_POOL      DEFAULT
           )
NOPARALLEL;


CREATE INDEX PARUS.I_DOCOUTPT_COMPANY_FK ON PARUS.DOCOUTPT
(COMPANY)
LOGGING
TABLESPACE PARUSIDX3
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          1200K
            MINEXTENTS       1
            MAXEXTENTS       2147483645
            PCTINCREASE      0
            FREELISTS        1
            FREELIST GROUPS  1
            BUFFER_POOL      DEFAULT
           )
NOPARALLEL;


