CREATE OR REPLACE TRIGGER T_DOCLINKS_BDELETE_REPL_ARH
before delete on DOCLINKS for each row
begin
/* регистрация события */
IF USER<>'SNP_REPL' THEN
  INSERT INTO PARUS.UPDATELIST (TABLENAME,TABLERN,AUTHID,MODIFDATE,OPERATION,NOTE)
  VALUES ('DOCLINKS',:OLD.RN,USER,SYSDATE,'D','?');
END IF;
end;
/

