CREATE UNIQUE INDEX PARUS.C_GOODSSUPPLY_UK ON PARUS.GOODSSUPPLY
(PRN, STORE)
LOGGING
TABLESPACE PARIDX
PCTFREE    10
INITRANS   6
MAXTRANS   255
STORAGE    (
            INITIAL          2640K
            MINEXTENTS       1
            MAXEXTENTS       2147483645
            PCTINCREASE      0
            FREELISTS        1
            FREELIST GROUPS  1
            BUFFER_POOL      DEFAULT
           )
NOPARALLEL;


