CREATE OR REPLACE TRIGGER "PARUS".T_MDLBOSPS_BINSERT
before insert on MDLBOSPS for each row
begin
/* регистрация события */
IF USER<>'SNP_REPL' THEN
  P_MDLBOSPS_IUD_EVENT(:new.RN, 'I',:new.PRN,
  :new.ACCOUNT_DEBIT,:new.ANALYTIC_DEBIT1,:new.ANALYTIC_DEBIT2,:new.ANALYTIC_DEBIT3,:new.ANALYTIC_DEBIT4,:new.ANALYTIC_DEBIT5,
  :new.ACCOUNT_CREDIT,:new.ANALYTIC_CREDIT1,:new.ANALYTIC_CREDIT2,:new.ANALYTIC_CREDIT3,:new.ANALYTIC_CREDIT4,:new.ANALYTIC_CREDIT5);
END IF;  
end;
/
