CREATE OR REPLACE PROCEDURE PARUS.PR_REPLICATE_DOCUMENT_SNP (pUNITCODE VARCHAR2, pTABLENAME VARCHAR2, pTABLERN NUMBER, pSELF NUMBER DEFAULT 1, pCOMMIT NUMBER DEFAULT 1) AS
BEGIN
  FOR lcur In ( SELECT /*+ RULE */ TABLENAME,MAX(UNITCODE) as UNITCODE FROM
  			    (
                  SELECT TABLENAME, UNITCODE FROM UNITTABL
				   WHERE (pUNITCODE||' '=' ' OR UNITCODE=pUNITCODE) AND
				         (pTABLENAME||' '=' ' OR TABLENAME=pTABLENAME)
				) GROUP BY TABLENAME
			  )
  LOOP
    -- Имитируем обновление самого документа
    IF pSELF=1 THEN
      /* регистрация события */
      INSERT INTO UPDATELIST (TABLENAME,TABLERN,AUTHID,MODIFDATE,OPERATION,NOTE)
      VALUES (lcur.TABLENAME,pTABLERN,USER,SYSDATE,'U','Имитация обновления');
	END IF;
	-- Имитируем обновление связей документа
	FOR lcur1 IN (SELECT /*+ RULE */ RN FROM DOCINPT WHERE UNITCODE=lcur.UNITCODE AND DOCUMENT=pTABLERN)
	LOOP
      /* регистрация события */
      INSERT INTO UPDATELIST (TABLENAME,TABLERN,AUTHID,MODIFDATE,OPERATION,NOTE)
      VALUES ('DOCINPT',lcur1.RN,USER,SYSDATE,'U','Имитация обновления');
	END LOOP;
	FOR lcur1 IN (SELECT /*+ RULE */ RN FROM DOCOUTPT WHERE UNITCODE=lcur.UNITCODE AND DOCUMENT=pTABLERN)
	LOOP
      /* регистрация события */
      INSERT INTO UPDATELIST (TABLENAME,TABLERN,AUTHID,MODIFDATE,OPERATION,NOTE)
      VALUES ('DOCOUTPT',lcur1.RN,USER,SYSDATE,'U','Имитация обновления');
	END LOOP;
	-- Имитируем обновление спецификаций документа
	-- Соглашения о взаимозачетах
	IF lcur.TABLENAME='AGREEMENT' THEN
	  FOR lcur1 IN (SELECT /*+ RULE */ RN FROM AGREEMENTS WHERE PRN=pTABLERN)
  	  LOOP
	    PR_REPLICATE_DOCUMENT_SNP ('','AGREEMENTS',lcur1.RN,1,pCOMMIT);
	  END LOOP;
	END IF;
	-- Банковские документы
	IF lcur.TABLENAME='BANKDOCS' THEN
	  FOR lcur1 IN (SELECT /*+ RULE */ DISTINCT PRN FROM BANKDOCSACC WHERE PRN=pTABLERN)
  	  LOOP
	    PR_REPLICATE_DOCUMENT_SNP ('','BANKDOCSACC',lcur1.PRN,1,pCOMMIT);
	  END LOOP;
	  FOR lcur1 IN (SELECT /*+ RULE */ RN FROM BANKDOCS_SUMM WHERE PRN=pTABLERN)
  	  LOOP
	    PR_REPLICATE_DOCUMENT_SNP ('','BANKDOCS_SUMM',lcur1.RN,1,pCOMMIT);
	  END LOOP;
	END IF;
	-- Цены реализации
	IF lcur.TABLENAME='RLPRICES' THEN
	  FOR lcur1 IN (SELECT /*+ RULE */ DISTINCT PRN FROM RLPRICESPECS WHERE PRN=pTABLERN)
  	  LOOP
	    PR_REPLICATE_DOCUMENT_SNP ('','RLPRICESPECS',lcur1.PRN,1,pCOMMIT);
	  END LOOP;
	END IF;
	-- Векселя
	IF lcur.TABLENAME='BILLASSACT' THEN
	  FOR lcur1 IN (SELECT /*+ RULE */ RN FROM BILLASSACTASS WHERE PRN=pTABLERN)
  	  LOOP
	    PR_REPLICATE_DOCUMENT_SNP ('','BILLASSACTASS',lcur1.RN,1,pCOMMIT);
	  END LOOP;
	  FOR lcur1 IN (SELECT /*+ RULE */ RN FROM BILLASSACTDOC WHERE PRN=pTABLERN)
  	  LOOP
	    PR_REPLICATE_DOCUMENT_SNP ('','BILLASSACTDOC',lcur1.RN,1,pCOMMIT);
	  END LOOP;
	  FOR lcur1 IN (SELECT /*+ RULE */ RN FROM BILLMOVEMENT WHERE ASSIGNMENT_ACT=pTABLERN)
  	  LOOP
	    PR_REPLICATE_DOCUMENT_SNP ('','BILLMOVEMENT',lcur1.RN,1,pCOMMIT);
	  END LOOP;
	END IF;
	IF lcur.TABLENAME='BILLCARD' THEN
	  FOR lcur1 IN (SELECT /*+ RULE */ RN FROM BILLMOVEMENT WHERE PRN=pTABLERN)
  	  LOOP
	    PR_REPLICATE_DOCUMENT_SNP ('','BILLMOVEMENT',lcur1.RN,1,pCOMMIT);
	  END LOOP;
	END IF;
	IF lcur.TABLENAME='BILLRECPACT' THEN
	  FOR lcur1 IN (SELECT /*+ RULE */ RN FROM BILLRECPACTASS WHERE PRN=pTABLERN)
  	  LOOP
	    PR_REPLICATE_DOCUMENT_SNP ('','BILLRECPACTASS',lcur1.RN,1,pCOMMIT);
	  END LOOP;
	  FOR lcur1 IN (SELECT /*+ RULE */ RN FROM BILLRECPACTDOC WHERE PRN=pTABLERN)
  	  LOOP
	    PR_REPLICATE_DOCUMENT_SNP ('','BILLRECPACTDOC',lcur1.RN,1,pCOMMIT);
	  END LOOP;
	  FOR lcur1 IN (SELECT /*+ RULE */ RN FROM BILLMOVEMENT WHERE RECEPTION_ACT=pTABLERN)
  	  LOOP
	    PR_REPLICATE_DOCUMENT_SNP ('','BILLMOVEMENT',lcur1.RN,1,pCOMMIT);
	  END LOOP;
	END IF;
	-- Кассовые документы
	IF lcur.TABLENAME='CASHDOCS' THEN
	  FOR lcur1 IN (SELECT /*+ RULE */ DISTINCT PRN FROM CASHDOCSACC WHERE PRN=pTABLERN)
  	  LOOP
	    PR_REPLICATE_DOCUMENT_SNP ('','CASHDOCSACC',lcur1.PRN,1,pCOMMIT);
	  END LOOP;
	  FOR lcur1 IN (SELECT /*+ RULE */ RN FROM CASHDOCS_SUMM WHERE PRN=pTABLERN)
  	  LOOP
	    PR_REPLICATE_DOCUMENT_SNP ('','CASHDOCS_SUMM',lcur1.RN,1,pCOMMIT);
	  END LOOP;
	END IF;
    -- Заказы потребителей
	IF lcur.TABLENAME='CONSUMERORD' THEN
	  FOR lcur1 IN (SELECT /*+ RULE */ RN FROM CONSUMERORDP WHERE PRN=pTABLERN)
  	  LOOP
	    PR_REPLICATE_DOCUMENT_SNP ('','CONSUMERORDP',lcur1.RN,1,pCOMMIT);
	  END LOOP;
	  FOR lcur1 IN (SELECT /*+ RULE */ RN FROM CONSUMERORDS WHERE PRN=pTABLERN)
  	  LOOP
	    PR_REPLICATE_DOCUMENT_SNP ('','CONSUMERORDS',lcur1.RN,1,pCOMMIT);
	  END LOOP;
	END IF;
	IF lcur.TABLENAME='CONSUMERORDP' THEN
	  FOR lcur1 IN (SELECT /*+ RULE */ RN FROM CONSUMERORDPS WHERE PERF=pTABLERN)
  	  LOOP
	    PR_REPLICATE_DOCUMENT_SNP ('','CONSUMERORDPS',lcur1.RN,1,pCOMMIT);
	  END LOOP;
	END IF;
	IF lcur.TABLENAME='CONSUMERORDS' THEN
	  FOR lcur1 IN (SELECT /*+ RULE */ RN FROM CONSUMERORDPS WHERE PRN=pTABLERN)
  	  LOOP
	    PR_REPLICATE_DOCUMENT_SNP ('','CONSUMERORDPS',lcur1.RN,1,pCOMMIT);
	  END LOOP;
	END IF;
	-- исходящие СФ
	IF lcur.TABLENAME='DICACCFO' THEN
	  FOR lcur1 IN (SELECT /*+ RULE */ RN FROM DICLACFO WHERE PRN=pTABLERN)
  	  LOOP
	    PR_REPLICATE_DOCUMENT_SNP ('','DICLACFO',lcur1.RN,1,pCOMMIT);
	  END LOOP;
	END IF;
	-- входящие СФ
	IF lcur.TABLENAME='DICACCFI' THEN
	  FOR lcur1 IN (SELECT /*+ RULE */ RN FROM DICLACFI WHERE PRN=pTABLERN)
  	  LOOP
	    PR_REPLICATE_DOCUMENT_SNP ('','DICLACFI',lcur1.RN,1,pCOMMIT);
	  END LOOP;
	END IF;
	-- Приходные партии
	IF lcur.TABLENAME='INCOMDOC' THEN
	  FOR lcur1 IN (SELECT /*+ RULE */ RN FROM GOODSPARTIES WHERE INDOC=pTABLERN)
  	  LOOP
	    PR_REPLICATE_DOCUMENT_SNP ('','GOODSPARTIES',lcur1.RN,1,pCOMMIT);
	  END LOOP;
	  FOR lcur1 IN (SELECT /*+ RULE */ RN FROM INCOMEFROMDEPS WHERE PARTY_RN=pTABLERN AND DOC_DATE>=TO_DATE('01.09.2004','dd.mm.yyyy'))
  	  LOOP
	    PR_REPLICATE_DOCUMENT_SNP ('','INCOMEFROMDEPS',lcur1.RN,1,pCOMMIT);
	  END LOOP;
	  FOR lcur1 IN (SELECT /*+ RULE */ RN FROM INORDERS WHERE PARTY=pTABLERN AND INDOCDATE>=TO_DATE('01.09.2004','dd.mm.yyyy'))
  	  LOOP
	    PR_REPLICATE_DOCUMENT_SNP ('','INORDERS',lcur1.RN,1,pCOMMIT);
	  END LOOP;
	END IF;
	-- партии
	IF lcur.TABLENAME='GOODSPARTIES' THEN
	  FOR lcur1 IN (SELECT /*+ RULE */ RN FROM GOODSSUPPLY WHERE PRN=pTABLERN)
  	  LOOP
	    PR_REPLICATE_DOCUMENT_SNP ('','GOODSSUPPLY',lcur1.RN,1,pCOMMIT);
	  END LOOP;
	  FOR lcur1 IN (SELECT /*+ RULE */ DISTINCT B.RN FROM PAYACC B, PAYACCSPECS A WHERE B.RN=A.PRN AND A.GOODSPARTY=pTABLERN AND B.ACCDATE>=TO_DATE('01.09.2004','dd.mm.yyyy'))
  	  LOOP
	    PR_REPLICATE_DOCUMENT_SNP ('','PAYACC',lcur1.RN,1,pCOMMIT);
	  END LOOP;
	  FOR lcur1 IN (SELECT /*+ RULE */ DISTINCT B.RN FROM SHEEPDIRSCUST B, SHEEPDIRSCUSTSPECS A WHERE B.RN=A.PRN AND A.GOODSPARTY=pTABLERN AND B.DOCDATE>=TO_DATE('01.09.2004','dd.mm.yyyy'))
  	  LOOP
	    PR_REPLICATE_DOCUMENT_SNP ('','SHEEPDIRSCUST',lcur1.RN,1,pCOMMIT);
	  END LOOP;
	  FOR lcur1 IN (SELECT /*+ RULE */ DISTINCT B.RN FROM SHEEPDIRSDEPT B, SHEEPDIRSDEPTSPECS A WHERE B.RN=A.PRN AND A.GOODSPARTY=pTABLERN AND B.DOCDATE>=TO_DATE('01.09.2004','dd.mm.yyyy'))
  	  LOOP
	    PR_REPLICATE_DOCUMENT_SNP ('','SHEEPDIRSDEPT',lcur1.RN,1,pCOMMIT);
	  END LOOP;
	  FOR lcur1 IN (SELECT /*+ RULE */ DISTINCT B.RN FROM TRANSINVCUST B, TRANSINVCUSTSPECS A WHERE B.RN=A.PRN AND A.GOODSPARTY=pTABLERN AND B.DOCDATE>=TO_DATE('01.09.2004','dd.mm.yyyy'))
  	  LOOP
	    PR_REPLICATE_DOCUMENT_SNP ('','TRANSINVCUST',lcur1.RN,1,pCOMMIT);
	  END LOOP;
	  FOR lcur1 IN (SELECT /*+ RULE */ DISTINCT B.RN FROM TRANSINVDEPT B, TRANSINVDEPTSPECS A WHERE B.RN=A.PRN AND A.GOODSPARTY=pTABLERN AND B.DOCDATE>=TO_DATE('01.09.2004','dd.mm.yyyy'))
  	  LOOP
	    PR_REPLICATE_DOCUMENT_SNP ('','TRANSINVDEPT',lcur1.RN,1,pCOMMIT);
	  END LOOP;
	END IF;
	-- Товарные запасы
	IF lcur.TABLENAME='GOODSSUPPLY' THEN
	  FOR lcur1 IN (SELECT /*+ RULE */ RN FROM REGPRICE WHERE PRN=pTABLERN)
  	  LOOP
	    PR_REPLICATE_DOCUMENT_SNP ('','REGPRICE',lcur1.RN,1,pCOMMIT);
	  END LOOP;
	  FOR lcur1 IN (SELECT /*+ RULE */ DISTINCT B.RN FROM INCOMEFROMDEPS B, INCOMEFROMDEPSSPEC A WHERE B.RN=A.PRN AND A.SUPPLY=pTABLERN AND B.DOC_DATE>=TO_DATE('01.09.2004','dd.mm.yyyy'))
  	  LOOP
	    PR_REPLICATE_DOCUMENT_SNP ('','INCOMEFROMDEPS',lcur1.RN,1,pCOMMIT);
	  END LOOP;
	  FOR lcur1 IN (SELECT /*+ RULE */ DISTINCT B.RN FROM INORDERS B, INORDERSPECS A WHERE B.RN=A.PRN AND A.GOODSSUPPLY=pTABLERN AND B.INDOCDATE>=TO_DATE('01.09.2004','dd.mm.yyyy'))
  	  LOOP
	    PR_REPLICATE_DOCUMENT_SNP ('','INORDERS',lcur1.RN,1,pCOMMIT);
	  END LOOP;
	  FOR lcur1 IN (SELECT /*+ RULE */ RN FROM RESJOURNAL WHERE SUPPLY=pTABLERN AND DOCDATE>=TO_DATE('01.09.2004','dd.mm.yyyy'))
  	  LOOP
	    PR_REPLICATE_DOCUMENT_SNP ('','RESJOURNAL',lcur1.RN,1,pCOMMIT);
	  END LOOP;
	  FOR lcur1 IN (SELECT /*+ RULE */ RN FROM STOREOPERJOURN WHERE GOODSSUPPLY=pTABLERN AND DOCDATE>=TO_DATE('01.09.2004','dd.mm.yyyy'))
  	  LOOP
	    PR_REPLICATE_DOCUMENT_SNP ('','STOREOPERJOURN',lcur1.RN,1,pCOMMIT);
	  END LOOP;
	  FOR lcur1 IN (SELECT /*+ RULE */ RN FROM STRPLOPRJRNL WHERE GOODSSUPPLY=pTABLERN AND DOCDATE>=TO_DATE('01.09.2004','dd.mm.yyyy'))
  	  LOOP
	    PR_REPLICATE_DOCUMENT_SNP ('','STRPLOPRJRNL',lcur1.RN,1,pCOMMIT);
	  END LOOP;
	  FOR lcur1 IN (SELECT /*+ RULE */ RN FROM STRPLRESJRNL WHERE GOODSSUPPLY=pTABLERN AND DOCDATE>=TO_DATE('01.09.2004','dd.mm.yyyy'))
  	  LOOP
	    PR_REPLICATE_DOCUMENT_SNP ('','STRPLRESJRNL',lcur1.RN,1,pCOMMIT);
	  END LOOP;
	  FOR lcur1 IN (SELECT /*+ RULE */ RN FROM STPLGOODSSUPPLY WHERE GOODSSUPPLY=pTABLERN)
  	  LOOP
	    PR_REPLICATE_DOCUMENT_SNP ('','STPLGOODSSUPPLY',lcur1.RN,1,pCOMMIT);
	  END LOOP;
	  FOR lcur1 IN (SELECT /*+ RULE */ DISTINCT B.RN FROM WROFFACTS B, WROFFACTSPECS A WHERE B.RN=A.PRN AND A.GOODSSUPPLY=pTABLERN AND B.DOCDATE>=TO_DATE('01.09.2004','dd.mm.yyyy'))
  	  LOOP
	    PR_REPLICATE_DOCUMENT_SNP ('','WROFFACTS',lcur1.RN,1,pCOMMIT);
	  END LOOP;
	END IF;
	-- Приходные ордера
	IF lcur.TABLENAME='INORDERS' THEN
	  FOR lcur1 IN (SELECT /*+ RULE */ RN FROM INORDERSPECS WHERE PRN=pTABLERN)
  	  LOOP
	    PR_REPLICATE_DOCUMENT_SNP ('','INORDERSPECS',lcur1.RN,1,pCOMMIT);
	  END LOOP;
	END IF;
	-- Приход из подразделений
	IF lcur.TABLENAME='INCOMEFROMDEPS' THEN
	  FOR lcur1 IN (SELECT /*+ RULE */ RN FROM INCOMEFROMDEPSSPEC WHERE PRN=pTABLERN)
  	  LOOP
	    PR_REPLICATE_DOCUMENT_SNP ('','INCOMEFROMDEPSSPEC',lcur1.RN,1,pCOMMIT);
	  END LOOP;
	END IF;
	-- Ведомости инвентаризации
	IF lcur.TABLENAME='RLINVSHEET' THEN
	  FOR lcur1 IN (SELECT /*+ RULE */ RN FROM RLINVSHEETSPEC WHERE PRN=pTABLERN)
  	  LOOP
	    PR_REPLICATE_DOCUMENT_SNP ('','RLINVSHEETSPEC',lcur1.RN,1,pCOMMIT);
	  END LOOP;
	END IF;
	-- Счета на оплату
	IF lcur.TABLENAME='PAYACC' THEN
	  FOR lcur1 IN (SELECT /*+ RULE */ RN FROM PAYACCSPECS WHERE PRN=pTABLERN)
  	  LOOP
	    PR_REPLICATE_DOCUMENT_SNP ('','PAYACCSPECS',lcur1.RN,1,pCOMMIT);
	  END LOOP;
	END IF;
	-- распоряжения на отгрузку потребителям
	IF lcur.TABLENAME='SHEEPDIRSCUST' THEN
	  FOR lcur1 IN (SELECT /*+ RULE */ RN FROM SHEEPDIRSCUSTSPECS WHERE PRN=pTABLERN)
  	  LOOP
	    PR_REPLICATE_DOCUMENT_SNP ('','SHEEPDIRSCUSTSPECS',lcur1.RN,1,pCOMMIT);
	  END LOOP;
	END IF;
	-- распоряжения на отгрузку в подразделения
	IF lcur.TABLENAME='SHEEPDIRSDEPT' THEN
	  FOR lcur1 IN (SELECT /*+ RULE */ RN FROM SHEEPDIRSDEPTSPECS WHERE PRN=pTABLERN)
  	  LOOP
	    PR_REPLICATE_DOCUMENT_SNP ('','SHEEPDIRSDEPTSPECS',lcur1.RN,1,pCOMMIT);
	  END LOOP;
	END IF;
	-- расходные накладные на отгрузку потребителям
	IF lcur.TABLENAME='TRANSINVCUST' THEN
	  FOR lcur1 IN (SELECT /*+ RULE */ RN FROM TRANSINVCUSTSPECS WHERE PRN=pTABLERN)
  	  LOOP
	    PR_REPLICATE_DOCUMENT_SNP ('','TRANSINVCUSTSPECS',lcur1.RN,1,pCOMMIT);
	  END LOOP;
	END IF;
	-- расходные накладные на отгрузку в подразделения
	IF lcur.TABLENAME='TRANSINVDEPT' THEN
	  FOR lcur1 IN (SELECT /*+ RULE */ RN FROM TRANSINVDEPTSPECS WHERE PRN=pTABLERN)
  	  LOOP
	    PR_REPLICATE_DOCUMENT_SNP ('','TRANSINVDEPTSPECS',lcur1.RN,1,pCOMMIT);
	  END LOOP;
	END IF;
	-- Товарные отчеты
	IF lcur.TABLENAME='SALESREPORTMAIN' THEN
	  FOR lcur1 IN (SELECT /*+ RULE */ RN FROM SALESREPORTDETAIL WHERE PRN=pTABLERN)
  	  LOOP
	    PR_REPLICATE_DOCUMENT_SNP ('','SALESREPORTDETAIL',lcur1.RN,1,pCOMMIT);
	  END LOOP;
	END IF;
	-- Акты оприходования/списания
	IF lcur.TABLENAME='WROFFACTS' THEN
	  FOR lcur1 IN (SELECT /*+ RULE */ RN FROM WROFFACTSPECS WHERE PRN=pTABLERN)
  	  LOOP
	    PR_REPLICATE_DOCUMENT_SNP ('','WROFFACTSPECS',lcur1.RN,1,pCOMMIT);
	  END LOOP;
	END IF;
	-- Лицевой счет
	IF lcur.TABLENAME='FACEACC' THEN
	  FOR lcur1 IN (SELECT /*+ RULE */ DISTINCT PRN FROM AGREEMENTS WHERE FACEACC_FROM=pTABLERN OR FACEACC_TO=pTABLERN)
  	  LOOP
	    PR_REPLICATE_DOCUMENT_SNP ('','AGREEMENT',lcur1.PRN,1,pCOMMIT);
	  END LOOP;
	  FOR lcur1 IN (SELECT /*+ RULE */ RN FROM BILLASSACT WHERE FACEACC=pTABLERN)
  	  LOOP
	    PR_REPLICATE_DOCUMENT_SNP ('','BILLASSACT',lcur1.RN,1,pCOMMIT);
	  END LOOP;
	  FOR lcur1 IN (SELECT /*+ RULE */ DISTINCT PRN FROM BILLASSACTDOC WHERE FACEACC=pTABLERN)
  	  LOOP
	    PR_REPLICATE_DOCUMENT_SNP ('','BILLASSACT',lcur1.PRN,1,pCOMMIT);
	  END LOOP;
	  FOR lcur1 IN (SELECT /*+ RULE */ RN FROM BILLRECPACT WHERE FACEACC=pTABLERN)
  	  LOOP
	    PR_REPLICATE_DOCUMENT_SNP ('','BILLRECPACT',lcur1.RN,1,pCOMMIT);
	  END LOOP;
	  FOR lcur1 IN (SELECT /*+ RULE */ DISTINCT PRN FROM BILLRECPACTDOC WHERE FACEACC=pTABLERN)
  	  LOOP
	    PR_REPLICATE_DOCUMENT_SNP ('','BILLRECPACT',lcur1.PRN,1,pCOMMIT);
	  END LOOP;
	  FOR lcur1 IN (SELECT /*+ RULE */ RN FROM CONSUMERORD WHERE FACEACC=pTABLERN)
  	  LOOP
	    PR_REPLICATE_DOCUMENT_SNP ('','CONSUMERORD',lcur1.RN,1,pCOMMIT);
	  END LOOP;
	  FOR lcur1 IN (SELECT /*+ RULE */ RN FROM INCOMEFROMDEPS WHERE OUT_FACEACC=pTABLERN)
  	  LOOP
	    PR_REPLICATE_DOCUMENT_SNP ('','INCOMEFROMDEPS',lcur1.RN,1,pCOMMIT);
	  END LOOP;
	  FOR lcur1 IN (SELECT /*+ RULE */ RN FROM INORDERS WHERE FACEACC=pTABLERN)
  	  LOOP
	    PR_REPLICATE_DOCUMENT_SNP ('','INORDERS',lcur1.RN,1,pCOMMIT);
	  END LOOP;
	  FOR lcur1 IN (SELECT /*+ RULE */ RN FROM LIABILITYNOTES WHERE FACEACC=pTABLERN)
  	  LOOP
	    PR_REPLICATE_DOCUMENT_SNP ('','LIABILITYNOTES',lcur1.RN,1,pCOMMIT);
	  END LOOP;
	  FOR lcur1 IN (SELECT /*+ RULE */ RN FROM PAYACC WHERE FACEACC=pTABLERN)
  	  LOOP
	    PR_REPLICATE_DOCUMENT_SNP ('','PAYACC',lcur1.RN,1,pCOMMIT);
	  END LOOP;
	  FOR lcur1 IN (SELECT /*+ RULE */ RN FROM PAYNOTES WHERE FACEACC=pTABLERN OR PAYER_ACC=pTABLERN)
  	  LOOP
	    PR_REPLICATE_DOCUMENT_SNP ('','PAYNOTES',lcur1.RN,1,pCOMMIT);
	  END LOOP;
	  FOR lcur1 IN (SELECT /*+ RULE */ DISTINCT PRN FROM SALESREPORTDETAIL WHERE FACEACC=pTABLERN)
  	  LOOP
	    PR_REPLICATE_DOCUMENT_SNP ('','SALESREPORTMAIN',lcur1.PRN,1,pCOMMIT);
	  END LOOP;
	  FOR lcur1 IN (SELECT /*+ RULE */ RN FROM SHEEPDIRSDEPT WHERE FACEACC=pTABLERN)
  	  LOOP
	    PR_REPLICATE_DOCUMENT_SNP ('','SHEEPDIRSDEPT',lcur1.RN,1,pCOMMIT);
	  END LOOP;
	  FOR lcur1 IN (SELECT /*+ RULE */ RN FROM SHEEPDIRSCUST WHERE FACEACC=pTABLERN)
  	  LOOP
	    PR_REPLICATE_DOCUMENT_SNP ('','SHEEPDIRSCUST',lcur1.RN,1,pCOMMIT);
	  END LOOP;
	  FOR lcur1 IN (SELECT /*+ RULE */ RN FROM TRANSINVCUST WHERE FACEACC=pTABLERN)
  	  LOOP
	    PR_REPLICATE_DOCUMENT_SNP ('','TRANSINVCUST',lcur1.RN,1,pCOMMIT);
	  END LOOP;
	  FOR lcur1 IN (SELECT /*+ RULE */ RN FROM TRANSINVDEPT WHERE FACEACC=pTABLERN)
  	  LOOP
	    PR_REPLICATE_DOCUMENT_SNP ('','TRANSINVDEPT',lcur1.RN,1,pCOMMIT);
	  END LOOP;

    END IF;
	-- Склад
	IF lcur.TABLENAME='AZSAZSLISTMT' THEN
--	  FOR lcur1 IN (SELECT /*+ RULE */ DISTINCT B.INDOC FROM GOODSSUPPLY A,GOODSPARTIES B WHERE A.PRN=B.RN AND A.STORE=pTABLERN)
--  	  LOOP
--	    PR_REPLICATE_DOCUMENT_SNP ('','INCOMDOC',lcur1.INDOC,1,pCOMMIT);
--	  END LOOP;
--	  FOR lcur1 IN (SELECT /*+ RULE */ DISTINCT B.RN FROM GOODSSUPPLY A,GOODSPARTIES B WHERE A.PRN=B.RN AND A.STORE=pTABLERN)
--  	  LOOP
--        PR_REPLICATE_DOCUMENT_SNP ('','GOODSPARTIES',lcur1.RN,1,pCOMMIT);
--	  END LOOP;
	  FOR lcur1 IN (SELECT /*+ RULE */ RN FROM WROFFACTS WHERE STORE=pTABLERN)
  	  LOOP
	    PR_REPLICATE_DOCUMENT_SNP ('','WROFFACTS',lcur1.RN,1,pCOMMIT);
	  END LOOP;
	  FOR lcur1 IN (SELECT /*+ RULE */ RN FROM TRANSINVCUST WHERE STORE=pTABLERN AND DOCDATE>=TO_DATE('01.09.2004','dd.mm.yyyy'))
  	  LOOP
	    PR_REPLICATE_DOCUMENT_SNP ('','TRANSINVCUST',lcur1.RN,1,pCOMMIT);
	  END LOOP;
	  FOR lcur1 IN (SELECT /*+ RULE */ RN FROM TRANSINVDEPT WHERE STORE=pTABLERN AND DOCDATE>=TO_DATE('01.09.2004','dd.mm.yyyy'))
  	  LOOP
	    PR_REPLICATE_DOCUMENT_SNP ('','TRANSINVDEPT',lcur1.RN,1,pCOMMIT);
	  END LOOP;
	  FOR lcur1 IN (SELECT /*+ RULE */ RN FROM SHEEPDIRSCUST WHERE STORE=pTABLERN AND DOCDATE>=TO_DATE('01.09.2004','dd.mm.yyyy'))
  	  LOOP
	    PR_REPLICATE_DOCUMENT_SNP ('','SHEEPDIRSCUST',lcur1.RN,1,pCOMMIT);
	  END LOOP;
	  FOR lcur1 IN (SELECT /*+ RULE */ RN FROM SHEEPDIRSDEPT WHERE STORE=pTABLERN AND DOCDATE>=TO_DATE('01.09.2004','dd.mm.yyyy'))
  	  LOOP
	    PR_REPLICATE_DOCUMENT_SNP ('','SHEEPDIRSDEPT',lcur1.RN,1,pCOMMIT);
	  END LOOP;
	  FOR lcur1 IN (SELECT /*+ RULE */ RN FROM SALESREPORTMAIN WHERE RPT_UNIT=pTABLERN AND RPT_DATE>=TO_DATE('01.09.2004','dd.mm.yyyy'))
  	  LOOP
	    PR_REPLICATE_DOCUMENT_SNP ('','SALESREPORTMAIN',lcur1.RN,1,pCOMMIT);
	  END LOOP;
	  FOR lcur1 IN (SELECT /*+ RULE */ RN FROM PAYACC WHERE STORE=pTABLERN AND ACCDATE>=TO_DATE('01.09.2004','dd.mm.yyyy'))
  	  LOOP
	    PR_REPLICATE_DOCUMENT_SNP ('','PAYACC',lcur1.RN,1,pCOMMIT);
	  END LOOP;
	  FOR lcur1 IN (SELECT /*+ RULE */ DISTINCT PRN FROM PAYACCSPECS WHERE STORE=pTABLERN)
  	  LOOP
	    PR_REPLICATE_DOCUMENT_SNP ('','PAYACC',lcur1.PRN,1,pCOMMIT);
	  END LOOP;
	  FOR lcur1 IN (SELECT /*+ RULE */ RN FROM INORDERS WHERE STORE=pTABLERN AND INDOCDATE>=TO_DATE('01.09.2004','dd.mm.yyyy'))
  	  LOOP
	    PR_REPLICATE_DOCUMENT_SNP ('','INORDERS',lcur1.RN,1,pCOMMIT);
	  END LOOP;
	  FOR lcur1 IN (SELECT /*+ RULE */ RN FROM INCOMEFROMDEPS WHERE (STORE=pTABLERN OR OUT_STORE=pTABLERN) AND DOC_DATE>=TO_DATE('01.09.2004','dd.mm.yyyy'))
  	  LOOP
	    PR_REPLICATE_DOCUMENT_SNP ('','INCOMEFROMDEPS',lcur1.RN,1,pCOMMIT);
	  END LOOP;
	  FOR lcur1 IN (SELECT /*+ RULE */ RN FROM DICACCFO WHERE PR_SENDER_CODE=pTABLERN AND ACC_DATE>=TO_DATE('01.09.2004','dd.mm.yyyy'))
  	  LOOP
	    PR_REPLICATE_DOCUMENT_SNP ('','DICACCFO',lcur1.RN,1,pCOMMIT);
	  END LOOP;
	  FOR lcur1 IN (SELECT /*+ RULE */ RN FROM CONSUMERORD WHERE STORE=pTABLERN AND ORD_DATE>=TO_DATE('01.09.2004','dd.mm.yyyy'))
  	  LOOP
	    PR_REPLICATE_DOCUMENT_SNP ('','CONSUMERORD',lcur1.RN,1,pCOMMIT);
	  END LOOP;
	  FOR lcur1 IN (SELECT /*+ RULE */ DISTINCT B.RN FROM CONSUMERORD B, CONSUMERORDS A WHERE B.RN=A.PRN AND A.STORE=pTABLERN AND B.ORD_DATE>=TO_DATE('01.09.2004','dd.mm.yyyy'))
  	  LOOP
	    PR_REPLICATE_DOCUMENT_SNP ('','CONSUMERORD',lcur1.RN,1,pCOMMIT);
	  END LOOP;
	END IF;

  END LOOP;

  -- COMMIT
  IF pCOMMIT=1 THEN
    COMMIT;
  END IF;
END;
/
