CREATE OR REPLACE TRIGGER "PARUS".T_UPDATELIST_BINSERT
before insert on UPDATELIST for each row
begin
if ( :new.RN is null ) then
:new.RN := GEN_UPDATELIST_ID;
end if;
:new.OSUSER := GET_SESSION_OSUSER;
:new.MACHINE := GET_SESSION_MACHINE;
:new.TERMINAL := GET_SESSION_TERMINAL;
:new.PROGRAM := GET_SESSION_PROGRAM;
if :new.NOTE||' '=' ' or :new.NOTE IS NULL THEN
  :new.NOTE:='?';
end if;  
end;
/

drop index PARUS.I_UPDATELIST_AUTHID;
/

drop index PARUS.I_UPDATELIST_MODIFDATE;
/

drop index PARUS.I_UPDATELIST_TABLENAME;
/

CREATE INDEX PARUS.I_UPDATELIST_TABLE_RN_DATE ON PARUS.UPDATELIST
(TABLENAME, TABLERN, MODIFDATE)
LOGGING
TABLESPACE PARIDX
/

CREATE INDEX PARUS.I_UPDATELIST_DATE ON PARUS.UPDATELIST
(MODIFDATE)
LOGGING
TABLESPACE PARIDX
/
