  SELECT
    month_num AS COL_SORT,  
    'Месяц' AS COL_X1_NAME,
    month_str AS COL_X1_VALUE,  
    'АИ-98' AS COL_Y1_NAME, 
    SUM(ves98) AS COL_Y1_VALUE,
    'АИ-95' AS COL_Y2_NAME, 
    SUM(ves95) AS COL_Y2_VALUE,
    'АИ-92' AS COL_Y3_NAME, 
    SUM(ves92) AS COL_Y3_VALUE,
    'АИ-80' AS COL_Y4_NAME, 
    SUM(ves80) AS COL_Y4_VALUE,
    'ДТ' AS COL_Y5_NAME, 
    SUM(dt) AS COL_Y5_VALUE,
    'ГАЗ' AS COL_Y6_NAME, 
    SUM(GAS) AS COL_Y6_VALUE,
	' на '||:DATE_END,
	:cPRIM
  FROM 
  (
    SELECT
      TO_CHAR(OBOROT_KONS.DATE_OPER,'YYYYMM') AS month_num,
      TO_CHAR(OBOROT_KONS.DATE_OPER,'Month YY') AS month_str,
      SUM(CASE
	        WHEN grp.GROUP_ABBR='АИ-98' THEN OBOROT_KONS.KG/1000
			ELSE 0
		  END) AS Ves98,
      SUM(CASE
	        WHEN grp.GROUP_ABBR='АИ-95' THEN OBOROT_KONS.KG/1000
			ELSE 0
		  END) AS Ves95,
      SUM(CASE
	        WHEN grp.GROUP_ABBR='АИ-92' THEN OBOROT_KONS.KG/1000
			ELSE 0
		  END) AS Ves92,
      SUM(CASE
	        WHEN grp.GROUP_ABBR='АИ-80' THEN OBOROT_KONS.KG/1000
			ELSE 0
		  END) AS Ves80,
      SUM(CASE
	        WHEN grp.GROUP_ABBR='ДТ' THEN OBOROT_KONS.KG/1000
			ELSE 0
		  END) AS DT,
      SUM(CASE
	        WHEN grp.GROUP_ABBR='ГАЗ' THEN OBOROT_KONS.KG/1000
			ELSE 0
		  END) AS GAS
    FROM OBOROT_KONS, KLS_PROD_KONS,KLS_PROD_GR_KONS,ORG_STRUCTURE,KLS_ORG_KIND,
	     KLS_PROD_KONS_GROUPS_DESC grp9, KLS_PROD_GR2GR_DESC grp11, KLS_PROD_GROUPS grp 
    WHERE OBOROT_KONS.TIP_OP_ID=:nTIP_OP -- тип операции
	  AND OBOROT_KONS.TIP_REAL_ID<>2 
	  AND OBOROT_KONS.VID_REAL_ID<>5
	  AND OBOROT_KONS.PROD_KONS_ID=KLS_PROD_KONS.ID
	  AND KLS_PROD_KONS.ID=grp9.PROD_KONS_ID
	  AND grp9.PROD_GROUPS_ID=grp11.PROD_GROUPS_ID_1
	  AND grp11.PROD_TYPE_GRP_ID_1=9
	  AND grp11.PROD_TYPE_GRP_ID_2=11
	  AND grp11.PROD_GROUPS_ID_2=grp.ID
	  AND KLS_PROD_KONS.GR_KONS_ID=KLS_PROD_GR_KONS.ID_GR
	  AND OBOROT_KONS.ORG_STRU_ID=ORG_STRUCTURE.ID
	  AND ORG_STRUCTURE.ORG_KIND_ID=KLS_ORG_KIND.ID
--	  AND (KLS_ORG_KIND.GROUP_KIND_ID=NVL(:nORG_KIND_GRP,KLS_ORG_KIND.GROUP_KIND_ID)) -- тип объекта	 
	  AND OBOROT_KONS.DATE_OPER>:dDATE_BEG-1 
	  AND OBOROT_KONS.DATE_OPER<:dDATE_END+1
--	  AND (OBOROT_KONS.FILIAL_ID=NVL(:nFILIAL,OBOROT_KONS.FILIAL_ID)) -- филиал 
--	  AND (OBOROT_KONS.ORG_STRU_ID=NVL(:nAZC,OBOROT_KONS.ORG_STRU_ID)) -- подразделение (АЗС)	 
--	  AND (KLS_PROD_GR_KONS.ID_GLOBAL_GR=NVL(:cPROD_GR,KLS_PROD_GR_KONS.ID_GLOBAL_GR)) -- группа продуктов
--	  AND (grp9.PROD_GROUPS_ID=NVL(:nPROD,grp9.PROD_GROUPS_ID)) -- продукт
    GROUP BY 
      TO_CHAR(OBOROT_KONS.DATE_OPER,'YYYYMM'),
      TO_CHAR(OBOROT_KONS.DATE_OPER,'Month YY')  
  ) oborot 
  GROUP BY
    month_num,  
    month_str;  
