SELECT 
  TO_CHAR(BILLS.DATE_KVIT,'MM') AS MON, 
  Rusmonth(BILLS.DATE_KVIT) AS MON_DATE, 
  plat.PREDPR_NAME AS plat_NAME,
  KLS_REGION.REGION_NAME,
  poluch.PREDPR_NAME AS poluch_NAME,
  KLS_PROD.LONG_NAME_NPR,
  BILLS.KOL_DN,
  SUM(BILL_POS.VES) AS VES,
  ROUND(BILL_POS.CENA_BN*1.2,2) AS cena
FROM MONTH,BILLS,BILL_POS,KLS_PREDPR poluch, KLS_PREDPR plat,KLS_REGION,KLS_PROD,KLS_DOG
WHERE MONTH.nom_zd=BILLS.nom_zd
AND BILLS.nom_dok=BILL_POS.nom_dok
AND date_kvit>=TO_DATE('01.01.2002','dd.mm.yyyy') 
AND date_kvit<=TO_DATE('31.12.2002','dd.mm.yyyy')
AND MONTH.planstru_id IN (95)
AND MONTH.poluch_id=poluch.ID
AND MONTH.dog_id=KLS_DOG.ID
AND KLS_DOG.predpr_id=plat.ID
AND poluch.REGION_ID=KLS_REGION.ID
AND BILLS.PROD_ID_NPR=KLS_PROD.ID_NPR
AND BILL_POS.BILL_POS_ID<10
GROUP BY
  TO_CHAR(BILLS.DATE_KVIT,'MM'), 
  Rusmonth(BILLS.DATE_KVIT), 
  plat.PREDPR_NAME,
  KLS_REGION.REGION_NAME,
  poluch.PREDPR_NAME,
  KLS_PROD.LONG_NAME_NPR,
  BILLS.KOL_DN,
  BILL_POS.CENA_BN

