SELECT 'UPDATE SF_POZ_PROD SET MATNR='''||P.MATNR||''', MATNK='||P.KSSS_PROD_ID||' WHERE KOD_TU=6 AND ID_POZ_PROD='||TO_CHAR(SP.ID_POZ_PROD)||';'
FROM SF_POZ_PROD SP,MASTER.KSSS_PROD P
WHERE SP.ID_NFPROD=P.FOX_ID(+)
  AND SP.DATE_OTGR>=TO_DATE('01.10.2003','dd.mm.yyyy')