SELECT AAA.MON_DATE,AAA.PLAT_NAME,BBB.REGION_NAME,AAA.POLUCH_NAME,AAA.PRODUCT_NAME,AAA.PAYTYPE_NAME,AAA.VES_TN,AAA.POKUP_PRICE,AAA.REALIZ_PRICE,AAA.TIP_TRANSP
FROM
(
SELECT MON_DATE,PLAT_NAME,KEY_NAME,POLUCH_NAME,PRODUCT_NAME,PAYTYPE_NAME,SUM(VES_TN) AS VES_TN,POKUP_PRICE,REALIZ_PRICE,TIP_TRANSP
FROM
(

SELECT produ.AGNNAME, RusMonth(t.DOCDATE) AS MON_DATE,a.AGNNAME AS PLAT_NAME,f.NAME AS POLUCH_NAME,NamePoluchReady(f.NAME) AS KEY_NAME,n.NOMEN_NAME AS PRODUCT_NAME,pt.GSMPAYMENTS_MNEMO AS PAYTYPE_NAME,
	   ts.QUANTALT/1000 AS VES_TN,ROUND(rp.PRICE*1.2*1000,2) AS POKUP_PRICE,ROUND(ts.PRICE*1000,2) AS REALIZ_PRICE,
	   so.GSMWAYS_MNEMO AS TIP_TRANSP
FROM agnlist a,AGNFIFO f,transinvcust t,transinvcustspecs ts,dicnomns n,nommodif m,AZSGSMPAYMENTSTYPES pt,faceacc fa,
	 GOODSPARTIES gp,GOODSSUPPLY gs,REGPRICE rp,AZSAZSLISTMT skl,AZSGSMWAYSTYPES so, INCOMDOC in_doc, AGNLIST produ
WHERE t.RN=ts.PRN AND t.AGENT=a.RN AND t.AGNFIFO=f.RN(+) AND ts.NOMMODIF=m.RN AND m.PRN=n.RN 
  AND t.PAYTYPE=pt.RN AND n.NOMEN_TYPE=1 AND t.FACEACC=fa.RN AND fa.FCACGR=47683468
  AND (gs.STORE=t.STORE OR gs.STORE IS NULL) 
  AND ts.GOODSPARTY=gp.RN(+) AND gp.RN=gs.PRN(+) AND gs.RN=rp.PRN(+) 
  AND (gp.NOMMODIF=ts.NOMMODIF OR gp.NOMMODIF IS NULL)
  AND (rp.ADATE=t.DOCDATE OR rp.ADATE IS NULL) 
  AND t.STORE=skl.RN AND trim(skl.AZS_NUMBER) IN ('ÀÐÕÀÍ_ÒÐÀÍÇÈÒ_ÍÀËÈÂ'/*,'ÓÕÒÈÍÑÊÀß_ÍÁ','ÓÕÒÀ_ÖÀ','Àâòîíàëèâ'*/) 
  AND t.STOPER=so.RN /*AND trim(so.GSMWAYS_MNEMO) IN ('ÐÅÀË_ÒÐÀÍÇÈÒ','ÐÅÀË_ÀÂÒÎÍ','ÀÐÕ_ÒÐÀÍÇÈÒ')*/
  AND t.DOCDATE>=TO_DATE('01.01.2002','dd.mm.yyyy') AND t.DOCDATE<=TO_DATE('31.12.2002','dd.mm.yyyy')
  AND gp.INDOC = in_doc.RN (+)
  AND in_doc.AGENT=produ.RN (+)

)
GROUP BY MON_DATE,PLAT_NAME,POLUCH_NAME,PRODUCT_NAME,PAYTYPE_NAME,POKUP_PRICE,REALIZ_PRICE,TIP_TRANSP
) AAA,
(
SELECT MAX(BB.REGION_NAME) AS REGION_NAME,AA.NAME AS KEY_NAME
FROM
(
SELECT DISTINCT NamePoluchReady(f.NAME) AS NAME,f.NAME AS orig_name 
FROM agnlist a,AGNFIFO f,transinvcust t,transinvcustspecs ts,dicnomns n,nommodif m,AZSGSMPAYMENTSTYPES pt,faceacc fa,
	 GOODSPARTIES gp,GOODSSUPPLY gs,REGPRICE rp,AZSAZSLISTMT skl,AZSGSMWAYSTYPES so
WHERE t.RN=ts.PRN AND t.AGENT=a.RN AND t.AGNFIFO=f.RN(+) AND ts.NOMMODIF=m.RN AND m.PRN=n.RN 
  AND t.PAYTYPE=pt.RN AND n.NOMEN_TYPE=1 AND t.FACEACC=fa.RN AND fa.FCACGR=47683468
  AND (gs.STORE=t.STORE OR gs.STORE IS NULL) 
  AND ts.GOODSPARTY=gp.RN(+) AND gp.RN=gs.PRN(+) AND gs.RN=rp.PRN(+) 
  AND (gp.NOMMODIF=ts.NOMMODIF OR gp.NOMMODIF IS NULL)
  AND (rp.ADATE=t.DOCDATE OR rp.ADATE IS NULL) 
  AND t.STORE=skl.RN AND trim(skl.AZS_NUMBER) IN ('ÓÕÒÈÍÑÊÀß_ÍÁ','ÓÕÒÀ_ÖÀ','Àâòîíàëèâ')
  AND t.STOPER=so.RN AND trim(so.GSMWAYS_MNEMO) IN ('ÐÅÀË_ÒÐÀÍÇÈÒ','ÐÅÀË_ÀÂÒÎÍ')
  AND t.DOCDATE>=TO_DATE('01.01.2002','dd.mm.yyyy') AND t.DOCDATE<=TO_DATE('31.12.2002','dd.mm.yyyy')
) AA,
(  
SELECT NamePoluchReady(A.PREDPR_NAME) AS NAME,A.PREDPR_NAME, B.REGION_NAME FROM 
MASTER.KLS_PREDPR@buh.world A,MASTER.KLS_REGION@buh.world B WHERE A.REGION_ID=B.ID
ORDER BY 1
) BB
WHERE AA.NAME=BB.NAME(+)
GROUP BY AA.NAME
) BBB
WHERE AAA.KEY_NAME=BBB.KEY_NAME(+)