-- BILL и R3_BILLS - сравнение сумм
SELECT DISTINCT
KLS_PREDPR.PREDPR_NAME,
KLS_DOG.DOG_NUMBER,
BILLS.NOM_SF,
BILLS.DATE_VYP_SF,
BILLS.luk_summa_dok,
R3_BILLS.VBELN,
R3_BILLS.nom_r3,
R3_BILLS.NOM_SF,
R3_BILLS.summa_dok
--KVIT.NUM_KVIT,
--KVIT.SVED_NUM,
--KVIT.DATE_KVIT
FROM R3_BILLS,BILLS,KLS_PREDPR,KLS_DOG,KVIT 
WHERE BILLS.nom_dok=R3_BILLS.nom_dok(+) 
AND BILLS.date_kvit>=TO_DATE('01.02.2003','dd.mm.yyyy') 
AND BILLS.date_kvit<=TO_DATE('10.02.2003','dd.mm.yyyy')
AND BILLS.DOG_ID<>1221
AND BILLS.NAZN_OTG_ID<>10 
AND ABS(BILLS.luk_summa_dok-NVL(R3_BILLS.summa_dok,0))<>0
AND BILLS.DOG_ID=KLS_DOG.ID
AND KLS_DOG.PREDPR_ID=KLS_PREDPR.ID
AND KVIT.BILL_ID=BILLS.NOM_DOK
ORDER BY 
KLS_DOG.DOG_NUMBER,
BILLS.NOM_SF

-- Все BILLS
SELECT 
* 
FROM BILLS 
WHERE BILLS.date_kvit>=TO_DATE('01.01.2003','dd.mm.yyyy') 
AND BILLS.date_kvit<=TO_DATE('31.01.2003','dd.mm.yyyy')
AND BILLS.DOG_ID<>1221
AND BILLS.NAZN_OTG_ID<>10 

-- BILLS и SVETA
SELECT A.*,R3_BILLS.nom_r3,R3_BILLS.VBELN,R3_BILLS.NOM_DOK,R3_BILLS.SUMMA_DOK FROM R3_BILLS,
(SELECT BILLS.DATE_KVIT,BILLS.NOM_SF,BILLS.DOG_ID,AP.KOD_PROD AS NOM_DOK, SUM(AP.KOL) AS VES, MAX(AP.CENA) AS CENA, 
SUM(AP.allnds) AS summa_dok,ASF.SCHETF FROM SVETA.SF_POZ_PROD AP,BILLS,SVETA.SF_SFAK_PROD ASF 
WHERE AP.LOADATE=TO_DATE('14.02.2003','dd.mm.yyyy')
  AND AP.KOD_PROD=BILLS.NOM_DOK
  AND AP.KOD_PROD=ASF.KOD_PROD 
GROUP BY BILLS.DATE_KVIT,AP.KOD_PROD,BILLS.NOM_SF,BILLS.DOG_ID,ASF.SCHETF
) A
WHERE A.nom_dok=R3_BILLS.nom_dok(+)
AND ABS(A.summa_dok-NVL(R3_BILLS.summa_dok,0))<>0
ORDER BY R3_BILLS.nom_r3,A.nom_dok

-- BILLS и SVETA - номера
SELECT A.*,R3_BILLS.nom_r3,R3_BILLS.VBELN,R3_BILLS.NOM_DOK,R3_BILLS.SUMMA_DOK FROM R3_BILLS,
(
SELECT BILLS.DATE_KVIT,BILLS.NOM_SF,BILLS.DOG_ID,AP.KOD_PROD AS NOM_DOK, SUM(AP.KOL) AS VES, MAX(AP.CENA) AS CENA, 
SUM(AP.allnds) AS summa_dok,ASF.SCHETF FROM SVETA.SF_POZ_PROD AP,BILLS,SVETA.SF_SFAK_PROD ASF 
WHERE AP.LOADATE=TO_DATE('05.02.2003','dd.mm.yyyy')
  AND AP.KOD_PROD=BILLS.NOM_DOK
  AND AP.KOD_PROD=ASF.KOD_PROD 
GROUP BY BILLS.DATE_KVIT,AP.KOD_PROD,BILLS.NOM_SF,BILLS.DOG_ID,ASF.SCHETF
) A
WHERE A.nom_dok=R3_BILLS.nom_dok(+)
AND A.SCHETF<>R3_BILLS.NOM_R3
ORDER BY R3_BILLS.nom_r3,A.nom_dok

-- BILLS и SVETA - цены 
SELECT A.*,B.nom_r3,B.VBELN,B.NOM_DOK,B.SUMMA_DOK,B.CENA_BN FROM  
(
SELECT R3_BILLS.nom_r3,R3_BILLS.VBELN,R3_BILLS.NOM_DOK,R3_BILLS.SUMMA_DOK,R3_BILL_POS.cena_bn
   FROM R3_BILLS,R3_BILL_POS
  WHERE R3_BILLS.VBELN=R3_BILL_POS.VBELN
    AND R3_BILL_POS.R3_BILL_POS_ID=1
) B,   
(
SELECT BILLS.DATE_KVIT,BILLS.NOM_SF,BILLS.DOG_ID,KOD_PROD AS NOM_DOK, SUM(KOL) AS VES, MAX(CENA) AS CENA, 
SUM(allnds) AS summa_dok FROM SVETA.SF_POZ_PROD,BILLS 
WHERE KOD_PROD=BILLS.NOM_DOK
  AND LOADATE>=TO_DATE('01.01.2003','dd.mm.yyyy')
GROUP BY BILLS.DATE_KVIT,KOD_PROD,BILLS.NOM_SF,BILLS.DOG_ID
) A
WHERE A.nom_dok=B.nom_dok(+)
AND ABS(A.cena-NVL(B.cena_bn,0))<>0
ORDER BY B.nom_r3,A.nom_dok


-- BILLS и R3_BILLS - цены
SELECT A.*,B.nom_r3,B.VBELN,B.NOM_DOK,B.SUMMA_DOK,B.CENA_BN FROM  
(
SELECT R3_BILLS.nom_r3,R3_BILLS.VBELN,R3_BILLS.NOM_DOK,R3_BILLS.SUMMA_DOK,R3_BILL_POS.cena_bn
   FROM R3_BILLS,R3_BILL_POS
  WHERE R3_BILLS.VBELN=R3_BILL_POS.VBELN
    AND R3_BILL_POS.R3_BILL_POS_ID=1
) B,   
(
SELECT BILLS.DATE_KVIT,BILLS.NOM_SF,BILLS.DOG_ID,BILLS.NOM_DOK,SUM(BILL_POS.VES) AS VES, MAX(BILL_POS.CENA_BN) AS CENA, 
SUM(BILL_POS.summa) AS summa_dok FROM BILL_POS,BILLS 
WHERE BILL_POS.NOM_DOK=BILLS.NOM_DOK
  AND BILLS.DATE_MOS>=TO_DATE('01.01.2003','dd.mm.yyyy')
  AND BILLS.DOG_ID<>1221 
  AND BILLS.NAZN_OTG_ID<>10 
GROUP BY BILLS.DATE_KVIT,BILLS.NOM_DOK,BILLS.NOM_SF,BILLS.DOG_ID
) A
WHERE A.nom_dok=B.nom_dok(+)
AND ABS(A.cena-NVL(B.cena_bn,0))<>0
ORDER BY B.nom_r3,A.nom_dok



-- BILLS и SVETA
SELECT BILLS.DATE_KVIT,BILLS.NOM_SF,BILLS.DOG_ID,BILLS.NOM_DOK,BILLS.LUK_SUMMA_DOK,A.* FROM 
(SELECT 
AP.KOD_PROD AS NOM_DOK, SUM(AP.KOL) AS VES, MAX(AP.CENA) AS CENA, 
SUM(AP.allnds) AS summa_dok,ASF.SCHETF FROM SVETA.SF_POZ_PROD AP,SVETA.SF_SFAK_PROD ASF 
WHERE AP.DATE_OTGR>=TO_DATE('01.02.2003','dd.mm.yyyy')
  AND AP.KOD_PROD=ASF.KOD_PROD 
GROUP BY AP.KOD_PROD,ASF.SCHETF
) A, BILLS
WHERE ABS(A.summa_dok-BILLS.luk_summa_dok)<>0
  AND A.NOM_DOK=BILLS.NOM_DOK
ORDER BY A.nom_dok


-- BILLS и SVETA
SELECT BILLS.DATE_KVIT,BILLS.NOM_SF,BILLS.DOG_ID,BILLS.NOM_DOK,BILLS.LUK_SUMMA_DOK,A.* FROM 
(SELECT 
AP.KOD_PROD AS NOM_DOK, SUM(AP.KOL) AS VES, MAX(AP.CENA) AS CENA, 
SUM(AP.allnds) AS summa_dok,ASF.SCHETF FROM SVETA.SF_POZ_PROD AP,SVETA.SF_SFAK_PROD ASF 
WHERE AP.LOADATE=TO_DATE('17.03.2003','dd.mm.yyyy')
  AND AP.KOD_PROD=ASF.KOD_PROD
  AND ASF.LINKSCHF||' '=' ' 
GROUP BY AP.KOD_PROD,ASF.SCHETF
) A, BILLS
WHERE A.NOM_DOK=BILLS.NOM_DOK
  AND BILLS.SUMMA_DOK<0
ORDER BY A.nom_dok



