-- Запросы для плана реализации и сводного плана поставки
-- Список поставщиков
SELECT * FROM KLS_PREDPR
WHERE EXISTS
(SELECT NULL
  FROM PREDPR_ROLE A 
  WHERE A.PREDPR_ID=KLS_PREDPR.ID 
    AND A.KLS_ROLE_ID=4)

-- Тип реализации
SELECT * FROM KLS_TIP_REAL_KONS WHERE ID IN (1,2)

-- Вид реализации
SELECT * FROM KLS_VID_REAL_KONS WHERE ID IN (1,5)

-- Вид объекта
SELECT * FROM KLS_ORG_KIND WHERE ID IN (1,5)

-- Филиалы
SELECT * FROM ORG_STRUCTURE WHERE PLAN_REAL=1

-- Продукты 
SELECT * FROM KLS_PROD
WHERE EXISTS 
(SELECT NULL 
  FROM KLS_PROD_GROUPS_DESC A, KLS_PROD_GROUPS B 
 WHERE A.PROD_GROUPS_ID=B.ID
   AND B.PROD_TYPE_GRP_ID =4
   AND A.PROD_ID_NPR=KLS_PROD.ID_NPR
   )
ORDER BY ID_NPR   
   
   