-- Обновление справочников из КССС

-- Добавление кредиторов в R3_VENDORS  
INSERT INTO R3_VENDORS (ID,NAME,CITY,POST_CODE,STREET,INN,CUSTOMERS_ID)
SELECT DISTINCT
  C.ID,
  D.NAME,
  D.CITY_J AS CITY,
  D.INDEX_J AS POST_CODE,
  D.STREET_J AS STREET,
  D.INN,
  TO_CHAR(TO_NUMBER(D.R3_CUSTOME))
FROM
(
SELECT * FROM
(
SELECT 
  TO_CHAR(TO_NUMBER(R3_VENDORS)) AS ID,
  MAX(PREDPR_ID) AS KSSS_PREDPR_ID
FROM LOAD_BUFFER.KSSS_PREDPR
WHERE R3_VENDORS IS NOT NULL  
GROUP BY R3_VENDORS 
) A
WHERE NOT EXISTS (SELECT NULL FROM R3_VENDORS B WHERE B.ID=A.ID)
) C, LOAD_BUFFER.KSSS_PREDPR D
WHERE C.KSSS_PREDPR_ID=D.PREDPR_ID



-- Добавление дебиторов в R3_CUSTOMERS  
INSERT INTO R3_CUSTOMERS (ID,NAME,CITY,POST_CODE,STREET,INN,VENDORS_ID)
SELECT DISTINCT
  C.ID,
  D.NAME,
  D.CITY_J AS CITY,
  D.INDEX_J AS POST_CODE,
  D.STREET_J AS STREET,
  D.INN,
  TO_CHAR(TO_NUMBER(D.R3_VENDORS))
FROM
(
SELECT * FROM
(
SELECT 
  TO_CHAR(TO_NUMBER(R3_CUSTOME)) AS ID,
  MAX(PREDPR_ID) AS KSSS_PREDPR_ID
FROM LOAD_BUFFER.KSSS_PREDPR
WHERE R3_CUSTOME IS NOT NULL  
GROUP BY R3_CUSTOME 
) A
WHERE NOT EXISTS (SELECT NULL FROM R3_CUSTOMERS B WHERE B.ID=A.ID)
) C, LOAD_BUFFER.KSSS_PREDPR D
WHERE C.KSSS_PREDPR_ID=D.PREDPR_ID


-- Добавление записей в справочник контрагентов КССС
INSERT INTO KSSS_PREDPR (KSSS_PREDPR_ID, NAME, OKONX, KSSS_STATE_ID, INDEX_J, CITY_J, STREET_J, INN, OKPO, KSSS_BANK_STATE_ID, KSSS_BANK_ID, KORR) 
SELECT 
  PREDPR_ID,
  NAME,
  OKONX,
  STATE_ID, 
  INDEX_J, 
  CITY_J, 
  STREET_J, 
  INN, 
  OKPO, 
  MAX(BANK_STATE), 
  MAX(BANK_ID), 
  MAX(KORR)
FROM load_buffer.KSSS_PREDPR A
WHERE NOT EXISTS (SELECT NULL FROM KSSS_PREDPR B WHERE B.KSSS_PREDPR_ID=A.PREDPR_ID)
GROUP BY
  PREDPR_ID,
  NAME,
  OKONX,
  STATE_ID, 
  INDEX_J, 
  CITY_J, 
  STREET_J, 
  INN, 
  OKPO 

-- добавление связей между КССС и R3_VENDORS
INSERT INTO KSSS_PREDPR_R3_VENDORS_DESC (KSSS_PREDPR_ID, R3_VENDORS)
SELECT DISTINCT  
  PREDPR_ID,
  TO_CHAR(TO_NUMBER(R3_VENDORS))
FROM load_buffer.KSSS_PREDPR A
WHERE NOT EXISTS (SELECT NULL FROM KSSS_PREDPR_R3_VENDORS_DESC B WHERE B.KSSS_PREDPR_ID=A.PREDPR_ID)
  AND R3_VENDORS IS NOT NULL

-- добавление связей между КССС и R3_CUSTOMERS
INSERT INTO KSSS_PREDPR_R3_CUSTOMERS_DESC (KSSS_PREDPR_ID, R3_CUSTOMERS)
SELECT DISTINCT  
  PREDPR_ID,
  TO_CHAR(TO_NUMBER(R3_CUSTOME))
FROM load_buffer.KSSS_PREDPR A
WHERE NOT EXISTS (SELECT NULL FROM KSSS_PREDPR_R3_CUSTOMERS_DESC B WHERE B.KSSS_PREDPR_ID=A.PREDPR_ID)
  AND R3_CUSTOME IS NOT NULL
  
  

  

