-- Реализовано
SELECT
  NAME,
  PROD_ABBR,
  DATE_OPER,
  SUM(REALIZ_VES) as REALIZ_VES,
  SUM(REALIZ_SUMMA) as REALIZ_SUMMA,
  SUM(DECODE(SIGN(END_OST),-1,0,END_OST)) as OST
FROM
(
  SELECT /*+ rule */
    C.NAME,
    DECODE(E.GROUP_ORDER,50,'ДТ',60,'ДТ',70,'ДТ',E.GROUP_ABBR) as PROD_ABBR,
	KLS_PROD.ID_NPR,
    KLS_DATES.VALUE DATE_OPER,
	(SELECT SUM(AZC_OPERATION.VES) FROM AZC_OPERATION,AZC_TYPE_OPERATION 
	  WHERE DATE_OPER=KLS_DATES.VALUE 
        AND AZC_OPERATION.TYPE_OPER_ID=AZC_TYPE_OPERATION.ID
        AND AZC_TYPE_OPERATION.ID=1
   	    AND AZC_OPERATION.PROD_ID_NPR=KLS_PROD.ID_NPR
	    AND AZC_OPERATION.DISCOUNT<>815
		AND AZC_OPERATION.ORG_STRU_ID=C.ID) AS REALIZ_VES, -- Отгружено за период
	(SELECT SUM(AZC_OPERATION.SUMMA) FROM AZC_OPERATION,AZC_TYPE_OPERATION 
	  WHERE DATE_OPER=KLS_DATES.VALUE 
        AND AZC_OPERATION.TYPE_OPER_ID=AZC_TYPE_OPERATION.ID
        AND AZC_TYPE_OPERATION.ID=1
   	    AND AZC_OPERATION.PROD_ID_NPR=KLS_PROD.ID_NPR
	    AND AZC_OPERATION.DISCOUNT<>815
		AND AZC_OPERATION.ORG_STRU_ID=C.ID) AS REALIZ_SUMMA, -- Отгружено за период
     FOR_FILIAL.GET_OST_END_MAS(C.ID,KLS_PROD.ID_NPR,KLS_DATES.VALUE) as END_OST
  FROM KLS_DATES,KLS_PROD,V_ORG_STRUCTURE C,KLS_PROD_GROUPS_DESC D,KLS_PROD_GROUPS E
  WHERE C.ID IN (2003,2005,2008,2009,2016)
	AND KLS_PROD.ID_NPR=D.PROD_ID_NPR AND D.PROD_GROUPS_ID=E.ID AND E.PROD_TYPE_GRP_ID=5
	AND E.GROUP_ORDER IN (10,20,30,40,50,60,70)
	AND KLS_DATES.VALUE BETWEEN :dDATE_BEG AND :dDATE_END
)
GROUP BY	 
    NAME,
    PROD_ABBR,
    DATE_OPER 
	

	
	