-- Регионы реализации: 1 - Коми, 2 - Арханегльск, 3 - Прочие
-- Направление реализации: 1 - АЗС, 2-Нефтебазы, 3-Транзит

-- 1) План поставок с УНП
SELECT
  V_MASTER_REPORTS.REP_ID,
  V_MASTER_REPORTS.BEGIN_DATE,
  V_MASTER_REPORTS.END_DATE,
  DECODE(PLANSTRU_ID,95,2,178,2,1) AS REGION_ID, -- Регион реализации
  DECODE(PLANSTRU_ID,177,2,178,2,3) AS NAPR_ID, -- Направление реализации
  PROD_ID_NPR, -- Продукт
  SUM(PLAN_VES) AS PLAN_POST_VES -- Вес в тоннах
FROM PLAN_POST,KLS_PLANSTRU,PLAN_PERIODS,V_MASTER_REPORTS
WHERE PLAN_POST.PLANSTRU_ID=KLS_PLANSTRU.ID
  AND PLAN_POST.PLAN_PER_ID=PLAN_PERIODS.ID
  AND PLAN_POST.PLAN_ID=2 -- Московский план
  AND (KLS_PLANSTRU.PARENT_ID=93 AND KLS_PLANSTRU.ID NOT IN (97,105))-- План по ЛУКОЙЛ-СНП без хранения
  AND NLS_UPPER(V_MASTER_REPORTS.REPORT_FILE)='PF_REALIZ.XLS'
  AND PLAN_PERIODS.DATE_PLAN BETWEEN V_MASTER_REPORTS.BEGIN_DATE AND V_MASTER_REPORTS.END_DATE
GROUP BY    
  V_MASTER_REPORTS.REP_ID,
  V_MASTER_REPORTS.BEGIN_DATE,
  V_MASTER_REPORTS.END_DATE,
  DECODE(PLANSTRU_ID,95,2,178,2,1),
  DECODE(PLANSTRU_ID,177,2,178,2,3),
  PROD_ID_NPR

-- 2) План поставок ВНЕШНИХ ПОСТАВЩИКОВ
SELECT
  DECODE(PLANSTRU_ID,95,2,178,2,1) AS REGION_ID, -- Регион реализации
  DECODE(TIP_REAL_ID,1,2,3) AS NAPR_ID, -- Направление реализации
  PROD_ID_NPR, -- Продукт
  SUM(VES) AS PLAN_POST_VES -- Вес в тоннах
FROM PLAN_POST_SVOD
WHERE PLAN_POST_SVOD.SUPPLIER_ID<>2641 -- Все поставщики кроме ЛУКОЙЛ-СНП
  AND PLAN_POST_SVOD.DATE_PLAN BETWEEN TO_DATE('01.07.2003','dd.mm.yyyy') AND TO_DATE('31.07.2003','dd.mm.yyyy')
GROUP BY    
  DECODE(PLANSTRU_ID,95,2,178,2,1),
  DECODE(TIP_REAL_ID,1,2,3),
  PROD_ID_NPR

-- 3) Факт поставки 
SELECT
  DECODE(KLS_PLANSTRU.ID,95,2,178,2,1) AS REGION_ID, -- Регион реализации
  DECODE(MONTH.NPODOG_ID,NULL,2,3) AS NAPR_ID, -- Направление реализации
  KVIT.PROD_ID_NPR, -- Продукт
  SUM(VES_BRUTTO) AS FACT_POST_VES -- Вес в тоннах
FROM KVIT,MONTH,KLS_PLANSTRU
WHERE KVIT.NOM_ZD=MONTH.NOM_ZD 
  AND MONTH.PLANSTRU_ID=KLS_PLANSTRU.ID
  AND (KLS_PLANSTRU.PARENT_ID=93 AND KLS_PLANSTRU.ID NOT IN (97,105))-- План по ЛУКОЙЛ-СНП без хранения
  AND KVIT.DATE_OTGR BETWEEN TO_DATE('01.07.2003','dd.mm.yyyy') AND TO_DATE('31.07.2003','dd.mm.yyyy')
GROUP BY    
  DECODE(KLS_PLANSTRU.ID,95,2,178,2,1),
  DECODE(MONTH.NPODOG_ID,NULL,2,3),
  KVIT.PROD_ID_NPR

-- 4) План реализации
SELECT
  DECODE(ORG_STRU_ID,40,2,1) AS REGION_ID, -- Регион реализации
  DECODE(TIP_REAL_ID,2,3,DECODE(ORG_KIND_ID,5,1,2)) AS NAPR_ID, -- Направление реализации
  PROD_ID_NPR, -- Продукт
  SUM(VES) AS PLAN_REAL_VES -- Вес в тоннах
FROM PLAN_REALIZ
WHERE DATE_PLAN BETWEEN TO_DATE('01.07.2003','dd.mm.yyyy') AND TO_DATE('31.07.2003','dd.mm.yyyy')
GROUP BY    
  DECODE(ORG_STRU_ID,40,2,1),
  DECODE(TIP_REAL_ID,2,3,DECODE(ORG_KIND_ID,5,1,2)),
  PROD_ID_NPR

-- 5) Факт реализации (с АЗС и Нефтебаз)
SELECT
  DECODE(NVL(rela.FILIAL_ID,0),40,2,1) AS REGION_ID, -- Регион реализации
  DECODE(ORG_STRUCTURE.ORG_KIND_ID,5,1,2) AS NAPR_ID, -- Направление реализации
  PROD_ID_NPR, -- Продукт
  SUM(VES/1000) AS FACT_REAL_VES -- Вес в тоннах
FROM AZC_OPERATION,AZC_TYPE_OPERATION,ORG_STRUCTURE,
(
SELECT O_R.ORG_STRU_1_ID AS ORG_STRU_ID,O_R.ORG_STRU_2_ID AS FILIAL_ID 
   FROM ORG_RELATIONS O_R WHERE O_R.KIND_RELA_ID=1
) rela    
WHERE AZC_OPERATION.TYPE_OPER_ID=AZC_TYPE_OPERATION.ID
  AND AZC_TYPE_OPERATION.KIND_OPER=2
  AND AZC_OPERATION.ORG_STRU_ID=rela.ORG_STRU_ID(+)
  AND AZC_OPERATION.ORG_STRU_ID=ORG_STRUCTURE.ID
  AND DATE_OPER BETWEEN TO_DATE('01.07.2003','dd.mm.yyyy') AND TO_DATE('31.07.2003','dd.mm.yyyy')
GROUP BY    
  DECODE(NVL(rela.FILIAL_ID,0),40,2,1),
  DECODE(ORG_STRUCTURE.ORG_KIND_ID,5,1,2),
  PROD_ID_NPR
  
-- 6) Факт реализации (ТРАНЗИТ) 
SELECT
  DECODE(KLS_PLANSTRU.ID,95,2,178,2,1) AS REGION_ID, -- Регион реализации
  3 AS NAPR_ID, -- Направление реализации
  KVIT.PROD_ID_NPR, -- Продукт
  SUM(VES_BRUTTO) AS FACT_REAL_VES -- Вес в тоннах
FROM KVIT,MONTH,KLS_PLANSTRU
WHERE KVIT.NOM_ZD=MONTH.NOM_ZD 
  AND MONTH.PLANSTRU_ID=KLS_PLANSTRU.ID
  AND MONTH.NPODOG_ID IS NOT NULL
  AND (KLS_PLANSTRU.PARENT_ID=93 AND KLS_PLANSTRU.ID NOT IN (97,105))-- План по ЛУКОЙЛ-СНП без хранения
  AND KVIT.DATE_OTGR BETWEEN TO_DATE('01.07.2003','dd.mm.yyyy') AND TO_DATE('31.07.2003','dd.mm.yyyy')
GROUP BY    
  DECODE(KLS_PLANSTRU.ID,95,2,178,2,1),
  KVIT.PROD_ID_NPR
     
-- 7) Остатки на конец периода (АЗС и Нефтебазы)
SELECT
  DECODE(NVL(rela.FILIAL_ID,0),40,2,1) AS REGION_ID, -- Регион реализации
  DECODE(ORG_STRUCTURE.ORG_KIND_ID,5,1,2) AS NAPR_ID, -- Направление реализации
  KLS_PROD.ID_NPR AS PROD_ID_NPR, -- Продукт
  SUM(FOR_AZC.GET_AZC_OST_VES_ALL(ORG_STRUCTURE.ID,KLS_PROD.ID_NPR,TO_DATE('31.07.2003','dd.mm.yyyy'))/1000) AS END_OST -- Остаток в тоннах
FROM ORG_STRUCTURE,KLS_PROD,
(
SELECT O_R.ORG_STRU_1_ID AS ORG_STRU_ID,O_R.ORG_STRU_2_ID AS FILIAL_ID 
   FROM ORG_RELATIONS O_R WHERE O_R.KIND_RELA_ID=1
) rela    
WHERE ORG_STRUCTURE.ID=rela.ORG_STRU_ID(+)
  AND KLS_PROD.AZC_PR_GRP_ID IS NOT NULL
GROUP BY
  DECODE(NVL(rela.FILIAL_ID,0),40,2,1),
  DECODE(ORG_STRUCTURE.ORG_KIND_ID,5,1,2),
  KLS_PROD.ID_NPR

  
-- 8) Остатки на начало периода (АЗС и Нефтебазы) по консолидированной отчетности
SELECT COUNT(*) FROM OSTAT_KONS WHERE DATE_OST=TO_DATE('01.07.2003','dd.mm.yyyy')

SELECT
  DECODE(OSTAT_KONS.FILIAL_ID,40,2,1) AS REGION_ID, -- Регион реализации
  DECODE(ORG_STRUCTURE.ORG_KIND_ID,5,1,2) AS NAPR_ID, -- Направление реализации
  KLS_PROD.ID_NPR AS PROD_ID_NPR, -- Продукт
  SUM(KG/1000) AS BEGIN_OST -- Остаток в тоннах
FROM OSTAT_KONS,KLS_PROD_KONS,ORG_STRUCTURE,KLS_PROD
WHERE OSTAT_KONS.ORG_STRU_ID=ORG_STRUCTURE.ID 
  AND OSTAT_KONS.PROD_KONS_ID=KLS_PROD_KONS.ID
  AND KLS_PROD_KONS.PROD_ID_NPR=KLS_PROD.ID_NPR
  AND OSTAT_KONS.DATE_OST=TO_DATE('01.07.2003','dd.mm.yyyy')
GROUP BY
  DECODE(OSTAT_KONS.FILIAL_ID,40,2,1),
  DECODE(ORG_STRUCTURE.ORG_KIND_ID,5,1,2),
  KLS_PROD.ID_NPR

  
  
  
