SELECT 
  plat.predpr_name AS PLAT_NAME,
  KLS_DOG.DOG_NUMBER,
  DECODE(NVL(MONTH.KOL_DN_NPO,0),0,KLS_USL_OPL.KOL_DN,MONTH.KOL_DN_NPO) AS KOL_DN,
  KLS_PROD.NAME_NPR,
  MAX(MONTH.CENA_OTP_NPO) AS CENA_OTP_NPO,
  KLS_STAN.STAN_NAME,
  poluch.PREDPR_NAME AS POLUCH_NAME,
  KVIT.DATE_OTGR,
  SUM(KVIT.VES_BRUTTO) 
FROM 
  KVIT,MONTH,KLS_PREDPR plat,KLS_PREDPR poluch,KLS_STAN,KLS_DOG,KLS_PROD,KLS_USL_OPL
WHERE KVIT.nom_zd=MONTH.nom_zd
  AND MONTH.NPODOG_ID=KLS_DOG.ID
  AND KVIT.PROD_ID_NPR=KLS_PROD.ID_NPR
  AND MONTH.STAN_ID=KLS_STAN.ID
  AND KLS_DOG.PREDPR_ID=PLAT.ID
  AND MONTH.poluch_id=POLUCH.ID
  AND KLS_DOG.USL_OPL_ID=KLS_USL_OPL.ID(+)
  AND DATE_OTGR BETWEEN TO_DATE('01.07.2003','dd.mm.yyyy') AND TO_DATE('31.08.2003','dd.mm.yyyy')
  AND MONTH.PLANSTRU_ID IN (95,178)
GROUP BY 
  plat.predpr_name,
  KLS_DOG.DOG_NUMBER,
  DECODE(NVL(MONTH.KOL_DN_NPO,0),0,KLS_USL_OPL.KOL_DN,MONTH.KOL_DN_NPO),
  KLS_PROD.NAME_NPR,
  KLS_STAN.STAN_NAME,
  poluch.PREDPR_NAME,
  KVIT.DATE_OTGR
  

SELECT * 
FROM
(  
SELECT 
  MONTH.NOM_ZD,
  MONTH.LOAD_ABBR,
  plat.predpr_name AS PLAT_NAME,
  KLS_DOG.DOG_NUMBER,
  DECODE(NVL(MONTH.KOL_DN_NPO,0),0,KLS_USL_OPL.KOL_DN,MONTH.KOL_DN_NPO) AS KOL_DN,
  KLS_PROD.NAME_NPR,
  MONTH.PROD_ID_NPR,
  MAX(MONTH.CENA_OTP_NPO) AS CENA_OTP_NPO,
  KLS_STAN.STAN_NAME,
  KLS_STAN.ID AS STAN_ID,
  poluch.PREDPR_NAME AS POLUCH_NAME,
  MAX(MONTH.TONN_DECLARED) AS ZAYV_TONN,
  SUM(NVL(KV.VES_BRUTTO,0)) AS OTGR_TONN
FROM 
  MONTH,
    (SELECT * FROM KVIT WHERE KVIT.DATE_OTGR BETWEEN TO_DATE('01.07.2003','dd.mm.yyyy') AND TO_DATE('31.08.2003','dd.mm.yyyy')) kv,
  KLS_PREDPR plat,KLS_PREDPR poluch,KLS_STAN,KLS_DOG,KLS_PROD,KLS_USL_OPL,KLS_PLANSTRU
WHERE MONTH.nom_zd=KV.nom_zd(+)
  AND MONTH.NPODOG_ID=KLS_DOG.ID
  AND MONTH.PROD_ID_NPR=KLS_PROD.ID_NPR
  AND MONTH.STAN_ID=KLS_STAN.ID
  AND KLS_DOG.PREDPR_ID=PLAT.ID
  AND MONTH.poluch_id=POLUCH.ID
  AND KLS_DOG.USL_OPL_ID=KLS_USL_OPL.ID(+)
  AND MONTH.PLANSTRU_ID=KLS_PLANSTRU.ID
  AND KLS_PLANSTRU.REGION_ID=21
GROUP BY 
  MONTH.NOM_ZD,
  MONTH.LOAD_ABBR,
  plat.predpr_name,
  KLS_DOG.DOG_NUMBER,
  DECODE(NVL(MONTH.KOL_DN_NPO,0),0,KLS_USL_OPL.KOL_DN,MONTH.KOL_DN_NPO),
  KLS_PROD.NAME_NPR,
  MONTH.PROD_ID_NPR,
  KLS_STAN.STAN_NAME,
  KLS_STAN.ID,
  poluch.PREDPR_NAME
)
WHERE
   NOT ((SUBSTR(PROD_ID_NPR,1,3) NOT IN ('130','131') AND zayv_tonn-otgr_tonn<40 AND STAN_ID NOT IN(3,4) AND LOAD_ABBR<>'สอา') OR
       (zayv_tonn-otgr_tonn<0.5) OR
       (SUBSTR(PROD_ID_NPR,1,3) IN ('130','131') AND zayv_tonn-otgr_tonn<30 AND STAN_ID NOT IN (3,4) AND LOAD_ABBR<>'สอา'))
    