CREATE OR REPLACE VIEW V_RITM_POST_PLAN AS 
SELECT
  -- Анализ ритмичности: План поставок с учетом ОБР
  plat.ID AS PLAT_ID,
  plat.SF_NAME AS PLAT_NAME,
  SUM(A.PLAN_VES) AS PLAN_VES
FROM PLAN_POST A, PLAN_PERIODS P, KLS_DOG D, KLS_PREDPR plat, 
           (SELECT * FROM V_MASTER_REPORTS WHERE NLS_UPPER(REPORT_FILE)='RITM_POST.XLS') r  
WHERE A.DOG_ID=D.ID
      AND A.PLAN_ID IN (2,3)
      AND A.PLAN_PER_ID=P.ID
	  AND P.DATE_PLAN BETWEEN r.BEGIN_DATE AND r.END_DATE
	  AND D.PREDPR_ID=plat.ID
	  AND A.PROD_ID_NPR<>'90000'
	  AND D.AGENT_ID IN (8,1) AND plat.ID<>1334
	  AND plat.ID=DECODE(r.IS_UNP,1,plat.ID,2641)
GROUP BY
  plat.ID,
  plat.SF_NAME


CREATE OR REPLACE VIEW V_RITM_POST_GRAFIK AS 
SELECT  
  --Анализ ритмичности: График поставок по декадам
  PLAT_ID,
  PLAT_NAME,
  NUM_DECADA,
  ROUND(SUM(GRAF_VES),0) AS GRAF_VES
FROM
(    
  -- График поставок по ЖД
  SELECT /*+ RULE */
    plat.ID AS PLAT_ID,
    plat.SF_NAME AS PLAT_NAME,
    (CASE
        WHEN TO_NUMBER(TO_CHAR(GU12_BR.DATE_R,'DD'))<=10 THEN 1
        WHEN TO_NUMBER(TO_CHAR(GU12_BR.DATE_R,'DD'))<=20 THEN 2
  	    ELSE 3
  	 END) AS NUM_DECADA,
    GU12_BR.VES AS GRAF_VES
  FROM GU12_A,GU12_B,GU12_BR,KLS_PREDPR plat,
           (SELECT * FROM V_MASTER_REPORTS WHERE NLS_UPPER(REPORT_FILE)='RITM_POST.XLS') r  
  WHERE
	GU12_BR.ID_B=GU12_B.ID AND
    GU12_B.ID_A=GU12_A.ID AND
	GU12_BR.DATE_R BETWEEN r.BEGIN_DATE AND r.END_DATE AND
	GU12_B.PLAT_ID=plat.ID
    AND GU12_A.PROD_ID<>'201005'
    AND plat.ID=DECODE(r.IS_UNP,1,plat.ID,2641)
  UNION ALL
  -- График поставок по автоналиву  
  SELECT
    pp.PLAT_ID,
    pp.PLAT_NAME,
    wd.NUM_DECADA,
    pp.PLAN_VES*wd.COUNT_DECADA/wd.COUNT_MON AS GRAF_VES
  FROM   
  (
    SELECT /*+ RULE */
      plat.ID AS PLAT_ID,
      plat.SF_NAME AS PLAT_NAME,
      SUM(ZAKAZ.VES) AS plan_ves
    FROM ZAKAZ,KLS_DOG,KLS_PREDPR plat,
           (SELECT * FROM V_MASTER_REPORTS WHERE NLS_UPPER(REPORT_FILE)='RITM_POST.XLS') r  
    WHERE ZAKAZ.DOG_ID=KLS_DOG.ID AND KLS_DOG.PREDPR_ID=plat.ID AND
      ZAKAZ.STAN_ID=2595 AND -- Автоналив
   	  ZAKAZ.IS_ACCEPT=1 AND -- Утвержденные
      ZAKAZ.DATE_PLAN BETWEEN r.BEGIN_DATE AND r.END_DATE AND
	  ZAKAZ.IS_AGENT=1 -- Только заказы УНП
	  AND KLS_DOG.AGENT_ID IN (8,1) AND plat.ID<>1334
      AND plat.ID=DECODE(r.IS_UNP,1,plat.ID,2641)
    GROUP BY
      plat.ID,
      plat.SF_NAME
  ) pp,
  (
     -- Расчет кол-ва рабочих дней подекадно и за месяц
    SELECT
      A.NUM_DECADA,
  	  SUM(A.IS_WORK) AS COUNT_DECADA,
      MAX(B.COUNT_MON) AS COUNT_MON		
    FROM
      (	
       SELECT
          (CASE
            WHEN TO_NUMBER(TO_CHAR(VALUE,'DD'))<=10 THEN 1
            WHEN TO_NUMBER(TO_CHAR(VALUE,'DD'))<=20 THEN 2
  	        ELSE 3
    	   END) AS NUM_DECADA,
          IS_WORK 	 
        FROM KLS_DATES,
           (SELECT * FROM V_MASTER_REPORTS WHERE NLS_UPPER(REPORT_FILE)='RITM_POST.XLS') r  
        WHERE VALUE BETWEEN r.BEGIN_DATE AND r.END_DATE
	  ) a,
      (	
       SELECT
          SUM(IS_WORK) AS COUNT_MON 	 
        FROM KLS_DATES,
           (SELECT * FROM V_MASTER_REPORTS WHERE NLS_UPPER(REPORT_FILE)='RITM_POST.XLS') r  
        WHERE VALUE BETWEEN r.BEGIN_DATE AND r.END_DATE
	  ) b
    GROUP BY A.NUM_DECADA	  
  ) wd
)
GROUP BY 
  PLAT_ID,
  PLAT_NAME,
  NUM_DECADA
	
  
CREATE OR REPLACE VIEW V_RITM_POST_FACT AS 
SELECT  
  --Анализ ритмичности: Факт поставок
  PLAT_ID,
  PLAT_NAME,
  NUM_DECADA,
  ROUND(SUM(FACT_VES),0) AS FACT_VES
FROM
(    
  SELECT /*+ RULE */
    plat.ID AS PLAT_ID,
    plat.SF_NAME AS PLAT_NAME,
    (CASE
        WHEN TO_NUMBER(TO_CHAR(KVIT.DATE_OTGR,'DD'))<=10 THEN 1
        WHEN TO_NUMBER(TO_CHAR(KVIT.DATE_OTGR,'DD'))<=20 THEN 2
  	    ELSE 3
  	 END) AS NUM_DECADA,
    KVIT.VES_BRUTTO AS FACT_VES
  FROM KVIT,MONTH,KLS_DOG,KLS_PREDPR plat,
           (SELECT * FROM V_MASTER_REPORTS WHERE NLS_UPPER(REPORT_FILE)='RITM_POST.XLS') r  
  WHERE
	KVIT.NOM_ZD=MONTH.NOM_ZD AND MONTH.DOG_ID=KLS_DOG.ID AND KLS_DOG.PREDPR_ID=plat.ID AND
	KVIT.DATE_OTGR BETWEEN r.BEGIN_DATE AND r.END_DATE AND
    KVIT.PROD_ID_NPR<>'90000' 
    AND KLS_DOG.AGENT_ID IN (8,1) AND plat.ID<>1334
    AND plat.ID=DECODE(r.IS_UNP,1,plat.ID,2641)
)
GROUP BY 
  PLAT_ID,
  PLAT_NAME,
  NUM_DECADA

  

CREATE OR REPLACE VIEW V_RITM_POST AS 
SELECT
  --Анализ ритмичности: План/Факт поставок
  r.BEGIN_DATE,
  r.END_DATE,
  RusMonth(r.END_DATE) AS Period_Name,
  a.PLAT_ID,a.PLAT_NAME,
  SUM(PLAN_VES) AS PLAN,
  SUM(GRAF_1) AS GRAF_1,
  SUM(FACT_1) AS FACT_1,
  SUM(GRAF_2) AS GRAF_2,
  SUM(FACT_2) AS FACT_2,
  SUM(GRAF_3) AS GRAF_3,
  SUM(FACT_3) AS FACT_3
FROM
(    
  SELECT 
    PLAT_ID,PLAT_NAME,PLAN_VES,
    0 AS GRAF_1,
    0 AS FACT_1,
    0 AS GRAF_2,
    0 AS FACT_2,
    0 AS GRAF_3,
    0 AS FACT_3
  FROM V_RITM_POST_PLAN
  UNION ALL
  SELECT 
    PLAT_ID,
	PLAT_NAME,
	0 AS PLAN_VES,
    DECODE(NUM_DECADA,1,GRAF_VES,0) AS GRAF_1,
    0 AS FACT_1,
    DECODE(NUM_DECADA,2,GRAF_VES,0) AS GRAF_2,
    0 AS FACT_2,
    DECODE(NUM_DECADA,3,GRAF_VES,0) AS GRAF_3,
    0 AS FACT_3
  FROM V_RITM_POST_GRAFIK
  UNION ALL
  SELECT 
    PLAT_ID,
	PLAT_NAME,
	0 AS PLAN_VES,
    0 AS GRAF_1,
    DECODE(NUM_DECADA,1,FACT_VES,0) AS FACT_1,
    0 AS GRAF_2,
    DECODE(NUM_DECADA,2,FACT_VES,0) AS FACT_2,
    0 AS GRAF_3,
    DECODE(NUM_DECADA,3,FACT_VES,0) AS FACT_3
  FROM V_RITM_POST_FACT
) a, (SELECT * FROM V_MASTER_REPORTS WHERE NLS_UPPER(REPORT_FILE)='RITM_POST.XLS') r  
GROUP BY 
  r.BEGIN_DATE,
  r.END_DATE,
  a.PLAT_ID,
  a.PLAT_NAME  
