SELECT I.*,O.* 
FROM 
  INORDERS I, V_DOCLINKS_INOUT_OUT L, DELIVERYORD O
WHERE I.RN=L.NOUT_DOCUMENT
  AND L.SOUT_UNITCODE='IncomingOrders'
  AND L.SUNITCODE='DeliveryOrders'
  AND L.NDOCUMENT=O.RN(+)
  AND I.INDOCDATE BETWEEN TO_DATE('01.03.2004','dd.mm.yyyy') AND  TO_DATE('31.03.2004','dd.mm.yyyy')
