SELECT DISTINCT /*+ RULE */
  KLS_PREDPR.PREDPR_NAME,
  KLS_PREDPR.POSTINDEX_J||' '||KLS_REGION.REGION_NAME||' '||CITY_J||' '||ADDRESS_J as address_J,
  KLS_PREDPR.POSTINDEX_P||' '||CITY_P||' '||ADDRESS_P as address_P,
  KLS_PREDPR.INN,
  KLS_PREDPR.OKONH,
  KLS_PREDPR.OKPO,
  KLS_PREDPR.GD_KOD,
  KLS_PREDPR.OKVED,
  KLS_PREDPR.OGRN,
  KLS_PREDPR.RS,
  KLS_BANKS.BANK_NAME,
  KLS_BANKS.POSTINDEX as BANK_POSTINDEX,
  KLS_BANKS.ADDRESS as BANK_ADDRESS,
  KLS_PREDPR.BANK_KORS,
  KLS_PREDPR.EMAIL,
  KLS_PREDPR.FAX,
  KLS_PREDPR.PHONE,
  KLS_HOLDING.HOLDING_NAME,
  KLS_PERTYPE.PERTYPE_NAME,
  KLS_PREDPR_CLASS.NAME as CLASS_NAME
/*  KLS_STAN.STAN_KOD,
  KLS_STAN.STAN_NAME,
  KLS_VETKA.VETKA_NAME,
  STAN_REGION.REGION_NAME as STAN_REGION*/
  /*,
  KLS_PREDPR.EX_SVID,
  KLS_PREDPR_AKCIZ.EX_SVID_PREF,
  KLS_PREDPR_AKCIZ.EX_SVID_NUMB,
  KLS_PREDPR_AKCIZ.DATE_GIVE,
  KLS_PREDPR_AKCIZ.DATE_BEG,
  KLS_PREDPR_AKCIZ.DATE_END,
  KLS_PREDPR_AKCIZ.DATE_CANCEL*/
FROM
  MONTH, USL_DOG,KLS_DOG,KLS_PREDPR,KLS_REGION, KLS_BANKS,KLS_HOLDING, KLS_PERTYPE, KLS_PREDPR_CLASS, KLS_PREDPR_AKCIZ,
  KLS_STAN,KLS_VETKA,KLS_REGION STAN_REGION
WHERE
  MONTH.DOG_ID=USL_DOG.DOG_ID AND 
  MONTH.USL_NUMBER=USL_DOG.USL_NUMBER AND 
  MONTH.DATE_PLAN>=TO_DATE('01.01.2004','dd.mm.yyyy') AND
  MONTH.STAN_ID=KLS_STAN.ID AND
  KLS_STAN.REGION_ID=STAN_REGION.ID(+) AND
  MONTH.VETKA_ID=KLS_VETKA.ID(+) AND
  USL_DOG.DOG_ID=KLS_DOG.ID AND
  KLS_DOG.PREDPR_ID=KLS_PREDPR.ID AND
  KLS_PREDPR.REGION_ID=KLS_REGION.ID(+) AND
  KLS_PREDPR.BANKS_ID=KLS_BANKS.ID(+) AND
  KLS_PREDPR.HOLDING_ID=KLS_HOLDING.ID(+) AND
  KLS_PREDPR.PERTYPE_ID=KLS_PERTYPE.ID(+) AND
  KLS_PREDPR.CLASS_ID=KLS_PREDPR_CLASS.ID(+) AND
  KLS_PREDPR.ID=KLS_PREDPR_AKCIZ.PLAT_ID(+)  

    
