
SELECT 
  pp.PROD_ID_NPR as kod_npr,
  k.ID as KODIF_ID,
  MIN(b.NORM_POKAZATEL) as NORMTU,
  MIN(b.NOMER_PP) as NPP,
  MIN(b.NOMER_PP*100+b.NOMER_INSIDE) as SORTBY,
  MIN(sp.NAME_POKAZATEL) as NAME,
  MIN(k.FIELD_TYPE) as FIELD_TYPE,
  MIN(k.FIELD_LEN) as FIELD_LEN,
  MIN(k.FIELD_DEC) as FIELD_DEC,
  MIN(k.FIELD_SVED) as FIELD_SVED,
  MIN(b.KOD_POKAZATEL) as KOD_POKAZATEL
FROM UNP_PASPORT p, UNP_NORM_PASP b, KLS_KODIF_PASP_UNP i, kls_kodif k, UNP_SPRAV_POKAZATEL sp, KLS_PROD_PASP_UNP pp
WHERE p.DATE_PASPORT>=TO_DATE('01.01.2006','dd.mm.yyyy')
  AND p.KOD_OIL_PRODUCT=b.KOD_OIL_PRODUCT
  AND b.KOD_POKAZATEL=sp.KOD_POKAZATEL
  AND b.KOD_POKAZATEL=i.KOD_POKAZATEL
  AND p.KOD_OIL_PRODUCT=pp.KOD_OIL_PRODUCT
  and i.KODIF_ID=k.id
  and k.field_sved||' ' not in ('PL20_KG ','PL20 ','PL15 ')
  and p.NOMER_CISTERN is not null
  and b.KOD_POKAZATEL not in (266,200)
group by 
  pp.PROD_ID_NPR,
  k.ID
ORDER BY
  kod_npr,sortby  
  
